"use client";
import {useEffect,useRef,useState} from 'react';
import {syncosFetch} from '../intelligence/api';
import {PermissionLink} from '../access-control';
type Choice={key:string;label:string};type Row={id:string;title:string|null;status:string;created_at:string;href:string|null};
export default function RecordHistory(){
 const [choices,setChoices]=useState<Choice[]>([]),[resource,setResource]=useState(''),[q,setQ]=useState(''),[appliedQ,setAppliedQ]=useState(''),[rows,setRows]=useState<Row[]>([]),[next,setNext]=useState<string|null>(null),[before,setBefore]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const generation=useRef(0);
 useEffect(()=>{syncosFetch<Choice[]>('record-history').then(setChoices).catch(e=>setError(e.message));},[]);
 async function load(key:string,search:string,cursor=''){const current=++generation.current;setBusy(true);setError('');try{const query=new URLSearchParams({q:search});if(cursor)query.set('before',cursor);const result=await syncosFetch<{rows:Row[];next:string|null}>('record-history/'+key+'?'+query);if(current!==generation.current)return;setRows(result.rows);setAppliedQ(search);setNext(result.next);setBefore(cursor);}catch(e){if(current===generation.current)setError((e as Error).message);}finally{if(current===generation.current)setBusy(false);}}
 return <main className="completion-workspace" style={{maxWidth:1000,margin:'auto',padding:24}}><h1>Record history</h1><p>Find older records beyond the recent items shown in workspaces. Search the selected record type across its full available history. Detailed records keep their existing permissions and actions.</p>{error&&<p role="alert">{error}</p>}<form onSubmit={e=>{e.preventDefault();if(resource)void load(resource,q);}}><label>Record type<select required value={resource} disabled={busy} onChange={e=>{const key=e.target.value;generation.current++;setResource(key);setRows([]);setNext(null);setBefore('');setQ('');if(key)void load(key,'');}}><option value="">Choose record type</option>{choices.map(c=><option key={c.key} value={c.key}>{c.label}</option>)}</select></label><label>Search name, reference, status or record ID<input maxLength={200} value={q} onChange={e=>setQ(e.target.value)}/></label><button disabled={!resource||busy}>Search history</button></form>{busy&&<p role="status">Loading history…</p>}{resource&&!busy&&!error&&!rows.length&&<p>No matching records on this page.</p>}<ul style={{listStyle:'none',padding:0}}>{rows.map(row=><li key={row.id} style={{padding:16,borderBottom:'1px solid #8c9bab',overflowWrap:'anywhere'}}>{row.href?<PermissionLink href={row.href}>{row.title||row.id}</PermissionLink>:<strong>{row.title||row.id}</strong>}<p>{row.status} · {new Date(row.created_at).toLocaleString()}</p><small>Reference: {row.id}</small></li>)}</ul>{next&&<button disabled={busy} onClick={()=>void load(resource,appliedQ,next)}>Older matching records</button>}{before&&<button disabled={busy} onClick={()=>void load(resource,appliedQ)}>Back to latest</button>}</main>;
}
