"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {syncosFetch} from '../intelligence/api';
export function InventoryDiscrepancies({canResolve}:{canResolve:boolean}){
 const [data,setData]=useState<{rows:any[];next:string|null}>({rows:[],next:null}),[busy,setBusy]=useState(false),[error,setError]=useState('');const gate=useRef(false);
 async function load(before?:string){if(gate.current)return;gate.current=true;setBusy(true);try{setData(await syncosFetch('material-inventory/discrepancies'+(before?'?before='+before:'')));setError('');}catch(e){setError((e as Error).message);}finally{gate.current=false;setBusy(false);}}
 useEffect(()=>{void load();},[]);
 async function resolve(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();if(gate.current)return;gate.current=true;setBusy(true);const f=Object.fromEntries(new FormData(e.currentTarget));try{await syncosFetch('material-inventory/discrepancies/'+id+'/resolve',{method:'POST',body:{...f,no_adjustment_needed:f.no_adjustment_needed==='on'}});gate.current=false;await load();}catch(e){setError((e as Error).message);}finally{gate.current=false;setBusy(false);}}
 return <section><h2>Company material review queue</h2>{error&&<p role="alert">{error}</p>}<p>Review the count evidence and movement history. If stock needs correction, record an approved count adjustment above and link its movement reference here.</p>{!busy&&!data.rows.length&&<p>No reported discrepancies.</p>}{data.rows.map(r=><details key={r.id}><summary>{r.company_name} · {r.material_label} · {r.status}</summary><p>Count {r.reported_count}; recorded {r.recorded_balance} · {r.reference}</p><p>{r.description}</p>{r.status==='resolved'?<p>{r.resolution_note}</p>:canResolve&&<form onSubmit={e=>void resolve(e,r.id)}><fieldset disabled={busy}><legend>Resolve this discrepancy</legend><label>Resolution and evidence<textarea name="resolution_note" minLength={3} maxLength={1000} required/></label><label>Approved adjustment movement ID (if stock changed)<input name="adjustment_id"/></label><label><input type="checkbox" name="no_adjustment_needed"/> Review confirmed no adjustment was needed.</label><button>Record resolution</button></fieldset></form>}</details>)}<button disabled={busy} onClick={()=>void load()}>Refresh review queue</button>{data.next&&<button disabled={busy} onClick={()=>void load(data.next!)}>Older reviews</button>}</section>;
}
