"use client";
import {SearchChoice} from '../search-choice';
import {HistoryControls} from '../history-controls';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {CommandShell,Panel} from '../dashboard-components';
import {useCapability} from '../access-control';
import {syncosFetch} from '../intelligence/api';
type Choice={id:string;label:string;serial_number?:string;unit?:string};
type Data={usage:{lot_id:string;work_order_id:string;work_order_number:string;project_name:string;kind:string;quantity:string}[];lots:Choice[];locations:Choice[];crews:Choice[];work_orders:Choice[];balances:{lot_id:string;location_id:string;balance:string}[];movements:{id:string;lot_id:string;kind:string;quantity:string;reference:string;reason:string;created_at:string}[]};
function Choices({name,label,rows,required=false}:{name:string;label:string;rows:Choice[];required?:boolean}){return <label>{label}<select name={name} required={required}><option value="">Select {label.toLowerCase()}</option>{rows.map(r=><option key={r.id} value={r.id}>{r.label}{r.serial_number?` · ${r.serial_number} (${r.unit})`:''}</option>)}</select></label>;}
export default function MaterialInventory(){
 const manage=useCapability('inventory.manage'),adjust=useCapability('inventory.adjust');
 const [data,setData]=useState<Data>({usage:[],lots:[],locations:[],crews:[],work_orders:[],balances:[],movements:[]}),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[kind,setKind]=useState('receipt');
 const gate=useRef(false),keys=useRef<Record<string,string>>({}),errorRef=useRef<HTMLDivElement>(null);
 const historyQuery=useRef('');const [moreHistory,setMoreHistory]=useState(true);
 async function history(q:string,older=false){if(gate.current)return;gate.current=true;setBusy(true);setError('');try{const params=new URLSearchParams({q});if(older&&data.movements.length)params.set('before',data.movements[data.movements.length-1].id);const result=await syncosFetch<typeof data>(`material-inventory?${params}`);historyQuery.current=q;setMoreHistory(result.movements.length===200);setData(old=>({...result,movements:older?[...old.movements,...result.movements.filter(v=>!old.movements.some(x=>x.id===v.id))]:result.movements}));}catch(e){setError((e as Error).message);}finally{gate.current=false;setBusy(false);}}
 async function load(){historyQuery.current='';setMoreHistory(true);setData(await syncosFetch<Data>('material-inventory'));setLoaded(true);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);useEffect(()=>{if(error)errorRef.current?.focus();},[error]);
 async function save(e:FormEvent<HTMLFormElement>,endpoint:string){e.preventDefault();if(gate.current)return;gate.current=true;setBusy(true);setError('');setMessage('');const form=e.currentTarget,f=Object.fromEntries(new FormData(form));try{
  if(!keys.current[endpoint])keys.current[endpoint]=crypto.randomUUID();
  await syncosFetch(`material-inventory/${endpoint}`,{method:'POST',body:{...f,approved:f.approved==='on',request_key:keys.current[endpoint]}});
  form.reset();keys.current[endpoint]='';setKind('receipt');setMessage('Record saved. Review the updated balance and movement history.');await load();
 }catch(e){setError((e as Error).message+' Your entries are preserved.');}finally{gate.current=false;setBusy(false);}}
 const lot=(id:string)=>data.lots.find(l=>l.id===id),location=(id:string)=>data.locations.find(l=>l.id===id)?.label??'Unknown location';
 return <div className="completion-workspace"><CommandShell title="Material and reel inventory" purpose="Track physical stock and custody. Installed material records do not approve production, customer acceptance or billing.">
  {error&&<div role="alert" ref={errorRef} tabIndex={-1}>{error}<button disabled={busy} onClick={()=>load().then(()=>setError('')).catch(e=>setError(e.message))}>Retry loading inventory</button></div>}{message&&<p role="status">{message}</p>}{!loaded&&!error&&<p role="status">Loading inventory…</p>}
  {manage&&<Panel title="Register material and locations"><form onSubmit={e=>save(e,'lots')} onChange={()=>{keys.current.lots='';}}><fieldset disabled={busy}><legend>Material lot or reel</legend><label>Material name<input name="label" required maxLength={1000}/></label><label>Reel or lot identifier<input name="serial_number" required maxLength={1000}/></label><label>Unit<select name="unit"><option value="feet">Feet</option><option value="each">Each</option></select></label><button>Register material</button></fieldset></form>
   <form onSubmit={e=>save(e,'locations')}><fieldset disabled={busy}><legend>Warehouse or crew custody location</legend><label>Location name<input name="label" required maxLength={1000}/></label><SearchChoice endpoint="material-inventory/choices?kind=crews" name="crew_id" label="Crew (optional)" rows={data.crews}/><p>Leave crew blank for a warehouse. Both Sync and partner crews can have custody locations.</p><button>Register location</button></fieldset></form></Panel>}
  {manage&&<Panel title="Record material movement"><form onSubmit={e=>save(e,'movements')} onChange={()=>{keys.current.movements='';}}><fieldset disabled={busy||!loaded}><Choices name="lot_id" label="Material lot" rows={data.lots} required/><label>Movement<select name="kind" value={kind} onChange={e=>setKind(e.target.value)}>{[['receipt','Receive from supplier'],['transfer','Transfer or return'],['installed','Installed use'],['offcut','Offcut removed from usable stock'],['scrap','Scrap']].map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label>
   {kind!=='receipt'&&<Choices name="from_location_id" label="Source location" rows={data.locations} required/>}{['receipt','transfer'].includes(kind)&&<Choices name="to_location_id" label="Destination location" rows={data.locations} required/>}
   <label>Quantity<input name="quantity" type="number" min="0.0001" step="0.0001" required/></label><SearchChoice endpoint="material-inventory/choices?kind=work_orders" name="work_order_id" label="Work order" rows={data.work_orders} required={kind==='installed'}/><label>Supplier receipt or supporting document reference<input name="reference" required maxLength={1000}/></label><label>Reason<textarea name="reason" required maxLength={1000}/></label><p>A reusable offcut remains stock: transfer it to a custody location. Use offcut removal only for material no longer counted as usable.</p><button>Record movement</button></fieldset></form></Panel>}
  {adjust&&<Panel title="Approve a count adjustment"><form onSubmit={e=>save(e,'adjustments')} onChange={()=>{keys.current.adjustments='';}}><fieldset disabled={busy||!loaded}><Choices name="lot_id" label="Material lot" rows={data.lots} required/><Choices name="to_location_id" label="Counted location" rows={data.locations} required/><label>Difference from recorded balance<input name="quantity" type="number" step="0.0001" required/><small>Positive adds stock; negative removes stock. Enter the difference, not the total physical count.</small></label><label>Count sheet reference<input name="reference" required maxLength={1000}/></label><label>Discrepancy explanation<textarea name="reason" required maxLength={1000}/></label><label><input name="approved" type="checkbox" required/> I reviewed the physical count and approve this adjustment.</label><button>Approve adjustment</button></fieldset></form></Panel>}
  <Panel title="Current stock"><div className="table-wrap"><table><thead><tr><th>Material / reel</th><th>Custody</th><th>Balance</th></tr></thead><tbody>{data.balances.map(b=><tr key={b.lot_id+b.location_id}><td>{lot(b.lot_id)?.label} · {lot(b.lot_id)?.serial_number}</td><td>{location(b.location_id)}</td><td>{b.balance} {lot(b.lot_id)?.unit}</td></tr>)}</tbody></table></div>{loaded&&!data.balances.length&&<p>Register material and record its receipt to establish the opening stock.</p>}</Panel>
  <Panel title="Work-order material reconciliation"><p>Physical usage is shown separately from production and accepted billable quantities.</p><div className="table-wrap"><table><thead><tr><th>Project / work order</th><th>Material</th><th>Use</th><th>Quantity</th></tr></thead><tbody>{(data.usage??[]).map(u=><tr key={u.lot_id+u.work_order_id+u.kind}><td>{u.project_name} · {u.work_order_number}</td><td>{lot(u.lot_id)?.label} · {lot(u.lot_id)?.serial_number}</td><td>{u.kind}</td><td>{u.quantity} {lot(u.lot_id)?.unit}</td></tr>)}</tbody></table></div></Panel>
  <Panel title="Movement history"><HistoryControls label="movements" busy={busy} more={moreHistory&&data.movements.length>=200} onSearch={q=>void history(q)} onMore={()=>void history(historyQuery.current,true)}/><p>History is shown newest first. History is retained; discrepancies require a separate approved adjustment.</p>{data.movements.map(m=><details key={m.id}><summary>{lot(m.lot_id)?.label} · {m.kind} · {m.quantity} {lot(m.lot_id)?.unit} · {new Date(m.created_at).toLocaleString()}</summary><p>{m.reason}</p><p>Source: {m.reference}</p></details>)}</Panel>
 </CommandShell></div>;
}
