"use client";
import { useEffect,useRef,useState,type FormEvent } from 'react';
import { syncosFetch } from '../intelligence/api';
type Jsa={id:string;revision_number:number;work_date:string;work_location:string;hazards:string[];controls:string[];acknowledged_at?:string;can_request_pre_bore:boolean};
type Control={classification_review_required:boolean;id:string;control_type:string;reason:string;work_location?:string;status:string;required_approvals:string[];approvals:{approval_kind:string;approver_name:string;approved_at:string}[]};
type Data={versions:{id:string;work_order_number:string;version_number:number;pre_bore_required:boolean;safety_scope_reviewed_at?:string}[];staff:boolean;roles:string[];controls:Control[];work_orders:{id:string;work_order_number:string;title:string}[];crews:{id:string;name:string}[]};
const authorities:Record<string,string[]>={construction_supervisor:['field_supervisor','project_manager','operations_manager','executive'],utility_owner:['safety_manager','executive'],safety:['safety_manager','executive'],operations:['operations_manager','executive']};
const label=(s:string)=>s.replaceAll('_',' ');
export default function WorkSafety(){
 const [jsas,setJsas]=useState<Jsa[]>([]),[data,setData]=useState<Data>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const guard=useRef(false);
 async function load(){const [j,d]=await Promise.all([syncosFetch<Jsa[]>('work-safety/my-jsas'),syncosFetch<Data>('work-safety/controls')]);setJsas(j);setData(d);}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 async function submit(e:FormEvent<HTMLFormElement>,path:string,extra:Record<string,unknown>={}){e.preventDefault();if(guard.current)return;const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));guard.current=true;setBusy(true);setError('');setMessage('');try{await syncosFetch(path,{method:'POST',body:{...values,...extra,confirmed:values.confirmed==='on',verified:values.verified==='on',utility_strike:values.utility_strike==='on',pre_bore_required:values.pre_bore_required==='on',...(values.approved_at?{approved_at:new Date(String(values.approved_at)).toISOString()}:{})}});form.reset();await load();setMessage('Safety record saved. Production remains blocked until every applicable requirement is satisfied.');}catch(e){setError(e instanceof Error?e.message:'Unable to save. Check connection and retry.');}finally{setBusy(false);guard.current=false;}}
 return <main className="page"><header className="page-header"><h1>Safety reviews and work authorization</h1><p>Each worker acknowledges their own review. Foreman certification, pre-bore authorization and restart approvals are separate records.</p></header>
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{!data&&!error&&<p role="status">Loading your safety records…</p>}
 {data?.roles.some(r=>['safety_manager','operations_manager','project_manager','executive'].includes(r))&&<section className="partner-panel"><h2>Review work-order safety scope</h2><p>Review the governing safety requirements before production starts. Underground production codes always require pre-bore approval.</p>{data.versions.map(v=><details key={v.id}><summary>{v.work_order_number} · version {v.version_number} · {v.safety_scope_reviewed_at?'Reviewed':'Review required'}</summary><form onSubmit={e=>void submit(e,`work-safety/work-orders/${v.id}/scope-review`)}><fieldset disabled={busy}><legend>Safety requirements for this version</legend><label><input type="checkbox" name="pre_bore_required" defaultChecked={v.pre_bore_required}/> Pre-bore approval required</label><label>Governing requirements and reviewed scope reference<input name="evidence_reference" required/></label><button className="partner-button wide-touch">Save safety scope review</button></fieldset></form></details>)}</section>}
 <section className="partner-panel"><h2>My safety reviews</h2>{data&&!jsas.length&&<p>No completed safety review is assigned to your linked worker account. Ask your supervisor to verify your crew membership and account link.</p>}
 {jsas.map(j=><article className="partner-panel" key={j.id}><h3>{j.work_location} · revision {j.revision_number}</h3><p>Work date: {j.work_date.slice(0,10)}</p><p><strong>Hazards:</strong> {j.hazards.map(label).join(', ')}</p><p><strong>Controls:</strong> {j.controls.map(label).join(', ')}</p>
 {j.acknowledged_at?<p>Personally acknowledged at {new Date(j.acknowledged_at).toLocaleString()}.</p>:<form onSubmit={e=>void submit(e,`work-safety/jsas/${j.id}/acknowledge`,{revision_number:j.revision_number})}><fieldset disabled={busy}><legend>Personal acknowledgment</legend><label><input type="checkbox" name="confirmed" required/> I am the signed-in worker. I reviewed these hazards and controls and understand my stop-work authority.</label><button className="partner-button wide-touch" disabled={busy}>{busy?'Saving…':'Acknowledge my safety review'}</button></fieldset></form>}
 {j.can_request_pre_bore&&<details><summary>Request a pre-bore inspection</summary><form onSubmit={e=>void submit(e,'work-safety/pre-bore',{daily_jsa_id:j.id})}><fieldset disabled={busy}><legend>Inspection request for this location and revision</legend><label>Scope, utility-clearance references and inspection evidence<textarea name="reason" required/></label><button className="partner-button wide-touch" disabled={busy}>Request supervisor review</button></fieldset></form></details>}</article>)}
 </section>
 {data?.roles.some(r=>['safety_manager','qc_manager','executive','system_admin'].includes(r))&&<section className="partner-panel"><h2>Place work on hold</h2><p>A location notice currently holds the entire selected crew and work order. Leave crew empty to hold all crews on that work order. Changing a location label cannot clear a hold.</p><form onSubmit={e=>void submit(e,'work-safety/stops')}><fieldset disabled={busy}><legend>Shutdown scope</legend><label>Work order<select name="work_order_id" required><option value="">Select work order</option>{data.work_orders.map(w=><option key={w.id} value={w.id}>{w.work_order_number} · {w.title}</option>)}</select></label><label>Crew<select name="crew_id"><option value="">All crews on this work order</option>{data.crews.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Affected location<input name="work_location"/></label><label>Reason<textarea name="reason" required/></label><label><input type="checkbox" name="utility_strike"/> Utility strike: utility clearance is required before Safety and Operations approval</label><button className="partner-button wide-touch" disabled={busy}>Place work on hold</button></fieldset></form></section>}
 <section className="partner-panel"><h2>Authorization and shutdown history</h2>{data&&!data.controls.length&&<p>No safety controls are available in your scope.</p>}{data?.controls.map(c=>{const next=c.required_approvals.find(k=>!c.approvals.some(a=>a.approval_kind===k));const mayApprove=!c.classification_review_required&&next&&['pending','active'].includes(c.status)&&data.roles.some(r=>authorities[next]?.includes(r));return <article key={c.id} className="partner-panel"><h3>{label(c.control_type)} · {label(c.status)}</h3><p>{c.work_location} — {c.reason}</p>{c.classification_review_required&&<p>Imported shutdown: Safety must review its source and classify the restart requirements.</p>}{c.classification_review_required&&data.roles.some(r=>['safety_manager','executive'].includes(r))&&<form onSubmit={e=>void submit(e,`work-safety/controls/${c.id}/classify`)}><fieldset disabled={busy}><legend>Review imported shutdown</legend><label><input type="checkbox" name="utility_strike"/> Utility strike</label><label>Evidence supporting this classification<input name="evidence_reference" required/></label><button className="partner-button wide-touch">Record shutdown classification</button></fieldset></form>}{c.approvals.map(a=><p key={a.approval_kind}>{label(a.approval_kind)}: {a.approver_name}, {new Date(a.approved_at).toLocaleString()}</p>)}{next&&['pending','active'].includes(c.status)&&<p>Waiting for {label(next)} approval.</p>}{c.control_type==='pre_bore'&&['pending','approved'].includes(c.status)&&data.roles.some(r=>['safety_manager','operations_manager','project_manager','executive'].includes(r))&&<form onSubmit={e=>void submit(e,`work-safety/controls/${c.id}/revoke-pre-bore`)}><fieldset disabled={busy}><legend>Revoke pre-bore authorization</legend><label>Reason<input name="reason" required/></label><button className="partner-button wide-touch">Revoke authorization</button></fieldset></form>}{mayApprove&&<form onSubmit={e=>void submit(e,`work-safety/controls/${c.id}/approvals`,{approval_kind:next})}><fieldset disabled={busy}><legend>Record verified {label(next!)} approval</legend><label>Actual approving person or external representative<input name="approver_name" required/></label><label>Approval time<input type="datetime-local" step="1" name="approved_at" required/></label><label>Evidence reference<input name="evidence_reference" required/></label><label><input type="checkbox" name="verified" required/> I verified this approval and its evidence. Recording it does not imply an external party approved without proof.</label><button className="partner-button wide-touch" disabled={busy}>Record verified approval</button></fieldset></form>}</article>})}</section>
 </main>;
}
