"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {syncosFetch,SyncosApiError} from '../../intelligence/api';
import {useCapability,useVerifiedIdentity} from '../../access-control';
import {materialRequest} from '../../partner/material-drafts';
type Assignment={id:string;project:{name:string};crew:{name:string};work_order:{work_order_number:string}};
type Balance={location_id:string;lot_id:string;location_label:string;label:string;serial_number:string;unit:string;balance:string};
type Data={next:string|null;work_order_id:string;balances:Balance[];movements:{id:string;label:string;kind:string;quantity:string;unit:string}[]};
export default function FieldMaterials(){
 const allowed=useCapability('partner_production_record.create'),identity=useVerifiedIdentity();
 const [assignments,setAssignments]=useState<Assignment[]>([]),[assignment,setAssignment]=useState(''),[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<Record<string,unknown>|null>(null),[rejected,setRejected]=useState(false);
 const gate=useRef(false),dirty=useRef(false);const scope=(id:string)=>JSON.stringify([identity?.tenant_id,identity?.user_id,id]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
 useEffect(()=>{syncosFetch<Assignment[]>('syncfield/foreman/assignments').then(setAssignments).catch(e=>setError(e.message));},[]);
 async function load(id:string,before=''){if(dirty.current&&!confirm('Leave unsaved material entries?'))return;dirty.current=false;setAssignment(id);setData(null);setPending(null);setRejected(false);setError('');if(!id)return;setBusy(true);try{const result=await syncosFetch<Data>(`syncfield/foreman/materials?assignment_id=${id}${before?'&before='+encodeURIComponent(before):''}`);const saved=await materialRequest(scope(id));setData(result);setPending(saved??null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function transmit(body:Record<string,unknown>){if(gate.current||!allowed)return;gate.current=true;setBusy(true);setError('');setRejected(false);try{await syncosFetch('syncfield/foreman/materials',{method:'POST',body});await materialRequest(scope(assignment),null);setPending(null);dirty.current=false;setMessage('Material use recorded. This does not establish accepted production or billing.');await load(assignment);}catch(e){setRejected(e instanceof SyncosApiError&&e.status===400);setError((e as Error).message+' The saved request and its reference are preserved.');}finally{gate.current=false;setBusy(false);}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(gate.current||!data||!allowed||pending)return;const b=Object.fromEntries(new FormData(e.currentTarget)),row=data.balances[Number(b.material)];if(!row)return;gate.current=true;setBusy(true);const body={...b,assignment_id:assignment,lot_id:row.lot_id,from_location_id:row.location_id,work_order_id:data.work_order_id,request_key:crypto.randomUUID()};try{await materialRequest(scope(assignment),body);dirty.current=false;setPending(body);gate.current=false;await transmit(body);}catch(e){setError((e as Error).message);}finally{gate.current=false;setBusy(false);}}
 async function correctRejected(){try{await materialRequest(scope(assignment),null);setPending(null);setRejected(false);setMessage('Rejected request cleared for correction. Review the rejection before submitting revised entries.');}catch(e){setError((e as Error).message);}}
 return <main className="completion-workspace" style={{maxWidth:800,margin:'auto',padding:20}}><a href="/syncfield/today">Back to SyncField</a><h1>Crew materials</h1>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<label>Work assignment<select disabled={busy} value={assignment} onChange={e=>void load(e.target.value)}><option value="">Choose assignment</option>{assignments.map(a=><option key={a.id} value={a.id}>{a.project.name} · {a.work_order.work_order_number} · {a.crew.name}</option>)}</select></label>{pending&&<section aria-label="Saved material request"><h2>Material use awaiting confirmation</h2><p>{String(pending.kind)} · {String(pending.quantity)} · {String(pending.reference)}</p><p>Reference: {String(pending.request_key)}. Reopening this assignment restores the same request. Verify it before recording another movement.</p>{allowed&&<button disabled={busy} onClick={()=>void transmit(pending)}>Retry saved material use</button>}{allowed&&rejected&&<button disabled={busy} onClick={()=>void correctRejected()}>Correct rejected entries</button>}</section>}{data&&<><h2>Material in crew custody</h2>{data.balances.map(b=><p key={b.location_id+b.lot_id}>{b.label} · {b.serial_number} · {b.location_label}: {b.balance} {b.unit}</p>)}{allowed&&!pending&&data.balances.length>0&&<form onSubmit={submit} onChange={()=>{dirty.current=true;}}><fieldset disabled={busy}><label>Material<select name="material" required>{data.balances.map((b,i)=><option key={i} value={i}>{b.label} · {b.serial_number} · {b.location_label}</option>)}</select></label><label>Use<select name="kind"><option value="installed">Installed</option><option value="scrap">Scrap</option><option value="offcut">Offcut</option></select></label><label>Quantity<input name="quantity" type="number" min="0.0001" step="0.0001" required/></label><label>Work date<input name="work_date" type="date" required/></label><label>Source document reference<input name="reference" required maxLength={1000}/></label><label>Reason<textarea name="reason" required maxLength={1000}/></label><button>Record material use</button></fieldset></form>}<h2>Use on this work order</h2>{data.movements.map(m=><p key={m.id}>{m.label} · {m.kind} · {m.quantity} {m.unit}</p>)}{data.next&&<button disabled={busy} onClick={()=>void load(assignment,data.next!)}>Older material use</button>}<button disabled={busy} onClick={()=>void load(assignment)}>Latest material use</button></>}<p>Receipts, transfers and count adjustments require an authorized inventory operator. New material use requires current work and safety clearance. Logging out removes device-saved requests.</p></main>;
}
