"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useTenantCapability} from '../access-control';
import {syncosFetch} from '../intelligence/api';
type Connection={id:string;name:string;issuer:string;client_id:string;secret_env:string;authorization_endpoint:string;token_endpoint:string;jwks_uri:string;enabled:boolean;version:number};
type IdentityLink={id:string;user_id:string;email:string;display_name:string;subject:string;active:boolean};
export default function IdentitySettings(){const allowed=useTenantCapability('admin.manage_users'),gate=useRef(false);const [connections,setConnections]=useState<Connection[]>([]),[selected,setSelected]=useState(''),[links,setLinks]=useState<IdentityLink[]>([]),[members,setMembers]=useState<{id:string;email:string;display_name:string}[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function refresh(){const result=await syncosFetch<{connections:Connection[]}>('auth/sso/connections');setConnections(result.connections);}
 useEffect(()=>{if(allowed)void refresh().catch(e=>setError(e.message));},[allowed]);
 useEffect(()=>{setLinks([]);if(!selected)return;let alive=true;void syncosFetch<{links:IdentityLink[]}>(`auth/sso/links?connection_id=${selected}`).then(r=>{if(alive)setLinks(r.links);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[selected,connections]);
 async function action(fn:()=>Promise<void>){if(gate.current)return;gate.current=true;setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Could not save settings.');}finally{gate.current=false;setBusy(false);}}
 function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);void action(async()=>{const body=Object.fromEntries(form.entries());const result=await syncosFetch<{id:string}>('auth/sso/connections',{method:'POST',body:{...body,...(selected?{id:selected}:{}),enabled:form.get('enabled')==='on'}});await refresh();setSelected(result.id);setMessage('Connection saved. Existing SSO sessions for this connection must sign in again.');});}
 function search(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);void action(async()=>{const result=await syncosFetch<{members:typeof members}>(`auth/sso/members?search=${encodeURIComponent(String(form.get('search')??''))}`);setMembers(result.members);setMessage(result.members.length===50?'Showing 50 matches. Narrow the search if needed.':`${result.members.length} active members found.`);});}
 function link(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);void action(async()=>{await syncosFetch('auth/sso/links',{method:'POST',body:{connection_id:selected,user_id:form.get('user_id'),subject:form.get('subject'),active:true}});await refresh();setMessage('Identity linked. This member must sign in again; their existing roles are unchanged.');});}
 if(!allowed)return null;const current=connections.find(c=>c.id===selected);
 return <main className="operator-page"><h1>Organization sign-in settings</h1><p>Configure an approved OpenID Connect provider and explicitly link existing workspace members. Server credentials and approved provider hosts are managed by the server operator. Enter a credential reference here, never a secret.</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<label>Connection<select value={selected} disabled={busy} onChange={e=>setSelected(e.target.value)}><option value="">Create a connection</option>{connections.map(c=><option key={c.id} value={c.id}>{c.name} ({c.enabled?'enabled':'disabled'})</option>)}</select></label>
 <form key={selected+':'+(current?.version??0)} onSubmit={save}><fieldset disabled={busy}><legend>Provider configuration</legend>{([['name','Display name'],['issuer','Exact provider issuer'],['client_id','Client ID'],['secret_env','Server credential reference (SSO_CLIENT_SECRET_…)'],['authorization_endpoint','Authorization endpoint'],['token_endpoint','Token endpoint'],['jwks_uri','Signing keys endpoint']] as const).map(([key,label])=><label className="form-field" key={key}>{label}<input name={key} required maxLength={2048} defaultValue={current?.[key]??''} readOnly={key==='issuer'&&!!current}/></label>)}<label><input name="enabled" type="checkbox" defaultChecked={current?.enabled??false}/> Enable this approved connection</label><p>Changing the issuer requires a new connection and new identity links. Global SSO activation also requires server configuration.</p><button type="submit" style={{minHeight:44}}>Save connection</button></fieldset></form>
 {selected&&<><h2>Link an existing member</h2><form onSubmit={search}><label className="form-field">Find a member by name or email<input name="search" maxLength={100}/></label><button disabled={busy} style={{minHeight:44}}>Search members</button></form><form onSubmit={link}><fieldset disabled={busy}><label className="form-field">Member<select name="user_id" required defaultValue=""><option value="">Choose an active member</option>{members.map(m=><option key={m.id} value={m.id}>{m.display_name} · {m.email}</option>)}</select></label><label className="form-field">Verified provider subject<input name="subject" required maxLength={512}/></label><p>Use the provider’s verified subject identifier. Email matching alone does not link an account.</p><button style={{minHeight:44}}>Link identity</button></fieldset></form><h2>Linked identities</h2>{links.length?<ul>{links.map(l=><li key={l.id}>{l.display_name} · {l.email} · {l.active?'Active':'Revoked'} <button disabled={busy} style={{minHeight:44}} onClick={()=>void action(async()=>{await syncosFetch('auth/sso/links',{method:'POST',body:{connection_id:selected,user_id:l.user_id,subject:l.subject,active:!l.active}});await refresh();setMessage('Identity access updated and existing sessions revoked.');})}>{l.active?'Revoke access':'Restore approved link'}</button></li>)}</ul>:<p>No identities linked to this connection.</p>}</>}
 </main>;
}
