"use client";
import {useEffect,useState} from 'react';
import {Capability} from '../access-control';
import {syncosFetch} from '../intelligence/api';
type Intake={connections:Array<{_history_cursor?:string;id:string;customer_reference:string;account_reference:string}>,mappings:Array<{_history_cursor?:string;id:string;transaction_reference:string;amount:string}>,exceptions:Array<{_history_cursor?:string;id:string;transaction_reference:string;reason:string;status:string}>,jobs:Array<{_history_cursor?:string;id:string;transaction_reference:string;status:string;attempts:number}>,payables?:Array<{_history_cursor?:string;id:string;payable_number:string;net_payable_amount:string}>};
export function PassportIntake(){
 const [search,setSearch]=useState('');
 const [data,setData]=useState<Intake>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;syncosFetch<Intake>('passport-intake').then(d=>{if(active){setData(d);setError('');}}).catch(()=>{if(active)setError('Preparation records could not be loaded.');});return()=>{active=false;};},[revision]);
 async function history(kind:'payables'|'mappings'|'exceptions'|'jobs',before?:string){if(busy)return;setBusy(true);try{const params=new URLSearchParams({[kind+'_q']:kind==='payables'?search:'',...(before?{[kind+'_before']:before}:{})});const found=await syncosFetch<Intake>('passport-intake?'+params);setData(old=>old?{...old,[kind]:found[kind]}:found);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function older(kind:'payables'|'mappings'|'exceptions'|'jobs'){const rows=data?.[kind];return rows?.length===100&&rows.at(-1)?._history_cursor?<button type="button" disabled={busy} onClick={()=>void history(kind,rows.at(-1)!._history_cursor)}>Older {kind}</button>:null;}
 async function submit(e:React.FormEvent<HTMLFormElement>,path:string){e.preventDefault();if(busy)return;const form=e.currentTarget,body:Record<string,unknown>=Object.fromEntries(new FormData(form));if(path.endsWith('/mappings')){body.account_and_payee_verified=body.account_and_payee_verified==='on';delete body.connection_id;}setBusy(true);setError('');try{await syncosFetch(path,{method:'POST',body});form.reset();setRevision(x=>x+1);}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 return <Capability permission="partner_payment.confirm"><section className="workspace-panel"><h2>Saved integration preparation</h2><p>These are saved setup and review records. Provider access and automatic recording are disabled. Enter reference identifiers only; never paste passwords or API keys.</p>
 {error&&<p role="alert">{error} <button onClick={()=>setRevision(x=>x+1)}>Reload preparation</button></p>}
 {!data&&!error&&<p role="status">Loading preparation…</p>}
 <Capability permission="admin.manage_users"><form onSubmit={e=>void submit(e,'passport-intake/connections')}><fieldset disabled={busy}><legend>Prepare a sandbox account</legend><label>Customer reference<input required name="customer_reference" pattern="[-A-Za-z0-9_.:]+" maxLength={160}/></label><label>Account reference<input required name="account_reference" pattern="[-A-Za-z0-9_.:]+" maxLength={160}/></label><button type="submit">Save account references</button></fieldset></form></Capability>
 {data&&<><h3>Prepared accounts</h3>{data.connections.length?<ul>{data.connections.map(c=><li key={c.id}>{c.customer_reference} / {c.account_reference} — disabled</li>)}</ul>:<p>No account references saved.</p>}
 <h3>Approved transaction mappings</h3>{older("mappings")}{data.mappings.length?<ul>{data.mappings.map(m=><li key={m.id}>{m.transaction_reference}: ${m.amount}</li>)}</ul>:<p>No approved mappings. Account and payee verification is required before approving one.</p>}
 {data.connections.length>0&&<form onSubmit={e=>{const connection=new FormData(e.currentTarget).get('connection_id');void submit(e,`passport-intake/connections/${connection}/mappings`);}}><fieldset disabled={busy}><legend>Approve a transaction mapping</legend><p>Match a verified provider transaction to an accepted partner payable. Approval saves evidence only; it does not record or send a payment.</p><label>Prepared account<select required name="connection_id"><option value="">Choose account</option>{data.connections.map(c=><option key={c.id} value={c.id}>{c.customer_reference} / {c.account_reference}</option>)}</select></label><label>Find partner payable<input value={search} maxLength={200} onChange={e=>setSearch(e.target.value)}/></label><button type="button" disabled={busy} onClick={()=>void history("payables")}>Find payable</button>{older("payables")}<label>Partner payable<select required name="contractor_payable_id"><option value="">Choose payable</option>{(data.payables??[]).map(p=><option key={p.id} value={p.id}>{p.payable_number} — ${p.net_payable_amount}</option>)}</select></label>{!data.payables?.length&&<p>No partner payables with approved terms are available. Complete accepted-work finance first.</p>}<label>Transaction reference<input required name="transaction_reference" pattern="[-A-Za-z0-9_.:]+" maxLength={160}/></label><label>Payee reference<input required name="payee_reference" pattern="[-A-Za-z0-9_.:]+" maxLength={160}/></label><label>Transaction amount (USD)<input required name="amount" inputMode="decimal" pattern="([1-9][0-9]*|0)\.[0-9]{2}" placeholder="0.00"/></label><input type="hidden" name="currency" value="USD"/><label>Verification evidence<textarea required name="evidence_reference" minLength={3} maxLength={2000}/></label><label><input type="checkbox" required name="account_and_payee_verified"/>I verified the account, payee, transaction and payable against the evidence.</label><button type="submit" disabled={!data.payables?.length}>Approve mapping</button></fieldset></form>}
 <h3>Review exceptions</h3>{older("exceptions")}{data.exceptions.length?data.exceptions.map(row=><article key={row.id}><p>{row.transaction_reference}: {row.reason.replaceAll('_',' ')} — {row.status}</p>{row.status==='open'&&<form onSubmit={e=>void submit(e,`passport-intake/exceptions/${row.id}/review`)}><label>Review findings<textarea required name="review_note" minLength={3} maxLength={2000}/></label><button disabled={busy}>Record review</button><p>This records your findings. It does not post, reverse or authorize a payment.</p></form>}</article>):<p>No saved exceptions.</p>}
 <h3>Refresh jobs</h3>{older("jobs")}{data.jobs.length?<ul>{data.jobs.map(j=><li key={j.id}>{j.transaction_reference}: {j.status}, {j.attempts} attempts</li>)}</ul>:<p>No refresh jobs. Provider scheduling remains disabled.</p>}</>}
 </section></Capability>;
}
