"use client";
import {useRef,useState,useEffect,type FormEvent} from 'react';
import {syncosFetch} from './api';
import {useCapability,PermissionLink} from '../access-control';
export function CreateRecordConstraint({objectType,objectId,title=''}:{objectType:string;objectId:string;title?:string}) {
 const allowed=useCapability('constraint.create');const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);const key=useRef(''),gate=useRef(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(gate.current)return;gate.current=true;setBusy(true);setError('');const f=Object.fromEntries(new FormData(e.currentTarget));if(!key.current)key.current=crypto.randomUUID();try{await syncosFetch('constraints',{method:'POST',body:{...f,affected_object_type:objectType,affected_object_id:objectId,client_mutation_id:key.current,hard_stop:f.hard_stop==='on',override_allowed:f.hard_stop!=='on'}});setSaved(true);setOpen(false);}catch(e){setError((e as Error).message+' Your entries are preserved.');}finally{gate.current=false;setBusy(false);}}
 if(!allowed)return null;
 return <div>{saved?<p role="status">Constraint created for this record. <PermissionLink href="/constraints-center">Open Constraints Center</PermissionLink></p>:<button type="button" onClick={()=>setOpen(!open)} style={{minHeight:44}}>Create Constraint</button>}{open&&<form onSubmit={submit} onChange={()=>{if(!busy)key.current='';}}><fieldset disabled={busy} style={{border:0,minWidth:0}}><legend>New constraint for this record</legend><label>Constraint title<input name="title" defaultValue={title} required maxLength={240}/></label><label>Constraint category<select name="constraint_type" required defaultValue=""><option value="">Choose a category</option>{['information','relationship','capacity','compliance','execution','qc','safety','billing','cash','decision','data_trust'].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label><label>Severity<select name="severity" required defaultValue=""><option value="">Choose severity</option>{['low','medium','high','critical'].map(v=><option key={v}>{v}</option>)}</select></label><label>Details<textarea name="description" required maxLength={4000}/></label><label><input name="hard_stop" type="checkbox"/> Block approval until resolved</label><p>A constraint records a blocker. Use the safety shutdown workflow when work must stop in the field.</p><button type="submit">{busy?'Saving…':'Save constraint'}</button><button type="button" onClick={()=>setOpen(false)}>Cancel</button></fieldset>{error&&<p role="alert">{error}</p>}</form>}</div>;
}
export function AddContactToRelationship({contactId}:{contactId:string}) {
 const canCreate=useCapability('relationship_path.create'),canRead=useCapability('relationship_map.read');
 const [open,setOpen]=useState(false),[maps,setMaps]=useState<Array<{id:string;name:string;target_contact_id?:string}>>([]),[contacts,setContacts]=useState<Array<{id:string;first_name?:string;last_name?:string;full_name?:string}>>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');const key=useRef(''),gate=useRef(false);
 useEffect(()=>{if(!open||!canCreate||!canRead)return;let active=true;setBusy(true);Promise.all([syncosFetch<typeof maps>('relationship-maps'),syncosFetch<typeof contacts>('contacts')]).then(([m,c])=>{if(active){setMaps(m);setContacts(c);setError('');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[open,canCreate,canRead]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(gate.current)return;gate.current=true;setBusy(true);setError('');const f=Object.fromEntries(new FormData(e.currentTarget));if(!key.current)key.current=crypto.randomUUID();try{await syncosFetch(`relationship-maps/${f.map_id}/paths`,{method:'POST',body:{from_contact_id:contactId,to_contact_id:f.to_contact_id,path_name:f.path_name,path_summary:f.path_summary,status:'proposed',client_mutation_id:key.current}});setSaved(String(f.map_id));setOpen(false);}catch(e){setError((e as Error).message+' Your entries are preserved.');}finally{gate.current=false;setBusy(false);}}
 if(!canCreate||!canRead)return null;
 return <div><button type="button" style={{minHeight:44}} onClick={()=>setOpen(!open)}>Add to Relationship Map</button>{saved&&<p role="status">Proposed relationship added. <PermissionLink href={`/intelligence/relationship-maps/${saved}`}>Open relationship map</PermissionLink></p>}{open&&<form onSubmit={submit} onChange={()=>{if(!busy)key.current='';}}><fieldset disabled={busy} style={{border:0,minWidth:0}}><legend>Propose a contact relationship</legend><label>Relationship map<select name="map_id" required defaultValue=""><option value="">Choose a map</option>{maps.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Connect this contact to<select name="to_contact_id" required defaultValue=""><option value="">Choose another contact</option>{contacts.filter(c=>c.id!==contactId).map(c=><option key={c.id} value={c.id}>{c.full_name??[c.first_name,c.last_name].filter(Boolean).join(' ')}</option>)}</select></label><label>Relationship name<input name="path_name" required maxLength={240}/></label><label>Relationship evidence and context<textarea name="path_summary" required maxLength={4000}/></label><p>The relationship is saved as proposed for review.</p><button type="submit">{busy?'Saving…':'Save proposed relationship'}</button><button type="button" onClick={()=>setOpen(false)}>Cancel</button></fieldset>{error&&<p role="alert">{error}</p>}</form>}</div>;
}
