import {test,expect,type Page} from '@playwright/test';
async function session(page:Page,write=false){
 const permissions=['partner_context.read','partner_daily_production.read_org',...(write?['partner_form.delegate','partner_inventory.report']:[])];
 await page.addInitScript(()=>localStorage.setItem('syncos.apiToken','synthetic-token'));
 await page.route('**/api/syncos/auth/me',r=>r.fulfill({json:{user_id:'synthetic',tenant_id:'synthetic',roles:['partner_admin'],permissions,routing:{workspace:'/partner'}}}));
 await page.route('**/api/syncos/partner/context',r=>r.fulfill({json:{}}));
 await page.route('**/api/syncos/syncfield/partner/field-overview?*',r=>{
 const selected=new URL(r.request().url()).searchParams.get('assignment_id');return r.fulfill({json:{assignments:[{id:'assignment-a',current:true,assignment_status:'active',project_name:'Synthetic project',work_order_number:'WO-A',crew_name:'Crew A'},{id:'assignment-b',current:true,assignment_status:'active',project_name:'Synthetic project',work_order_number:'WO-B',crew_name:'Crew B'}],assignment:selected?{id:selected,current:true}:null,forms:[{id:'form-v1',schema:{name:'Field condition'},version:1,active:true,submission_count:0}],records:[],balances:[{lot_id:'lot',location_id:'custody',label:'Cable',serial_number:'REEL-1',location_label:'Crew A',unit:'ft',balance:'100'}],movements:[],discrepancies:[]}});
 });
 await page.goto('/partner/field-oversight');await page.getByRole('combobox',{name:'Work assignment',exact:true}).selectOption('assignment-a');await expect(page.getByRole('heading',{name:'Assigned forms and response coverage'})).toBeVisible();
}
test('company reader sees coverage and custody without unauthorized actions',async({page})=>{
 await session(page);await expect(page.getByText(/awaiting a response/)).toBeVisible();await expect(page.getByRole('button',{name:'Request material review'})).toHaveCount(0);await expect(page.getByRole('combobox',{name:'Destination assignment for delegation'})).toHaveCount(0);await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
test('authorized company admin delegates exact version and reports a stock discrepancy without adjusting stock',async({page})=>{
 const writes:any[]=[];await page.route('**/api/syncos/syncfield/partner/delegate-form',async r=>{writes.push(r.request().postDataJSON());await r.fulfill({json:{id:'assigned'}});});await page.route('**/api/syncos/syncfield/partner/material-discrepancies',async r=>{writes.push(r.request().postDataJSON());await r.fulfill({json:{id:'review'}});});
 await session(page,true);await page.getByRole('combobox',{name:'Destination assignment for delegation'}).selectOption('assignment-b');await page.getByRole('button',{name:'Assign this form to selected crew assignment'}).click();await expect(page.getByText(/Form assigned. Each crew/)).toBeVisible();expect(writes[0]).toEqual({source_assignment_id:'assignment-a',assignment_id:'assignment-b',version_id:'form-v1'});
 await page.getByRole('combobox',{name:'Material and crew custody'}).selectOption('lot|custody');await page.getByLabel('Physical count').fill('95');await page.getByLabel('Count-sheet or evidence reference').fill('COUNT-TEST');await page.getByLabel('What differs from the recorded stock?').fill('Five feet missing from physical count');await page.getByRole('button',{name:'Request material review'}).click();await expect(page.getByText(/Stock has not been adjusted/)).toBeVisible();expect(writes[1]).toMatchObject({assignment_id:'assignment-a',lot_id:'lot',location_id:'custody',reported_count:'95'});expect(writes[1].request_key).toMatch(/^[a-f\d-]{36}$/);
});
test('failed stock report retains count and stable request key for retry',async({page})=>{
 const bodies:any[]=[];await page.route('**/api/syncos/syncfield/partner/material-discrepancies',async r=>{bodies.push(r.request().postDataJSON());await r.fulfill({status:503,json:{message:'Review queue unavailable'}});});await session(page,true);await page.getByRole('combobox',{name:'Material and crew custody'}).selectOption('lot|custody');await page.getByLabel('Physical count').fill('95');await page.getByLabel('Count-sheet or evidence reference').fill('COUNT-TEST');await page.getByLabel('What differs from the recorded stock?').fill('Five feet missing');await page.getByRole('button',{name:'Request material review'}).click();await expect(page.getByText(/Your entries are preserved/)).toBeVisible();await expect(page.getByLabel('Physical count')).toHaveValue('95');await page.getByRole('button',{name:'Request material review'}).click();await expect.poll(()=>bodies.length).toBe(2);expect(bodies[0]).toEqual(bodies[1]);
});
