const test=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto'),{Pool}=require('pg');
const {SearchController}=require('../apps/api/dist/routes/search.controller');
const url=process.env.SYNCOS_COMMERCIAL_TEST_DATABASE_URL;
test('global search pages without truncation and enforces record permissions before returning results',{skip:!url},async()=>{const pool=new Pool({connectionString:url});try{
 const tag=randomUUID(),tenant=(await pool.query("INSERT INTO tenants(name,slug) VALUES('Synthetic search',$1) RETURNING id",['search-'+tag])).rows[0].id,other=(await pool.query("INSERT INTO tenants(name,slug) VALUES('Other search',$1) RETURNING id",['search-other-'+tag])).rows[0].id,user=(await pool.query("INSERT INTO users(email,display_name) VALUES($1,'Search reader') RETURNING id",[tag+'@synthetic.test'])).rows[0].id,member=(await pool.query('INSERT INTO tenant_users(tenant_id,user_id) VALUES($1,$2) RETURNING id',[tenant,user])).rows[0].id,role=(await pool.query("INSERT INTO roles(tenant_id,name) VALUES($1,'Search reader') RETURNING id",[tenant])).rows[0].id;
 await pool.query("INSERT INTO user_roles(tenant_id,tenant_user_id,role_id,scope_type,scope_id) VALUES($1,$2,$3,'tenant',$1)",[tenant,member,role]);await pool.query("INSERT INTO role_permissions(tenant_id,role_id,permission_id) SELECT $1,$2,id FROM permissions WHERE key IN ('project.read','search.read')",[tenant,role]);
 await pool.query("INSERT INTO projects(tenant_id,name) SELECT $1,'Searchable project '||n FROM generate_series(1,121)n",[tenant]);await pool.query("INSERT INTO projects(tenant_id,name) VALUES($1,'Searchable foreign project')",[other]);await pool.query("INSERT INTO organizations(tenant_id,name,type) VALUES($1,'Searchable secret customer','customer')",[tenant]);await pool.query("INSERT INTO projects(tenant_id,name) VALUES($1,'Literal 100% project')",[tenant]);
 const c=new SearchController(pool),req={auth:{tenantId:tenant,userId:user}},seen=new Set();let after;do{const rows=await c.search(req,'Searchable',undefined,after);assert.ok(rows.length<=50);for(const row of rows){assert.equal(row.object_type,'project');assert.equal(seen.has(row.id),false);assert.doesNotMatch(row.title,/foreign|secret/);seen.add(row.id);}after=rows.length===50?rows.at(-1)._cursor:null;}while(after);assert.equal(seen.size,121);assert.equal((await c.search(req,'%')).length,1);await assert.rejects(c.search(req,'Searchable',undefined,'invalid'),/Invalid search position/);await assert.rejects(c.search(req,'a'.repeat(201)),/200 characters/);
 await pool.query("DELETE FROM role_permissions WHERE tenant_id=$1 AND role_id=$2 AND permission_id=(SELECT id FROM permissions WHERE key='project.read')",[tenant,role]);assert.deepEqual(await c.search(req,'Searchable'),[]);
 await pool.query("INSERT INTO role_permissions(tenant_id,role_id,permission_id) SELECT $1,$2,id FROM permissions WHERE key='project.read'",[tenant,role]);await pool.query("UPDATE user_roles SET scope_type='organization',scope_id=$2 WHERE tenant_id=$1",[tenant,randomUUID()]);assert.deepEqual(await c.search(req,'Searchable'),[]);
 }finally{await pool.end();}});
