import {test,expect,type Page} from '@playwright/test';
import {createHash} from 'node:crypto';
const pdf=Buffer.from('%PDF-1.4\n%%EOF'), checksum=createHash('sha256').update(pdf).digest('hex');
async function setup(page:Page){
 await page.goto('/syncfield/offline.html');
 await page.evaluate(async()=>{const token='synthetic.'+btoa(JSON.stringify({sub:'user',tenant_id:'tenant'}))+'.test';localStorage.setItem('syncos.apiToken',token);const fingerprint=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token))),b=>b.toString(16).padStart(2,'0')).join('');const now=Date.now();localStorage.setItem('syncos.offlineContext',JSON.stringify({fingerprint,tenant:'tenant',user:'user',savedAt:now,expires:now+3600000,assignments:[{id:'assignment',project:'Synthetic project',crew:'Sync crew',workOrder:'WO-test'}]}));});
 await page.route('**/api/syncos/auth/me',r=>r.fulfill({json:{user_id:'user',tenant_id:'tenant',permissions:['partner_daily_production.create']}}));
 await page.route('**/api/syncos/syncfield/foreman/map-assignment?*',r=>r.fulfill({json:{id:'assignment',map:{version_id:'map-v1'}}}));
 await page.route('**/api/syncos/syncfield/foreman/production/codes?*',r=>r.fulfill({json:[]}));
 await page.route('**/api/syncos/syncfield/foreman/map-versions/map-v1/bytes?*',r=>r.fulfill({json:{mime_type:'application/pdf',size_bytes:pdf.length,checksum,content_base64:pdf.toString('base64')}}));
 await page.reload();await page.getByRole('button',{name:'Prepare or refresh assignment'}).click();await expect(page.getByRole('link',{name:/Open cached PDF/})).toBeVisible();
}
async function save(page:Page){await page.getByText('Create a new report on this device',{exact:true}).click();await page.getByLabel('Work date',{exact:true}).fill('2026-10-05');await page.getByLabel('Daily report notes').fill('Original site notes');await page.getByRole('button',{name:'Save report on this device'}).click();await expect(page.getByText('Local draft — not sent')).toBeVisible();}
test('cold navigation restores map and new report, exact retry after ambiguous response',async({page,context})=>{
 await setup(page);await page.evaluate(async()=>{await navigator.serviceWorker.register('/syncfield/offline-worker.js',{scope:'/syncfield/'});await navigator.serviceWorker.ready;});await page.reload();await context.setOffline(true);await page.goto('/syncfield/production');await expect(page.getByRole('link',{name:/Open cached PDF/})).toBeVisible();await save(page);await page.reload();await expect(page.getByText('Local draft — not sent')).toBeVisible();await context.setOffline(false);
 const bodies:any[]=[];await page.route('**/api/syncos/syncfield/foreman/production/today',async r=>{bodies.push(r.request().postDataJSON());if(bodies.length===1)await r.abort();else await r.fulfill({json:{id:'server-report'}});});
 await page.getByRole('button',{name:'Send or reconcile saved report'}).click();await expect(page.getByText('Awaiting reconciliation — original request preserved')).toBeVisible();await expect(page.getByText('Edit local report 2026-10-05')).toHaveCount(0);await page.goto('/syncfield/offline.html');await page.getByRole('button',{name:'Send or reconcile saved report'}).click();await expect(page.getByText('Server draft confirmed',{exact:true})).toBeVisible();expect(bodies).toHaveLength(2);expect(bodies[0]).toEqual(bodies[1]);expect(bodies[0].general_notes).toBe('Original site notes');
});
test('shutdown rejection preserves report; another account cannot see it',async({page})=>{await setup(page);await save(page);await page.route('**/api/syncos/syncfield/foreman/production/today',r=>r.fulfill({status:403,json:{message:'Work stopped pending approval'}}));await page.getByRole('button',{name:'Send or reconcile saved report'}).click();await expect(page.getByText('Awaiting reconciliation — original request preserved')).toBeVisible();await page.evaluate(()=>localStorage.setItem('syncos.apiToken','different-account'));await page.reload();await expect(page.getByText(/Reconnect to verify this account/)).toBeVisible();await expect(page.getByText('Saved report 2026-10-05')).toHaveCount(0);});
test('corrupt map cannot replace a verified download and expired context is denied',async({page})=>{await setup(page);await page.route('**/api/syncos/syncfield/foreman/map-versions/map-v1/bytes?*',r=>r.fulfill({json:{mime_type:'application/pdf',size_bytes:pdf.length,checksum:'bad',content_base64:pdf.toString('base64')}}));await page.getByRole('button',{name:'Prepare or refresh assignment'}).click();await expect(page.getByText(/Map download did not pass/)).toBeVisible();await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('syncos.offlineContext')!);s.expires=Date.now()-1;localStorage.setItem('syncos.offlineContext',JSON.stringify(s));});await page.reload();await expect(page.getByText(/Reconnect and sign in to view assignments/)).toBeVisible();await expect(page.getByRole('link',{name:/Open cached PDF/})).toHaveCount(0);});

test('an interrupted replacement map removes the outdated link and can be prepared again',async({page})=>{await setup(page);await page.route('**/api/syncos/syncfield/foreman/map-assignment?*',r=>r.fulfill({json:{id:'assignment',map:{version_id:'map-v2'}}}));await page.route('**/api/syncos/syncfield/foreman/map-versions/map-v2/bytes?*',r=>r.abort());await page.getByRole('button',{name:'Prepare or refresh assignment'}).click();await expect(page.getByText('Map unavailable offline. Retry preparation while connected.')).toBeVisible();await expect(page.getByRole('link',{name:/Open cached PDF/})).toHaveCount(0);await page.reload();await expect(page.getByText('Map unavailable offline. Retry preparation while connected.')).toBeVisible();await page.route('**/api/syncos/syncfield/foreman/map-versions/map-v2/bytes?*',r=>r.fulfill({json:{mime_type:'application/pdf',size_bytes:pdf.length,checksum,content_base64:pdf.toString('base64')}}));await page.getByRole('button',{name:'Prepare or refresh assignment'}).click();await expect(page.getByRole('link',{name:'Open cached PDF · version map-v2'})).toBeVisible();});
