"use client";
import {useEffect,useState,useRef,type FormEvent} from 'react';
import Link from 'next/link';
import {syncosFetch,clearAuthContext,saveToken} from '../intelligence/api';
export default function ResetPassword(){const [token,setToken]=useState(''),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');const gate=useRef(false);
 useEffect(()=>{setToken(new URLSearchParams(window.location.hash.slice(1)).get('token')??'');setLoaded(true);window.history.replaceState(null,'',window.location.pathname);},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(gate.current)return;const f=new FormData(e.currentTarget);if(f.get('password')!==f.get('confirmation')){setError('Passwords must match.');return;}gate.current=true;setBusy(true);setError('');try{const r=await syncosFetch<{message:string}>('auth/password-recovery/complete',{method:'POST',token:'',body:{token,password:f.get('password')}});saveToken('');clearAuthContext();setMessage(r.message);setToken('');}catch(e){setError((e as Error).message);}finally{gate.current=false;setBusy(false);}}
 return <main className="login-shell"><section className="login-panel"><h1>Choose a new password</h1>{!loaded?<p role="status">Checking recovery link…</p>:message?<p role="status">{message}</p>:token?<form onSubmit={submit}><fieldset disabled={busy} style={{border:0,minWidth:0}}><p>Use 12–128 characters. Updating your password signs out existing sessions on every device.</p><label className="form-field">New password<input name="password" type="password" autoComplete="new-password" required minLength={12} maxLength={128}/></label><label className="form-field">Confirm new password<input name="confirmation" type="password" autoComplete="new-password" required minLength={12} maxLength={128}/></label><button type="submit" style={{minHeight:44}}>{busy?'Updating…':'Update password'}</button></fieldset></form>:<p>Open the link from your recovery email, or <Link href="/forgot-password">request a new link</Link>.</p>}{error&&<p role="alert">{error} <Link href="/forgot-password">Request another recovery link</Link></p>}<p><Link href="/login">Return to sign in</Link></p></section></main>;
}
