"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useParams} from 'next/navigation';
export default function ServiceRequest(){
 const {slug}=useParams<{slug:string}>();const [channel,setChannel]=useState<{label:string;privacy_notice:string}|null>(null),[error,setError]=useState(''),[receipt,setReceipt]=useState(''),[busy,setBusy]=useState(false);const key=useRef(''),gate=useRef(false),alert=useRef<HTMLParagraphElement>(null);
 useEffect(()=>{let alive=true;setChannel(null);fetch(`/api/syncos/public/customer-intake/${encodeURIComponent(slug)}`,{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('This request channel is unavailable. Contact your Sync representative.');return r.json();}).then(v=>{if(alive)setChannel(v);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[slug]);
 useEffect(()=>{if(error)alert.current?.focus();},[error]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(gate.current)return;gate.current=true;setBusy(true);setError('');const values=Object.fromEntries(new FormData(e.currentTarget));if(!key.current)key.current=crypto.randomUUID();try{const r=await fetch(`/api/syncos/public/customer-intake/${encodeURIComponent(slug)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...values,consent:values.consent==='on',request_key:key.current})});const result=await r.json();if(!r.ok)throw Error(typeof result.message==='string'?result.message:'Request could not be recorded. Your entries are preserved.');setReceipt(result.reference);}catch(e){setError((e as Error).message+' Retry with the same entries if the connection was interrupted.');}finally{gate.current=false;setBusy(false);}}
 return <main className="completion-workspace" style={{maxWidth:720,margin:'auto',padding:24}}><h1>{channel?.label??'Request service'}</h1><p>Send a request for review. Submission does not authorize work, reserve a crew, or establish commercial terms.</p>{error&&<p ref={alert} tabIndex={-1} role="alert">{error}</p>}{receipt?<section role="status"><h2>Request received</h2><p>Keep your receipt reference: <strong>{receipt}</strong></p><p>Your assigned team will review the request. No confirmation email has been sent.</p></section>:channel?<form onSubmit={submit} onChange={()=>{key.current='';}}><fieldset disabled={busy}><label>Your name<input name="customer_name" required maxLength={200} autoComplete="name"/></label><label>Contact email<input name="email" type="email" required maxLength={254} autoComplete="email"/></label><label>Subject<input name="subject" required maxLength={240}/></label><label>Request details<textarea name="details" required maxLength={10000}/></label><div aria-hidden="true" style={{position:'absolute',left:-10000}}><label>Leave blank<input name="website" tabIndex={-1} autoComplete="off"/></label></div><p style={{whiteSpace:'pre-wrap'}}>{channel.privacy_notice}</p><label><input type="checkbox" name="consent" required/> I authorize processing this request and contacting me about it.</label><p>Do not include passwords, payment-card details, or other sensitive account information.</p><button style={{minHeight:44}}>{busy?'Sending…':'Submit request'}</button></fieldset></form>:!error?<p role="status">Loading request form…</p>:null}</main>;
}
