import {test,expect,type Page} from '@playwright/test';
async function identity(page:Page,permissions:string[]){await page.addInitScript(()=>localStorage.setItem('syncos.apiToken','synthetic-browser-test'));await page.route('**/api/syncos/auth/me',r=>r.fulfill({json:{user_id:'synthetic',tenant_id:'synthetic',roles:['system_admin'],role_names:['System Admin'],permissions,tenant_permissions:permissions}}));}
const inventory={lots:[],locations:[],crews:[],work_orders:[],balances:[],movements:[]};
const inquiries={inquiries:[],owners:[],opportunities:[],projects:[]};
test('read-only roles see records without form, stock or inquiry mutation controls',async({page})=>{
 await identity(page,['form.read','inventory.read','customer_inquiry.read']);
 await page.route('**/api/syncos/supplemental-forms**',r=>r.fulfill({json:[]}));await page.route('**/api/syncos/material-inventory',r=>r.fulfill({json:inventory}));await page.route('**/api/syncos/customer-inquiries',r=>r.fulfill({json:inquiries}));
 for(const path of ['/forms','/material-inventory','/customer-inquiries']){await page.goto(path);await expect(page.locator('h1')).toBeVisible();await expect(page.locator('form')).toHaveCount(0);}
});
test('form designer publishes a revision and records a rendered answer',async({page})=>{
 await identity(page,['form.read','form.manage','form.submit']);let versions:any[]=[],records:any[]=[];
 await page.route('**/api/syncos/supplemental-forms**',async route=>{const req=route.request(),path=new URL(req.url()).pathname;
 if(req.method()==='GET')return route.fulfill({json:path.endsWith('/assignments')?[]:path.endsWith('/records')?records:versions});
 const b=req.postDataJSON();if(path.endsWith('/versions')){versions=[{id:'v1',family_id:'f1',version:1,status:'draft',schema:b.schema}];return route.fulfill({json:versions[0]});}
 if(path.endsWith('/publish')){versions[0].status='published';return route.fulfill({json:versions[0]});}
 records=[{id:'r1',version_id:'v1',schema_snapshot:versions[0].schema,answers:b.answers,created_at:new Date().toISOString()}];return route.fulfill({json:records[0]});});
 await page.goto('/forms');await page.getByLabel('Form name',{exact:true}).fill('Site observations');await page.getByRole('button',{name:'Add field',exact:true}).click();await page.getByLabel('Label',{exact:true}).fill('Notes');await page.getByLabel('Required answer').check();await page.getByRole('button',{name:'Save draft version',exact:true}).click();await expect(page.getByText('Draft version saved. Review it before publication.')).toBeVisible();
 await page.getByLabel('I reviewed and approve these fields as supplemental information.').check();await page.getByRole('button',{name:'Publish version 1'}).click();await page.getByRole('combobox',{name:'Form version',exact:true}).selectOption('v1');await page.getByLabel('Notes (required)').fill('Synthetic observation');await page.getByRole('button',{name:'Submit form',exact:true}).click();await expect(page.getByText('Form submitted. Its approved version and answers are preserved.')).toBeVisible();expect(records[0].answers).toEqual({[versions[0].schema.fields[0].key]:'Synthetic observation'});
});
test('inquiry failure preserves entries and retries the same request',async({page})=>{
 await identity(page,['customer_inquiry.read','customer_inquiry.manage']);let writes:any[]=[];
 await page.route('**/api/syncos/customer-inquiries',r=>{if(r.request().method()==='GET')return r.fulfill({json:inquiries});writes.push(r.request().postDataJSON());return r.fulfill({status:writes.length===1?503:201,json:writes.length===1?{message:'Try again'}:{id:'i1'}});});
 await page.goto('/customer-inquiries');await page.getByLabel('Customer name').fill('Synthetic customer');await page.getByLabel('Contact email').fill('customer@synthetic.test');await page.getByLabel('Subject',{exact:true}).fill('Service inquiry');await page.getByLabel('Request details').fill('Synthetic work');await page.getByLabel('Source and permission to process').fill('Customer request');await page.getByLabel('This request is authorized for processing by Sync.').check();await page.getByRole('button',{name:'Record inquiry',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Your entries are preserved'})).toBeVisible();await expect(page.getByLabel('Subject',{exact:true})).toHaveValue('Service inquiry');await page.getByRole('button',{name:'Record inquiry',exact:true}).click();await expect(page.getByText('Inquiry recorded. Assign an owner and review possible duplicates.')).toBeVisible();expect(writes[0].request_key).toBe(writes[1].request_key);
});
test('inventory separates ordinary movements from approved count adjustments on a phone-sized viewport',async({page})=>{
 await page.setViewportSize({width:390,height:844});await identity(page,['inventory.read','inventory.manage']);await page.route('**/api/syncos/material-inventory',r=>r.fulfill({json:inventory}));await page.goto('/material-inventory');await expect(page.getByRole('button',{name:'Record movement',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Approve adjustment',exact:true})).toHaveCount(0);await page.getByRole('combobox',{name:'Movement',exact:true}).selectOption('installed');await expect(page.getByRole('combobox',{name:'Work order',exact:true})).toHaveAttribute('required','');await expect(page.getByRole('combobox',{name:'Destination location',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});

test('saved form answers survive reload and preserve retry identity',async({page})=>{
 await identity(page,['form.read','form.submit']);const version={id:'v-draft',family_id:'f-draft',version:1,status:'published',schema:{name:'Field notes',fields:[{key:'note',label:'Observation',type:'text',required:true}]}};let writes:any[]=[];
 await page.route('**/api/syncos/supplemental-forms**',route=>{if(route.request().method()==='GET')return route.fulfill({json:new URL(route.request().url()).pathname.endsWith('/records')?[]:[version]});writes.push(route.request().postDataJSON());return route.fulfill({status:writes.length===1?503:201,json:writes.length===1?{message:'Connection interrupted'}:{id:'saved'}});});
 await page.goto('/forms');await page.getByRole('combobox',{name:'Form version',exact:true}).selectOption(version.id);await page.getByLabel('Observation (required)').fill('Saved before connection failed');await page.getByRole('button',{name:'Save answers on this device'}).click();await expect(page.getByText('Draft saved on this device for seven days. It has not been submitted.')).toBeVisible();
 await page.reload();await page.getByRole('combobox',{name:'Form version',exact:true}).selectOption(version.id);await page.getByRole('button',{name:'Restore saved answers'}).click();await expect(page.getByLabel('Observation (required)')).toHaveValue('Saved before connection failed');await page.getByRole('button',{name:'Submit form',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Connection interrupted'})).toBeVisible();await page.getByRole('button',{name:'Submit form',exact:true}).click();await expect(page.getByText('Form submitted. Its approved version and answers are preserved.')).toBeVisible();expect(writes).toHaveLength(2);expect(writes[0].request_key).toBe(writes[1].request_key);await expect(page.getByRole('button',{name:'Restore saved answers'})).toHaveCount(0);
});
test('form drafts do not cross users or published versions',async({page})=>{
 await identity(page,['form.read','form.submit']);let user='synthetic';await page.route('**/api/syncos/auth/me',r=>r.fulfill({json:{user_id:user,tenant_id:'synthetic',roles:['system_admin'],permissions:['form.read','form.submit']}}));const versions=[1,2].map(n=>({id:'version'+n,family_id:'family',version:n,status:'published',schema:{name:'Private notes',fields:[{key:'note',label:'Note',type:'text',required:true}]}}));await page.route('**/api/syncos/supplemental-forms**',r=>r.fulfill({json:r.request().url().endsWith('/records')?[]:versions}));await page.goto('/forms');await page.getByRole('combobox',{name:'Form version',exact:true}).selectOption('version1');await page.getByLabel('Note (required)').fill('Private');await page.getByRole('button',{name:'Save answers on this device'}).click();await expect(page.getByRole('button',{name:'Restore saved answers'})).toBeVisible();await page.getByRole('combobox',{name:'Form version',exact:true}).selectOption('version2');await expect(page.getByRole('button',{name:'Restore saved answers'})).toHaveCount(0);user='different-user';await page.reload();await page.getByRole('combobox',{name:'Form version',exact:true}).selectOption('version1');await expect(page.getByRole('button',{name:'Restore saved answers'})).toHaveCount(0);
});

test('offline cold navigation exposes only matching unexpired saved context and logout removes it',async({page,context})=>{
 await page.goto('/syncfield/offline.html');await page.evaluate(async()=>{const token='synthetic-offline-session';localStorage.setItem('syncos.apiToken',token);const fingerprint=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token))),b=>b.toString(16).padStart(2,'0')).join('');localStorage.setItem('syncos.offlineContext',JSON.stringify({fingerprint,tenant:'synthetic',user:'synthetic',savedAt:Date.now(),expires:Date.now()+60000,assignments:[{project:'Synthetic project',workOrder:'WO-OFFLINE',crew:'Crew'}]}));await navigator.serviceWorker.register('/syncfield/offline-worker.js',{scope:'/syncfield/'});await navigator.serviceWorker.ready;});
 await expect.poll(()=>page.evaluate(()=>Boolean(navigator.serviceWorker.controller))).toBe(true);await context.setOffline(true);await page.goto('/syncfield/today');await expect(page.getByRole('heading',{name:'SyncField connection recovery'})).toBeVisible();await expect(page.getByText('Synthetic project · WO-OFFLINE · Crew')).toBeVisible();await expect(page.getByText('Offline view — current authorization has not been verified.')).toBeVisible();
 await page.evaluate(()=>localStorage.setItem('syncos.apiToken','different-user'));await page.reload();await expect(page.getByText('Reconnect to verify this account before viewing saved context.')).toBeVisible();await expect(page.getByText('Synthetic project · WO-OFFLINE · Crew')).not.toBeVisible();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Log out and clear device context'}).click();expect(await page.evaluate(()=>localStorage.getItem('syncos.offlineContext'))).toBeNull();
});

test('public intake keeps a stable receipt reference across a lost response without sign-in',async({page})=>{
 let writes:any[]=[];
 await page.route('**/api/syncos/public/customer-intake/pilot-request',route=>{if(route.request().method()==='GET')return route.fulfill({json:{label:'Pilot service request',privacy_notice:'We use these details to review your request.'}});const b=route.request().postDataJSON();writes.push(b);return route.fulfill({status:writes.length===1?503:202,json:writes.length===1?{message:'Temporary interruption'}:{reference:b.request_key}});});
 await page.goto('/request-service/pilot-request');await page.getByLabel('Your name').fill('Synthetic customer');await page.getByLabel('Contact email').fill('synthetic@example.test');await page.getByLabel('Subject',{exact:true}).fill('Work request');await page.getByLabel('Request details').fill('Review a new service location');await page.getByLabel('I authorize processing').check();await page.getByRole('button',{name:'Submit request'}).click();await expect(page.getByRole('alert').filter({hasText:'Temporary interruption'})).toBeVisible();await expect(page.getByLabel('Subject',{exact:true})).toHaveValue('Work request');await page.getByRole('button',{name:'Submit request'}).click();await expect(page.getByRole('heading',{name:'Request received'})).toBeVisible();expect(writes[0].request_key).toBe(writes[1].request_key);await expect(page.getByText('No confirmation email has been sent.',{exact:false})).toBeVisible();
});

test('saved field form answers remain editable after cold offline navigation and preserve scope',async({page,context})=>{
 await page.goto('/syncfield/offline.html');await page.evaluate(async()=>{const token='synthetic-form-offline';localStorage.setItem('syncos.apiToken',token);const fingerprint=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token))),b=>b.toString(16).padStart(2,'0')).join('');localStorage.setItem('syncos.offlineContext',JSON.stringify({fingerprint,tenant:'field-tenant',user:'field-user',savedAt:Date.now(),expires:Date.now()+60000,assignments:[{id:'a1',project:'Field project'}]}));await new Promise<void>((resolve,reject)=>{const q=indexedDB.open('syncos-form-drafts',1);q.onupgradeneeded=()=>q.result.createObjectStore('drafts',{keyPath:'scope'});q.onsuccess=()=>{const db=q.result,tx=db.transaction('drafts','readwrite');for(const user of ['field-user','other-user'])tx.objectStore('drafts').put({scope:JSON.stringify(['field-tenant',user,'a1','v1']),versionId:'v1',schema:{name:user==='field-user'?'Assigned observations':'Other private form',fields:[{key:'note',label:'Observation',type:'text',required:true}]},answers:{note:'Before interruption'},requestKey:'old',savedAt:Date.now()});tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(Error('save failed'));};});await navigator.serviceWorker.register('/syncfield/offline-worker.js',{scope:'/syncfield/'});await navigator.serviceWorker.ready;});await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await context.setOffline(true);await page.goto('/syncfield/forms');await expect(page.getByText('Edit saved form: Assigned observations')).toBeVisible();await expect(page.getByText('Other private form')).toHaveCount(0);await page.getByText('Edit saved form: Assigned observations').click();await page.getByLabel('Observation (required)').fill('After cold restart');await page.getByRole('button',{name:'Save edited answers on this device'}).click();await expect(page.getByText('Answers saved. Reconnect, choose the same work assignment and form, review, then submit. Nothing has been sent.')).toBeVisible();await page.reload();await page.getByText('Edit saved form: Assigned observations').click();await expect(page.getByLabel('Observation (required)')).toHaveValue('After cold restart');
});

test('cold offline production edits survive reload but attempted requests remain immutable',async({page,context})=>{
 await page.goto('/syncfield/offline.html');await page.evaluate(async()=>{const token='synthetic-production-offline';localStorage.setItem('syncos.apiToken',token);const fingerprint=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token))),b=>b.toString(16).padStart(2,'0')).join('');localStorage.setItem('syncos.offlineContext',JSON.stringify({fingerprint,tenant:'t1',user:'u1',savedAt:Date.now(),expires:Date.now()+60000,assignments:[{id:'a1',project:'Synthetic'}]}));await new Promise<void>((resolve,reject)=>{const q=indexedDB.open('syncos-field-production',1);q.onupgradeneeded=()=>q.result.createObjectStore('mutations',{keyPath:'mutationId'});q.onsuccess=()=>{const db=q.result,tx=db.transaction('mutations','readwrite');for(const [id,status,retryCount] of [['new','PENDING',0],['attempted','SYNCING',1],['other','PENDING',0]])tx.objectStore('mutations').put({mutationId:id,operation:'CREATE_PRODUCTION',scopeKey:`tenant:t1:user:${id==='other'?'other':'u1'}:org:o1:report:r1`,payload:{location_type:'daily',reported_quantity:2,notes:id},status,retryCount,sequence:Date.now()});tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(Error('fixture save failed'));};});await navigator.serviceWorker.register('/syncfield/offline-worker.js',{scope:'/syncfield/'});await navigator.serviceWorker.ready;});await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await context.setOffline(true);await page.goto('/syncfield/production');const drafts=page.locator('details');await expect(drafts).toHaveCount(2);await drafts.first().locator('summary').click();await drafts.last().locator('summary').click();const editable=drafts.filter({has:page.getByRole('button',{name:'Save production edits on this device',includeHidden:true})});await editable.getByLabel('Reported quantity').fill('7.5');await editable.getByLabel('Work notes').fill('Corrected before first transmission');await editable.getByRole('button').click();await expect(editable.getByRole('status')).toContainText('Production edits saved');await expect(page.getByText('This request may already have reached the server.',{exact:false})).toBeVisible();await page.reload();const restored=page.locator('details').filter({has:page.getByRole('button',{name:'Save production edits on this device',includeHidden:true})});await restored.locator('summary').click();await expect(restored.getByLabel('Reported quantity')).toHaveValue('7.5');await expect(restored.getByLabel('Work notes')).toHaveValue('Corrected before first transmission');
});

test('workflow delivery retries are hidden without update authority and preserve failed status on error',async({page})=>{
 await identity(page,['workflow_task.read']);const row={id:'notice',title:'Synthetic assigned task',kind:'overdue',status:'failed',task_status:'open',due_at:null,attempts:5,last_error:'Delivery was not confirmed.'};await page.route('**/api/syncos/workflow-notifications',r=>r.fulfill({json:[row]}));await page.goto('/workflow-notifications');await expect(page.getByRole('heading',{name:'My workflow notifications'})).toBeVisible();await expect(page.getByRole('button',{name:'Retry delivery'})).toHaveCount(0);await page.route('**/api/syncos/auth/me',r=>r.fulfill({json:{user_id:'synthetic',tenant_id:'synthetic',roles:['system_admin'],permissions:['workflow_task.read','workflow_task.update'],tenant_permissions:['workflow_task.read','workflow_task.update']}}));await page.reload();await page.route('**/api/syncos/workflow-notifications/notice/retry',r=>r.fulfill({status:503,json:{message:'Temporary delivery interruption'}}));await page.getByRole('button',{name:'Retry delivery'}).click();await expect(page.getByRole('alert').filter({hasText:'Temporary delivery interruption'})).toBeVisible();await expect(page.getByRole('button',{name:'Retry delivery'})).toBeEnabled();await expect(page.getByText('overdue · Delivery: failed · Task: open')).toBeVisible();
});

test('history searches all matching pages and opens existing guarded detail routes',async({page})=>{
 await identity(page,['project.read']);await page.route('**/api/syncos/record-history',r=>r.fulfill({json:[{key:'projects',label:'Projects'}]}));let queries:string[]=[];await page.route('**/api/syncos/record-history/projects?*',r=>{const url=new URL(r.request().url());queries.push(url.search);return r.fulfill({json:{rows:[{id:url.searchParams.has('before')?'older':'newer',title:url.searchParams.has('before')?'Older project':'New project',status:'active',created_at:'2026-01-01',href:'/projects/example'}],next:url.searchParams.has('before')?null:'newer'}});});await page.goto('/record-history');await page.getByLabel('Record type').selectOption('projects');await expect(page.getByRole('link',{name:'New project'})).toHaveAttribute('href','/projects/example');await page.getByLabel('Search name, reference, status or record ID').fill('Pilot');await page.getByRole('button',{name:'Search history'}).click();await page.getByRole('button',{name:'Older matching records'}).click();await expect(page.getByRole('link',{name:'Older project'})).toBeVisible();expect(queries.at(-1)).toContain('q=Pilot');expect(queries.at(-1)).toContain('before=newer');await page.getByRole('button',{name:'Back to latest'}).click();await expect(page.getByRole('link',{name:'New project'})).toBeVisible();
});

test('field material use preserves the exact pending request across failure and reload',async({page})=>{
 await identity(page,['partner_context.read','partner_daily_production.read','partner_production_record.create']);const a={id:'assignment',project:{name:'Project'},crew:{name:'Crew'},work_order:{work_order_number:'WO-1'}};await page.route('**/api/syncos/syncfield/foreman/assignments',r=>r.fulfill({json:[a]}));let writes:any[]=[];await page.route('**/api/syncos/syncfield/foreman/materials**',r=>{if(r.request().method()==='GET')return r.fulfill({json:{next:null,work_order_id:'work',balances:[{location_id:'location',lot_id:'lot',location_label:'Truck',label:'Cable',serial_number:'REEL-1',unit:'feet',balance:'100'}],movements:[]}});writes.push(r.request().postDataJSON());return r.fulfill({status:writes.length===1?503:201,json:writes.length===1?{message:'Response interrupted'}:{id:'recorded'}});});await page.goto('/syncfield/materials');await page.getByLabel('Work assignment').selectOption('assignment');await page.getByLabel('Quantity',{exact:true}).fill('10');await page.getByLabel('Work date',{exact:true}).fill('2026-10-05');await page.getByLabel('Source document reference').fill('Synthetic report');await page.getByLabel('Reason',{exact:true}).fill('Installed at assigned site');await page.getByRole('button',{name:'Record material use',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Response interrupted'})).toBeVisible();await expect(page.getByRole('button',{name:'Record material use',exact:true})).toHaveCount(0);await page.reload();await page.getByLabel('Work assignment').selectOption('assignment');await expect(page.getByRole('region',{name:'Saved material request'})).toBeVisible();await page.getByRole('button',{name:'Retry saved material use'}).click();await expect(page.getByText('Material use recorded.',{exact:false})).toBeVisible();expect(writes).toHaveLength(2);expect(writes[1]).toEqual(writes[0]);await expect(page.getByRole('region',{name:'Saved material request'})).toHaveCount(0);
});

test('organization-scoped grants do not expose tenant-wide history or notification actions',async({page})=>{
 await identity(page,['project.read','workflow_task.read','workflow_task.update']);
 await page.route('**/api/syncos/auth/me',r=>r.fulfill({json:{user_id:'scoped-user',tenant_id:'synthetic',roles:['scoped_reader'],permissions:['project.read','workflow_task.read','workflow_task.update'],tenant_permissions:[]}}));
 for(const path of ['/record-history','/workflow-notifications']){await page.goto(path);await expect(page.getByRole('heading',{name:'Access unavailable'})).toBeVisible();await expect(page.getByRole('button',{name:'Retry delivery'})).toHaveCount(0);await expect(page.getByRole('link',{name:'History',exact:false})).toHaveCount(0);}
});
