"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {useParams,useRouter} from "next/navigation";
import {PermissionLink,useTenantCapability} from "../../../access-control";
import {syncosFetch,type SyncRecord} from "../../api";
import {ProgramPolicies} from "../program-policies";
const stages=["identified","contact_discovered","initial_outreach","application_submitted","documents_requested","compliance_review","operational_interview","rate_negotiation","approved","market_assigned","mobilized"];
const label=(s:string)=>s.replaceAll("_"," ");
export default function OnboardingProfile(){
 const {id}=useParams<{id:string}>(),router=useRouter(),creating=id==="new",canCreate=useTenantCapability("account_onboarding.create"),canRead=useTenantCapability("account_onboarding.read"),canEdit=useTenantCapability("account_onboarding.update");
 const [record,setRecord]=useState<SyncRecord|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[pending,setPending]=useState<Record<string,unknown>|null>(null);
 const dialog=useRef<HTMLDialogElement>(null),locked=useRef(false);
 async function load(){try{if(creating){const organizationId=new URL(window.location.href).searchParams.get("organization_id");if(!organizationId)throw new Error("Open an account from the onboarding board first.");const organization=await syncosFetch<SyncRecord>(`organizations/${organizationId}`);setRecord({organization_id:organizationId,organization_name:organization.name,lane:"prime",onboarding_stage:"identified"});}else setRecord(await syncosFetch<SyncRecord>(`account-onboarding/${id}`));setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load onboarding.");}}
 useEffect(()=>{if(canRead||creating&&canCreate)void load();},[id,canRead,canCreate,creating]);
 useEffect(()=>{if(pending)dialog.current?.showModal();else dialog.current?.close();},[pending]);
 function review(e:FormEvent<HTMLFormElement>){e.preventDefault();const fields=Object.fromEntries(new FormData(e.currentTarget));setError("");setPending({...fields,...(creating?{organization_id:record?.organization_id}:{}),expected_revision:record?.revision,next_action_deadline:fields.next_action_deadline||null});}
 async function save(){if(locked.current||!pending)return;locked.current=true;setBusy(true);setError("");try{const saved=await syncosFetch<SyncRecord>(creating?"account-onboarding":`account-onboarding/${id}`,{method:creating?"POST":"PATCH",body:pending});setPending(null);if(creating)router.replace(`/intelligence/account-onboarding/${saved.id}`);else await load();setNotice("Onboarding tracking updated. Work authorization and commercial approvals remain separate.");}catch(e){setError(e instanceof Error?e.message:"Could not save. Your entries are preserved.");}finally{locked.current=false;setBusy(false);}}
 if(!(creating?canCreate:canRead))return null;const editable=creating?canCreate:canEdit;
 return <main className="completion-workspace" style={{maxWidth:1000,margin:"auto",padding:24}}><PermissionLink href="/intelligence/account-onboarding">Back to account onboarding</PermissionLink><h1>Account onboarding review</h1>{notice&&<p role="status">{notice}</p>}{error&&!pending&&<p role="alert">{error}</p>}{!record?<button onClick={()=>void load()}>Retry loading profile</button>:<>
 <h2>{String(record.organization_name??"Account")}</h2><p>Lane: {label(String(record.lane))} · Current stage: {label(String(record.onboarding_stage))}</p><p>These stages track account progress. Changing a stage does not approve an agreement, authorize mobilization, accept production or release money.</p>
 {!editable&&<p role="status">Read-only onboarding review. Your role cannot change this profile.</p>}
 <dl>{["account_owner_name","primary_contact_name","rate_sheet_status","approval_status","next_action","next_action_deadline","required_documents","missing_documents","customer_programs","market_availability","notes"].map(key=><div key={key}><dt>{label(key)}</dt><dd>{Array.isArray(record[key])?(record[key] as string[]).join(", ")||"None recorded":String(record[key]??"Not recorded")}</dd></div>)}</dl>
 <p>Document and program summaries are tracking information. Verify originals and the applicable approved compliance policy before treating an account as ready.</p>
 {editable&&<form key={String(record.updated_at)} onSubmit={review}><fieldset disabled={busy}><legend>Update tracking and follow-up</legend>{creating&&<label>Account lane<select name="lane" defaultValue="prime"><option value="prime">Prime / Customer</option><option value="contractor">Contractor / Vendor</option></select></label>}<label>Onboarding stage<select name="onboarding_stage" required defaultValue={String(record.onboarding_stage)}>{stages.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>Next action<input name="next_action" maxLength={2000} defaultValue={String(record.next_action??"")}/></label><label>Next action deadline<input type="date" name="next_action_deadline" defaultValue={record.next_action_deadline?new Date(String(record.next_action_deadline)).toISOString().slice(0,10):""}/></label><label>Tracking notes<textarea name="notes" maxLength={10000} defaultValue={String(record.notes??"")}/></label><button style={{minHeight:44}}>Review changes</button></fieldset></form>}
 {!creating&&<ProgramPolicies profileId={id}/>}
 </>}
 <dialog ref={dialog} aria-labelledby="onboarding-confirm-title" onCancel={e=>{e.preventDefault();if(!busy)setPending(null);}} style={{maxWidth:560,width:"calc(100% - 32px)"}}><h2 id="onboarding-confirm-title">Confirm onboarding update</h2><p>New tracking stage: {label(String(pending?.onboarding_stage??""))}</p><p>This records progress only. It creates no contract, assignment, invoice, payable or payment. The change is recorded in the audit history.</p>{error&&<p role="alert">{error}</p>}<button disabled={busy} onClick={()=>setPending(null)} style={{minHeight:44}}>Keep editing</button><button disabled={busy} onClick={()=>void save()} style={{minHeight:44}}>{busy?"Saving…":"Confirm tracking update"}</button></dialog>
 </main>;
}
