"use client";
import { useEffect, useRef, useState } from "react";
import { syncosFetch } from "../intelligence/api";
export function FieldEvidence({ reportId, recordId, canUpload, onSaved }: { reportId: string; recordId?: string; canUpload: boolean; onSaved?: () => void }) {
 const [rows,setRows]=useState<{id:string;file_name:string;description:string}[]>([]);const [file,setFile]=useState<File|null>(null);const [description,setDescription]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const guard=useRef(false);const mutation=useRef(crypto.randomUUID());
 async function load(){setRows(await syncosFetch(`syncfield/foreman/evidence?daily_report_id=${encodeURIComponent(reportId)}`));}
 useEffect(()=>{setFile(null);setDescription("");setMessage("");mutation.current=crypto.randomUUID();void load().catch(e=>setMessage(e.message));},[reportId,recordId]);
 return <section className="partner-panel"><h3>Photos and evidence</h3><p>Upload JPEG, PNG, or PDF evidence up to 2 MB. Evidence is attached to this report; it does not change submitted quantities or imply acceptance.</p>{rows.map(row=><div key={row.id}><p>{row.file_name} — {row.description}</p><button type="button" className="partner-button" onClick={async()=>{try{const file=await syncosFetch<{content_base64:string;mime_type:string;file_name:string}>(`syncfield/foreman/evidence/${row.id}`);const url=URL.createObjectURL(new Blob([Uint8Array.from(atob(file.content_base64),c=>c.charCodeAt(0))],{type:file.mime_type}));const link=document.createElement("a");link.href=url;link.download=file.file_name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){setMessage(error instanceof Error?error.message:"Unable to download evidence.");}}}>Download {row.file_name}</button></div>)}{canUpload && <form className="partner-form-grid" onSubmit={async e=>{e.preventDefault();if(guard.current||!file)return;if(file.size>2097152){setMessage("Choose a file up to 2 MB.");return;}guard.current=true;setBusy(true);setMessage("");try{const content=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]);reader.onerror=()=>reject(new Error("Could not read this file."));reader.readAsDataURL(file);});await syncosFetch("syncfield/foreman/evidence",{method:"POST",body:{daily_report_id:reportId,production_record_id:recordId,file_name:file.name,mime_type:file.type,description,content_base64:content,client_mutation_id:mutation.current}});mutation.current=crypto.randomUUID();setDescription("");setFile(null);await load();onSaved?.();setMessage("Evidence saved.");}catch(error){setMessage(error instanceof Error?error.message:"Upload failed; retry when connected.");}finally{guard.current=false;setBusy(false);}}}><label>Evidence file<input required disabled={busy} type="file" accept="image/jpeg,image/png,application/pdf" onChange={e=>{setFile(e.target.files?.[0]??null);mutation.current=crypto.randomUUID();}} /></label><label>What does this evidence show?<textarea required disabled={busy} value={description} onChange={e=>{setDescription(e.target.value);mutation.current=crypto.randomUUID();}} /></label><button disabled={busy||!file} className="partner-button wide-touch">{busy?"Uploading…":"Upload evidence"}</button></form>}{message&&<p role="status">{message}</p>}</section>;
}
export function FieldIncident({assignmentId}:{assignmentId?:string}){
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const guard=useRef(false);const mutation=useRef(crypto.randomUUID());
 return <details className="partner-panel"><summary>Report an incident or near miss</summary><p>For an emergency, contact emergency services and your supervisor immediately. This report records the event; it does not contact emergency services.</p><form className="partner-form-grid" onChange={()=>{mutation.current=crypto.randomUUID();}} onSubmit={async e=>{e.preventDefault();if(guard.current)return;const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));guard.current=true;setBusy(true);try{await syncosFetch("syncfield/foreman/incidents",{method:"POST",body:{...values,occurred_at:new Date(String(values.occurred_at)).toISOString(),assignment_id:assignmentId,client_mutation_id:mutation.current}});mutation.current=crypto.randomUUID();form.reset();setMessage("Incident recorded. Follow your supervisor’s reporting procedure.");}catch(error){setMessage(error instanceof Error?error.message:"Report could not be saved. Retry.");}finally{guard.current=false;setBusy(false);}}}><fieldset disabled={busy}><legend>Incident details</legend><label>Type<select name="incident_type"><option value="near_miss">Near miss</option><option value="injury">Injury</option><option value="property_damage">Property damage</option><option value="environmental">Environmental</option><option value="other">Other</option></select></label><label>When did it happen?<input required type="datetime-local" name="occurred_at" /></label><label>Location<input required name="location" /></label><label>What happened?<textarea required name="description" /></label><label>Immediate action taken<textarea required name="immediate_action" /></label></fieldset><button disabled={busy} className="partner-button wide-touch">{busy?"Saving…":"Record incident"}</button>{message&&<p role="status">{message}</p>}</form></details>;
}
