"use client";
import {useRef,useState,type FormEvent} from 'react';
import {PermissionLink} from '../access-control';
import {syncosFetch} from '../intelligence/api';
type Result={object_type:string;id:string;title:string|null;status:string;snippet:string;_cursor:string};
const routes:Record<string,string>={organization:'/intelligence/organizations/',contact:'/intelligence/contacts/',signal:'/intelligence/signals/',relationship_map:'/intelligence/relationship-maps/',opportunity_candidate:'/opportunities/candidates/',opportunity:'/opportunities/',coverage_plan:'/opportunities/coverage/',project:'/projects/',work_order:'/work-orders/',production_record:'/production/',qc_review:'/qc/',billable_item:'/billable/',settlement:'/settlements/',invoice:'/invoices/',cash_receipt:'/cash/receipts/',payment_application:'/cash/applications/',collection_case:'/collections/',collection_action:'/collection-actions/',contractor_payable:'/contractor-payables/',payroll_run:'/payroll/',payment_batch:'/payments/',bank_account:'/bank-reconciliation/accounts/',bank_transaction:'/bank-reconciliation/transactions/',accounting_export_batch:'/accounting-exports/'};
export default function Search(){const [query,setQuery]=useState(''),[archived,setArchived]=useState(false),[applied,setApplied]=useState({query:'',archived:false}),[rows,setRows]=useState<Result[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[searched,setSearched]=useState(false),[page,setPage]=useState(1);const gate=useRef(false);
 async function load(q:string,include:boolean,after='',number=1){if(gate.current)return;gate.current=true;setBusy(true);setError('');try{const params=new URLSearchParams({q,archived:String(include),...(after?{after}:{})});const found=await syncosFetch<Result[]>('search?'+params);setRows(found);setApplied({query:q,archived:include});setPage(number);setSearched(true);}catch(e){setError(e instanceof Error?e.message:'Search could not be completed. Your search is preserved; try again.');}finally{setBusy(false);gate.current=false;}}
 function submit(e:FormEvent){e.preventDefault();void load(query.trim(),archived);}
 return <main className="completion-workspace" style={{maxWidth:1000,margin:'auto',padding:24}}><h1>Global search</h1><p>Find records across the workspaces you can read. Search results do not grant access to additional records or actions.</p><form onSubmit={submit}><label>Search records<input required maxLength={200} value={query} onChange={e=>setQuery(e.target.value)} style={{minHeight:44}}/></label><label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Include archived records</label><button disabled={busy||!query.trim()} style={{minHeight:44}}>Search records</button></form>{error&&<p role="alert">{error}</p>}{busy&&<p role="status">Searching…</p>}{searched&&!busy&&<p role="status">{rows.length?`${rows.length} results on page ${page}`:'No matching records. Try another name or reference.'}</p>}<ul style={{listStyle:'none',padding:0}}>{rows.map(r=><li key={r.object_type+':'+r.id} style={{padding:16,borderBottom:'1px solid #8c9bab',overflowWrap:'anywhere'}}>{routes[r.object_type]?<PermissionLink href={routes[r.object_type]+r.id}>{r.title||r.id}</PermissionLink>:<strong>{r.title||r.id}</strong>}<p>{r.object_type.replaceAll('_',' ')} · {r.status}</p><p>{r.snippet}</p><small>Reference: {r.id}</small></li>)}</ul>{rows.length===50&&<button disabled={busy} style={{minHeight:44}} onClick={()=>void load(applied.query,applied.archived,rows[49]._cursor,page+1)}>Next search results</button>}{page>1&&<button disabled={busy} style={{minHeight:44}} onClick={()=>void load(applied.query,applied.archived)}>Back to first results</button>}</main>;
}
