import {BadRequestException,Body,Controller,Get,Inject,Param,Post,Query,Req} from '@nestjs/common';
import type {Pool,PoolClient} from 'pg';
import {executeWriteAction,type WriteActionResult} from '@syncos/shared';
import {DATABASE_POOL} from '../modules/database.module';
import {RequirePermission,TenantPermissionOnly} from '../security/require-permission.decorator';
import type {AuthenticatedRequest} from './intelligence.types';
const uuid=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(v);
@Controller('access-administration')
@TenantPermissionOnly()
export class AccessAdministrationController {
 constructor(@Inject(DATABASE_POOL) private readonly pool:Pool){}
 private async write(r:AuthenticatedRequest,action:string,fn:(c:PoolClient)=>Promise<WriteActionResult<any>>){const c=await this.pool.connect();try{return await executeWriteAction(c,{tenantId:r.auth.tenantId,actorUserId:r.auth.userId,action,aggregateType:'tenant_user',eventType:action,write:async c=>{await c.query('SELECT id FROM tenants WHERE id=$1 FOR UPDATE',[r.auth.tenantId]);return fn(c);}});}finally{c.release();}}
 @Get('members') @RequirePermission('admin.manage_users')
 async members(@Req() r:AuthenticatedRequest,@Query('search') search:string,@Query('after') after:string){if(after&&!uuid(after))throw new BadRequestException('Invalid page cursor');const rows=(await this.pool.query(`SELECT tu.id,tu.user_id,tu.status,u.email,u.display_name,u.status account_status FROM tenant_users tu JOIN users u ON u.id=tu.user_id WHERE tu.tenant_id=$1 AND tu.deleted_at IS NULL AND u.deleted_at IS NULL AND ($2::uuid IS NULL OR tu.id>$2) AND (u.email ILIKE $3 OR u.display_name ILIKE $3) ORDER BY tu.id LIMIT 51`,[r.auth.tenantId,after||null,'%'+String(search??'').slice(0,100)+'%'])).rows;return {items:rows.slice(0,50),next:rows.length>50?rows[49].id:null};}
 @Get('members/:id') @RequirePermission('admin.manage_users')
 async read(@Req() r:AuthenticatedRequest,@Param('id') id:string){if(!uuid(id))throw new BadRequestException('Choose a member');const member=(await this.pool.query('SELECT tu.id,tu.user_id,tu.status,u.email,u.display_name FROM tenant_users tu JOIN users u ON u.id=tu.user_id WHERE tu.tenant_id=$1 AND tu.id=$2 AND tu.deleted_at IS NULL',[r.auth.tenantId,id])).rows[0];if(!member)throw new BadRequestException('Member not found');return {member,grants:(await this.pool.query(`SELECT ur.id,ur.role_id,r.name,r.system_key,ur.scope_type,ur.scope_id,o.name organization_name FROM user_roles ur JOIN roles r ON r.id=ur.role_id AND r.tenant_id=ur.tenant_id LEFT JOIN organizations o ON o.id=ur.scope_id AND o.tenant_id=ur.tenant_id AND ur.scope_type='organization' WHERE ur.tenant_id=$1 AND ur.tenant_user_id=$2 ORDER BY r.name`,[r.auth.tenantId,id])).rows};}
 @Get('roles') @RequirePermission('admin.manage_roles')
 async roles(@Req() r:AuthenticatedRequest){return {roles:(await this.pool.query(`SELECT r.id,r.name,r.system_key,array_agg(p.key ORDER BY p.key) permissions FROM roles r JOIN role_permissions rp ON rp.role_id=r.id AND rp.tenant_id=r.tenant_id JOIN permissions p ON p.id=rp.permission_id WHERE r.tenant_id=$1 AND r.deleted_at IS NULL GROUP BY r.id ORDER BY r.name`,[r.auth.tenantId])).rows};}
 @Post('members/:id/status') @RequirePermission('admin.manage_users')
 async status(@Req() r:AuthenticatedRequest,@Param('id') id:string,@Body() b:Record<string,unknown>){if(!uuid(id)||!['active','disabled'].includes(String(b.status)))throw new BadRequestException('Choose active or disabled');this.reason(b.reason);return this.write(r,'access.membership_changed',async c=>{const before=(await c.query('SELECT * FROM tenant_users WHERE tenant_id=$1 AND id=$2 AND deleted_at IS NULL FOR UPDATE',[r.auth.tenantId,id])).rows[0];if(!before)throw new BadRequestException('Member not found');if(before.user_id===r.auth.userId)throw new BadRequestException('Another administrator must change your access');if(before.status==='invited'||before.status==='archived')throw new BadRequestException('Use the approved onboarding or recovery workflow for this membership');if(b.status==='active'&&!(await c.query("SELECT 1 FROM users WHERE id=$1 AND status='active' AND deleted_at IS NULL",[before.user_id])).rows.length)throw new BadRequestException('Account is not active');const after=(await c.query('UPDATE tenant_users SET status=$3,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING id,user_id,status',[r.auth.tenantId,id,b.status])).rows[0];await this.assertAdministratorRemains(c,r.auth.tenantId);await c.query('UPDATE users SET auth_version=auth_version+1 WHERE id=$1',[before.user_id]);return {entityType:'tenant_user',entityId:id,beforeState:{status:before.status},afterState:{...after,reason:b.reason}};});}
 @Post('members/:id/roles') @RequirePermission('admin.manage_roles')
 async grant(@Req() r:AuthenticatedRequest,@Param('id') id:string,@Body() b:Record<string,unknown>){if(!uuid(id)||!uuid(b.role_id)||!['grant','revoke'].includes(String(b.operation)))throw new BadRequestException('Choose a member, role and operation');this.reason(b.reason);return this.write(r,'access.role_changed',async c=>{
 const member=(await c.query("SELECT tu.* FROM tenant_users tu JOIN users u ON u.id=tu.user_id WHERE tu.tenant_id=$1 AND tu.id=$2 AND tu.deleted_at IS NULL AND u.deleted_at IS NULL FOR UPDATE OF tu",[r.auth.tenantId,id])).rows[0];if(!member||member.user_id===r.auth.userId)throw new BadRequestException('Choose another workspace member');
 const role=(await c.query('SELECT * FROM roles WHERE tenant_id=$1 AND id=$2 AND deleted_at IS NULL',[r.auth.tenantId,b.role_id])).rows[0];if(!role)throw new BadRequestException('Role not found');
 // Tenant administration changes tenant grants only. Partner organization grants
 // remain in workforce onboarding, where relationship and worker links are checked.
 if(['partner_admin','partner_foreman','sync_foreman'].includes(role.system_key))throw new BadRequestException('Manage field and partner role assignments through workforce onboarding');
 if(b.operation==='grant'){
  if(member.status!=='active')throw new BadRequestException('Activate the member before granting a role');
  const excess=(await c.query(`SELECT p.key FROM role_permissions rp JOIN permissions p ON p.id=rp.permission_id WHERE rp.tenant_id=$1 AND rp.role_id=$2 AND NOT EXISTS(SELECT 1 FROM tenant_users tu JOIN user_roles ur ON ur.tenant_user_id=tu.id AND ur.tenant_id=tu.tenant_id JOIN roles ar ON ar.id=ur.role_id AND ar.tenant_id=ur.tenant_id JOIN role_permissions ap ON ap.role_id=ar.id AND ap.tenant_id=ar.tenant_id WHERE tu.tenant_id=$1 AND tu.user_id=$3 AND tu.status='active' AND tu.deleted_at IS NULL AND ur.scope_type='tenant' AND ar.deleted_at IS NULL AND ap.permission_id=p.id)`,[r.auth.tenantId,b.role_id,r.auth.userId])).rows;if(excess.length)throw new BadRequestException('You cannot grant permissions beyond your own workspace authority');
  await c.query(`INSERT INTO user_roles(tenant_id,tenant_user_id,role_id,scope_type,scope_id) SELECT $1,$2,$3,'tenant',$1 WHERE NOT EXISTS(SELECT 1 FROM user_roles WHERE tenant_id=$1 AND tenant_user_id=$2 AND role_id=$3 AND scope_type='tenant')`,[r.auth.tenantId,id,b.role_id]);
 }else await c.query("DELETE FROM user_roles WHERE tenant_id=$1 AND tenant_user_id=$2 AND role_id=$3 AND scope_type='tenant'",[r.auth.tenantId,id,b.role_id]);
 await this.assertAdministratorRemains(c,r.auth.tenantId);await c.query('UPDATE users SET auth_version=auth_version+1 WHERE id=$1',[member.user_id]);return {entityType:'tenant_user',entityId:id,afterState:{member_id:id,role_id:b.role_id,operation:b.operation,reason:b.reason}};
 });}
 private reason(value:unknown){if(typeof value!=='string'||value.trim().length<5||value.length>2000)throw new BadRequestException('Record the reviewed reason for this access change');}
 private async assertAdministratorRemains(c:PoolClient,tenant:string){const row=(await c.query(`SELECT tu.id FROM tenant_users tu JOIN users u ON u.id=tu.user_id JOIN user_roles ur ON ur.tenant_user_id=tu.id AND ur.tenant_id=tu.tenant_id JOIN roles r ON r.id=ur.role_id AND r.tenant_id=tu.tenant_id JOIN role_permissions rp ON rp.role_id=r.id AND rp.tenant_id=r.tenant_id JOIN permissions p ON p.id=rp.permission_id WHERE tu.tenant_id=$1 AND tu.status='active' AND tu.deleted_at IS NULL AND u.status='active' AND u.deleted_at IS NULL AND r.deleted_at IS NULL AND ur.scope_type='tenant' AND p.key IN ('admin.manage_users','admin.manage_roles') GROUP BY tu.id HAVING count(DISTINCT p.key)=2 LIMIT 1`,[tenant])).rows[0];if(!row)throw new BadRequestException('At least one active workspace administrator must remain');}
}
