import {BadRequestException,Body,ConflictException,Controller,Get,Inject,NotFoundException,Param,Post,Req,Res} from '@nestjs/common';
import type {Response} from 'express';
import type {Pool,PoolClient} from 'pg';
import {executeWriteAction} from '@syncos/shared';
import {DATABASE_POOL} from '../modules/database.module';
import {RequirePermission,TenantPermissionOnly} from '../security/require-permission.decorator';
import type {AuthenticatedRequest} from './intelligence.types';
import {sanitizeRestrictedFileName,detectRestrictedFileMime,calculateRestrictedFileSha256} from '../restricted-files/restricted-file.primitives';
const text=(v:unknown,name:string,max=2000)=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw new BadRequestException(`${name} is required (maximum ${max} characters).`);return v.trim();};
const day=(v:any)=>v instanceof Date?v.toISOString().slice(0,10):String(v);
const uuid=(v:unknown)=>{if(typeof v!=='string'||!/^[a-f\d]{8}(-[a-f\d]{4}){3}-[a-f\d]{12}$/i.test(v))throw new BadRequestException('Choose a valid record.');return v;};
function date(v:unknown,optional=false):string|null {if(optional&&(v===null||v===undefined||v===''))return null;const s=String(v);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(Date.parse(s))||new Date(s).toISOString().slice(0,10)!==s)throw new BadRequestException('Use a valid calendar date.');return s;}
@Controller('account-programs') @TenantPermissionOnly()
export class AccountProgramsController {
 constructor(@Inject(DATABASE_POOL) private readonly pool:Pool){}
 @Get('profiles/:id') @RequirePermission('account_onboarding.read')
 async list(@Req() r:AuthenticatedRequest,@Param('id') id:string){uuid(id);await this.profile(this.pool,r,id);return (await this.pool.query('SELECT id,name,created_at FROM account_programs WHERE tenant_id=$1 AND profile_id=$2 ORDER BY name,id',[r.auth.tenantId,id])).rows;}
 @Post('profiles/:id') @RequirePermission('account_onboarding.update')
 async create(@Req() r:AuthenticatedRequest,@Param('id') id:string,@Body() b:Record<string,unknown>){uuid(id);const name=text(b.name,'Program name',160);return this.write(r,'account_program.created',async c=>{await this.profile(c,r,id,true);const old=(await c.query('SELECT * FROM account_programs WHERE tenant_id=$1 AND profile_id=$2 AND name=$3',[r.auth.tenantId,id,name])).rows[0];if(old)return this.result(old,true);const row=(await c.query('INSERT INTO account_programs(tenant_id,profile_id,name,created_by) VALUES($1,$2,$3,$4) RETURNING *',[r.auth.tenantId,id,name,r.auth.userId])).rows[0];return this.result(row);});}
 @Get(':id') @RequirePermission('account_onboarding.read')
 async detail(@Req() r:AuthenticatedRequest,@Param('id') id:string){uuid(id);const program=await this.program(this.pool,r,id);const policies=(await this.pool.query('SELECT * FROM account_program_policies WHERE tenant_id=$1 AND program_id=$2 ORDER BY revision DESC',[r.auth.tenantId,id])).rows;
  const originals=(await this.pool.query('SELECT id,file_name,mime_type,checksum,octet_length(content) AS size_bytes,created_at FROM account_program_originals WHERE tenant_id=$1 AND program_id=$2 ORDER BY created_at,id',[r.auth.tenantId,id])).rows;
  const reviews=(await this.pool.query('SELECT r.* FROM account_program_reviews r JOIN account_program_policies p ON p.tenant_id=r.tenant_id AND p.id=r.policy_id WHERE p.tenant_id=$1 AND p.program_id=$2 ORDER BY r.reviewed_at DESC,r.id DESC',[r.auth.tenantId,id])).rows;
  const today=(await this.pool.query("SELECT (now() AT TIME ZONE 'UTC')::date::text AS today")).rows[0].today;
  const latest=policies.find(p=>day(p.effective_from)<=today);
  const active=latest&&(!latest.effective_until||day(latest.effective_until)>=today)?latest:null;
  const requirements=active?active.requirements.map((q:any)=>{const review=reviews.find(v=>v.policy_id===active.id&&v.requirement_key===q.key);const state=!review?'missing':review.expires_on&&day(review.expires_on)<today?'expired':review.decision;return {...q,state,review:review??null};}):[];
  return {program,policies,originals,reviews,active_policy_id:active?.id??null,requirements,ready:Boolean(active)&&requirements.every((q:any)=>q.state==='approved'),boundary:'Document readiness only; contracts, work authorization, customer acceptance and finance remain separate.'};
 }
 @Post(':id/originals') @RequirePermission('account_onboarding.update')
 async upload(@Req() r:AuthenticatedRequest,@Param('id') id:string,@Body() b:Record<string,unknown>){uuid(id);const name=sanitizeRestrictedFileName(text(b.file_name,'Filename',240)),encoded=String(b.content_base64??'');if(encoded.length>13981016||!/^[A-Za-z0-9+/]*={0,2}$/.test(encoded))throw new BadRequestException('Upload a supported original up to 10 MiB.');const content=Buffer.from(encoded,'base64');if(!content.length||content.length>10485760)throw new BadRequestException('Upload an original up to 10 MiB.');let mime:string;try{mime=detectRestrictedFileMime(content);}catch{throw new BadRequestException('Supported originals: PDF, JPEG, PNG and WebP.');}if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(mime))throw new BadRequestException('Supported originals: PDF, JPEG, PNG and WebP.');const checksum=calculateRestrictedFileSha256(content);
  return this.write(r,'account_program.original_added',async c=>{await this.program(c,r,id,true);const old=(await c.query('SELECT id,file_name,mime_type,checksum FROM account_program_originals WHERE tenant_id=$1 AND program_id=$2 AND checksum=$3',[r.auth.tenantId,id,checksum])).rows[0];if(old)return this.result(old,true);const row=(await c.query('INSERT INTO account_program_originals(tenant_id,program_id,file_name,mime_type,checksum,content,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,file_name,mime_type,checksum',[r.auth.tenantId,id,name,mime,checksum,content,r.auth.userId])).rows[0];return this.result(row);});
 }
 @Get(':id/originals/:fileId') @RequirePermission('account_onboarding.read')
 async download(@Req() r:AuthenticatedRequest,@Param('id') id:string,@Param('fileId') fileId:string,@Res() res:Response){uuid(id);uuid(fileId);await this.program(this.pool,r,id);const row=(await this.pool.query('SELECT * FROM account_program_originals WHERE tenant_id=$1 AND program_id=$2 AND id=$3',[r.auth.tenantId,id,fileId])).rows[0];if(!row)throw new NotFoundException('Original not found.');if(calculateRestrictedFileSha256(row.content)!==row.checksum)throw new ConflictException('Original integrity check failed.');await this.write(r,'account_program.original_downloaded',async()=>this.result({id:row.id,program_id:id,checksum:row.checksum}));res.setHeader('Content-Type',row.mime_type);res.setHeader('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(row.file_name)}`);res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.send(row.content);}
 @Post(':id/policies') @RequirePermission('account_onboarding.update')
 async policy(@Req() r:AuthenticatedRequest,@Param('id') id:string,@Body() b:Record<string,unknown>){uuid(id);const source=uuid(b.source_original_id),from=date(b.effective_from)!,until=date(b.effective_until,true),reason=text(b.reason,'Policy approval reason');if(b.confirmed!==true)throw new BadRequestException('Confirm this policy against the original governing requirements.');if(until&&until<from)throw new BadRequestException('The end date must follow the start date.');if(!Array.isArray(b.requirements)||!b.requirements.length||b.requirements.length>100)throw new BadRequestException('Specify between 1 and 100 document requirements.');const requirements=b.requirements.map((q:any)=>{if(!q||typeof q!=='object')throw new BadRequestException('Invalid requirement.');return {key:text(q.key,'Requirement key',80),label:text(q.label,'Requirement label',240)};});if(new Set(requirements.map(q=>q.key)).size!==requirements.length)throw new BadRequestException('Requirement keys must be unique.');
  return this.write(r,'account_program.policy_approved',async c=>{await this.program(c,r,id,true);await this.original(c,r,id,source);const current=Number((await c.query('SELECT COALESCE(max(revision),0) AS revision FROM account_program_policies WHERE tenant_id=$1 AND program_id=$2',[r.auth.tenantId,id])).rows[0].revision);if(b.expected_revision!==current)throw new ConflictException('Policy changed. Reload and review before approval.');const row=(await c.query('INSERT INTO account_program_policies(tenant_id,program_id,revision,source_original_id,effective_from,effective_until,requirements,reason,approved_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[r.auth.tenantId,id,current+1,source,from,until,JSON.stringify(requirements),reason,r.auth.userId])).rows[0];return this.result(row);});
 }
 @Post(':id/reviews') @RequirePermission('account_onboarding.update')
 async review(@Req() r:AuthenticatedRequest,@Param('id') id:string,@Body() b:Record<string,unknown>){uuid(id);const policyId=uuid(b.policy_id),originalId=uuid(b.original_id),key=text(b.requirement_key,'Requirement',80),reason=text(b.reason,'Review reason'),expires=date(b.expires_on,true),decision=String(b.decision);if(!['submitted','approved','rejected'].includes(decision))throw new BadRequestException('Choose a review decision.');if(decision==='approved'&&b.confirmed!==true)throw new BadRequestException('Confirm the original is readable and meets this requirement.');return this.write(r,'account_program.document_reviewed',async c=>{await this.program(c,r,id,true);await this.original(c,r,id,originalId);const p=(await c.query('SELECT * FROM account_program_policies WHERE tenant_id=$1 AND program_id=$2 AND id=$3',[r.auth.tenantId,id,policyId])).rows[0];if(!p||!p.requirements.some((q:any)=>q.key===key))throw new BadRequestException('Requirement not found in this policy.');const previous=(await c.query('SELECT id FROM account_program_reviews WHERE tenant_id=$1 AND policy_id=$2 AND requirement_key=$3 ORDER BY reviewed_at DESC,id DESC LIMIT 1',[r.auth.tenantId,policyId,key])).rows[0];if((b.expected_review_id??null)!==(previous?.id??null))throw new ConflictException('Review changed. Reload before saving.');const row=(await c.query('INSERT INTO account_program_reviews(tenant_id,policy_id,requirement_key,original_id,decision,expires_on,reason,reviewed_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[r.auth.tenantId,policyId,key,originalId,decision,expires,reason,r.auth.userId])).rows[0];return this.result(row);});}
 private async profile(c:Pool|PoolClient,r:AuthenticatedRequest,id:string,lock=false){const row=(await c.query(`SELECT id FROM account_onboarding_profiles WHERE tenant_id=$1 AND id=$2 AND deleted_at IS NULL ${lock?'FOR UPDATE':''}`,[r.auth.tenantId,id])).rows[0];if(!row)throw new NotFoundException('Account profile not found.');return row;}
 private async program(c:Pool|PoolClient,r:AuthenticatedRequest,id:string,lock=false){const row=(await c.query(`SELECT p.* FROM account_programs p JOIN account_onboarding_profiles a ON a.tenant_id=p.tenant_id AND a.id=p.profile_id WHERE p.tenant_id=$1 AND p.id=$2 AND a.deleted_at IS NULL ${lock?'FOR UPDATE OF p':''}`,[r.auth.tenantId,id])).rows[0];if(!row)throw new NotFoundException('Account program not found.');return row;}
 private async original(c:PoolClient,r:AuthenticatedRequest,id:string,file:string){if(!(await c.query('SELECT 1 FROM account_program_originals WHERE tenant_id=$1 AND program_id=$2 AND id=$3',[r.auth.tenantId,id,file])).rowCount)throw new BadRequestException('Choose an original belonging to this program.');}
 private result(row:any,retry=false){return {entityType:'account_program',entityId:row.id,afterState:row,skipEventAudit:retry};}
 private async write(r:AuthenticatedRequest,event:string,write:(c:PoolClient)=>Promise<any>){const c=await this.pool.connect();try{return await executeWriteAction(c,{tenantId:r.auth.tenantId,actorUserId:r.auth.userId,action:event,aggregateType:'account_program',eventType:event,write});}finally{c.release();}}
}
