import {workspaceHistory,workspaceChoices,type HistoryQuery} from './workspace-history';
import {BadRequestException,Body,Controller,Get,Inject,Param,Post,Req,Res,Query} from '@nestjs/common';
import type {Response} from 'express';
import type {Pool,PoolClient} from 'pg';
import {executeWriteAction} from '@syncos/shared';
import {DATABASE_POOL} from '../modules/database.module';
import {RequirePermission,TenantPermissionOnly} from '../security/require-permission.decorator';
import type {AuthenticatedRequest} from './intelligence.types';
import {sanitizeRestrictedFileName,detectRestrictedFileMime,calculateRestrictedFileSha256} from '../restricted-files/restricted-file.primitives';
const uuid=(v:unknown)=>{if(typeof v!=='string'||!/^[a-f\d]{8}(-[a-f\d]{4}){3}-[a-f\d]{12}$/i.test(v))throw new BadRequestException('Select a valid record.');return v;};
const str=(v:unknown,label:string,max=1000)=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw new BadRequestException(`${label} is required, up to ${max} characters.`);return v.trim();};
@Controller('customer-inquiries') @TenantPermissionOnly()
export class CustomerInquiriesController {
 constructor(@Inject(DATABASE_POOL) private readonly pool:Pool){}
 @Get() @RequirePermission('customer_inquiry.read')
 async list(@Req() r:AuthenticatedRequest,@Query() query:HistoryQuery={}){const t=r.auth.tenantId;return {
 inquiries:await workspaceHistory(this.pool,t,'inquiries',query),
 owners:(await this.pool.query("SELECT u.id,u.display_name AS label FROM users u JOIN tenant_users tu ON tu.user_id=u.id WHERE tu.tenant_id=$1 AND tu.status='active' AND tu.deleted_at IS NULL AND u.status='active' AND u.deleted_at IS NULL AND EXISTS(SELECT 1 FROM user_roles ur JOIN roles ar ON ar.id=ur.role_id AND ar.tenant_id=ur.tenant_id AND ar.deleted_at IS NULL JOIN role_permissions rp ON rp.role_id=ur.role_id AND rp.tenant_id=ur.tenant_id JOIN permissions perm ON perm.id=rp.permission_id WHERE ur.tenant_user_id=tu.id AND ur.tenant_id=tu.tenant_id AND ur.scope_type='tenant' AND perm.key='customer_inquiry.manage') ORDER BY u.display_name",[t])).rows,
 opportunities:(await this.pool.query('SELECT id,title AS label FROM opportunities WHERE tenant_id=$1 AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 200',[t])).rows,
 projects:(await this.pool.query('SELECT id,name AS label FROM projects WHERE tenant_id=$1 AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 200',[t])).rows};}
 @Get('choices') @RequirePermission('customer_inquiry.read')
 async choices(@Req() r:AuthenticatedRequest,@Query() query:{kind?:string;q?:string}){return workspaceChoices(this.pool,r.auth.tenantId,String(query.kind),query.q,['opportunities','projects']);}
 @Post() @RequirePermission('customer_inquiry.manage')
 async create(@Req() r:AuthenticatedRequest,@Body() b:Record<string,unknown>){const key=uuid(b.request_key),values=[str(b.customer_name,'Customer name'),str(b.email,'Email',254).toLowerCase(),str(b.subject,'Subject',240),str(b.details,'Request details',10000),str(b.source_reference,'Source and permission to process this request')];if(!/^\S+@\S+\.\S+$/.test(values[1]))throw new BadRequestException('Enter a valid contact email.');if(b.authorized!==true)throw new BadRequestException('Confirm that this request is authorized for processing.');
  return this.write(r,'customer_inquiry.created',async c=>{await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[r.auth.tenantId+':inquiry:'+key]);const old=(await c.query('SELECT * FROM customer_service_inquiries WHERE tenant_id=$1 AND request_key=$2',[r.auth.tenantId,key])).rows[0];if(old){if(['customer_name','email','subject','details','source_reference'].some((k,i)=>old[k]!==values[i]))throw new BadRequestException('This request was already saved with different details.');return this.result(old,true);}
   return this.result((await c.query('INSERT INTO customer_service_inquiries(tenant_id,request_key,customer_name,email,subject,details,source_reference,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[r.auth.tenantId,key,...values,r.auth.userId])).rows[0]);});}
 @Post(':id/review') @RequirePermission('customer_inquiry.manage')
 async review(@Req() r:AuthenticatedRequest,@Param('id') id:string,@Body() b:Record<string,unknown>){uuid(id);const status=str(b.status,'Status'),note=str(b.follow_up_note,'Follow-up or closure note',4000),owner=b.owner_user_id?uuid(b.owner_user_id):null,opportunity=b.opportunity_id?uuid(b.opportunity_id):null,project=b.project_id?uuid(b.project_id):null;
  if(!['new','assigned','awaiting_customer','qualified','closed'].includes(status))throw new BadRequestException('Invalid inquiry status.');if(status!=='new'&&!owner)throw new BadRequestException('Assign an owner before advancing this inquiry.');if(status==='qualified'&&!opportunity&&!project)throw new BadRequestException('Link a reviewed opportunity or project before marking qualified.');
  return this.write(r,'customer_inquiry.reviewed',async c=>{const old=await this.get(c,r,id,true);const due=b.due_at===undefined?old.due_at:b.due_at===null||b.due_at===''?null:new Date(String(b.due_at));if(due&&!Number.isFinite(due.getTime()))throw new BadRequestException('Use a valid follow-up date and time.');if(old.status===status&&old.follow_up_note===note&&old.owner_user_id===owner&&old.opportunity_id===opportunity&&old.project_id===project&&String(old.due_at)===String(due))return this.result(old,true);if(b.revision!==old.revision)throw new BadRequestException('This inquiry changed. Refresh and review the current version.');
   if(owner&&!(await c.query("SELECT 1 FROM tenant_users tu JOIN users u ON u.id=tu.user_id WHERE tu.tenant_id=$1 AND tu.user_id=$2 AND tu.status='active' AND tu.deleted_at IS NULL AND u.status='active' AND u.deleted_at IS NULL AND EXISTS(SELECT 1 FROM user_roles ur JOIN roles ar ON ar.id=ur.role_id AND ar.tenant_id=ur.tenant_id AND ar.deleted_at IS NULL JOIN role_permissions rp ON rp.role_id=ur.role_id AND rp.tenant_id=ur.tenant_id JOIN permissions perm ON perm.id=rp.permission_id WHERE ur.tenant_user_id=tu.id AND ur.tenant_id=tu.tenant_id AND ur.scope_type='tenant' AND perm.key='customer_inquiry.manage')",[r.auth.tenantId,owner])).rowCount)throw new BadRequestException('Owner unavailable in this organization.');
   for(const [table,value] of [['opportunities',opportunity],['projects',project]])if(value&&!(await c.query(`SELECT 1 FROM ${table} WHERE tenant_id=$1 AND id=$2 AND deleted_at IS NULL`,[r.auth.tenantId,value])).rowCount)throw new BadRequestException('Linked record unavailable in this organization.');
   const row=(await c.query('UPDATE customer_service_inquiries SET status=$3,follow_up_note=$4,owner_user_id=$5,opportunity_id=$6,project_id=$7,due_at=$8,revision=revision+1,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *',[r.auth.tenantId,id,status,note,owner,opportunity,project,due])).rows[0];if(owner&&owner!==old.owner_user_id&&!['closed','qualified'].includes(status))await c.query("INSERT INTO inquiry_follow_up_notifications(tenant_id,inquiry_id,recipient_user_id,kind,dedupe_key) VALUES($1,$2,$3,'assigned',$4) ON CONFLICT DO NOTHING",[r.auth.tenantId,id,owner,'assigned:'+id+':'+row.revision]);return {...this.result(row),beforeState:old};});}
 @Get(':id/files') @RequirePermission('customer_inquiry.read')
 async files(@Req() r:AuthenticatedRequest,@Param('id') id:string){uuid(id);return (await this.pool.query('SELECT id,file_name,mime_type,checksum,octet_length(content) AS size_bytes FROM customer_inquiry_files WHERE tenant_id=$1 AND inquiry_id=$2 ORDER BY created_at',[r.auth.tenantId,id])).rows;}
 @Post(':id/files') @RequirePermission('customer_inquiry.manage')
 async upload(@Req() r:AuthenticatedRequest,@Param('id') id:string,@Body() b:Record<string,unknown>){uuid(id);const name=sanitizeRestrictedFileName(str(b.file_name,'Filename',240)),encoded=String(b.content_base64??'');if(encoded.length>6990508||!/^[A-Za-z0-9+/]*={0,2}$/.test(encoded))throw new BadRequestException('Upload a supported file up to 5 MiB.');const content=Buffer.from(encoded,'base64');if(!content.length||content.length>5242880)throw new BadRequestException('Upload a file up to 5 MiB.');const mime=detectRestrictedFileMime(content);if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(mime))throw new BadRequestException('Supported originals: PDF, JPEG, PNG and WebP.');const checksum=calculateRestrictedFileSha256(content);
  return this.write(r,'customer_inquiry.file_attached',async c=>{await this.get(c,r,id,true);const prior=(await c.query('SELECT id,file_name,mime_type,checksum FROM customer_inquiry_files WHERE tenant_id=$1 AND inquiry_id=$2 AND checksum=$3',[r.auth.tenantId,id,checksum])).rows[0];if(prior)return {entityType:'customer_inquiry_file',entityId:prior.id,afterState:prior,skipEventAudit:true};const count=(await c.query('SELECT count(*)::int n FROM customer_inquiry_files WHERE tenant_id=$1 AND inquiry_id=$2',[r.auth.tenantId,id])).rows[0].n;if(count>=10)throw new BadRequestException('This inquiry already has ten attachments.');const row=(await c.query('INSERT INTO customer_inquiry_files(tenant_id,inquiry_id,file_name,mime_type,checksum,content,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,file_name,mime_type,checksum',[r.auth.tenantId,id,name,mime,checksum,content,r.auth.userId])).rows[0];return {entityType:'customer_inquiry_file',entityId:row.id,afterState:row};});}
 @Get('files/:fileId/download') @RequirePermission('customer_inquiry.read')
 async download(@Req() r:AuthenticatedRequest,@Param('fileId') fileId:string,@Res() res:Response){uuid(fileId);const file=(await this.pool.query('SELECT * FROM customer_inquiry_files WHERE tenant_id=$1 AND id=$2',[r.auth.tenantId,fileId])).rows[0];if(!file)throw new BadRequestException('Attachment unavailable.');res.setHeader('Content-Type',file.mime_type);res.setHeader('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(file.file_name)}`);res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cache-Control','no-store');res.send(file.content);}
 private async get(c:PoolClient,r:AuthenticatedRequest,id:string,lock=false){const row=(await c.query(`SELECT * FROM customer_service_inquiries WHERE tenant_id=$1 AND id=$2 ${lock?'FOR UPDATE':''}`,[r.auth.tenantId,id])).rows[0];if(!row)throw new BadRequestException('Inquiry unavailable.');return row;}
 private result(row:any,retry=false){return {entityType:'customer_inquiry',entityId:row.id,afterState:row,skipEventAudit:retry};}
 private async write(r:AuthenticatedRequest,event:string,write:(c:PoolClient)=>Promise<any>){const c=await this.pool.connect();try{return await executeWriteAction(c,{tenantId:r.auth.tenantId,actorUserId:r.auth.userId,action:event,aggregateType:'customer_inquiry',eventType:event,write});}finally{c.release();}}
}
