import {BadRequestException,Body,Controller,Get,Inject,Param,Post,Req,type OnModuleInit,type OnModuleDestroy} from '@nestjs/common';
import type {Pool,PoolClient} from 'pg';
import {executeWriteAction,type WriteActionResult} from '@syncos/shared';
import {DATABASE_POOL} from '../modules/database.module';
import {RequirePermission,TenantPermissionOnly} from '../security/require-permission.decorator';
import type {AuthenticatedRequest} from './intelligence.types';
import {invoicePackageFacts,packageHash} from './invoice-packages';
import {InvoicePackagesController} from './invoice-packages.controller';
import {approvedDeliveryEndpoint,transmitPrimePackage,validateDeliveryReceipt,type DeliveryReceipt} from './prime-delivery-transport';
const validId=(v:unknown)=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);
@Controller('prime-delivery')
export class PrimeDeliveryController implements OnModuleInit,OnModuleDestroy {
 private timer?:ReturnType<typeof setInterval>;private busy=false;
 constructor(@Inject(DATABASE_POOL) private readonly pool:Pool){}
 onModuleInit(){if(process.env.PRIME_DELIVERY_ENABLED==='true'){this.timer=setInterval(()=>{void this.processNext().catch(()=>{});},5000);this.timer.unref();}}
 onModuleDestroy(){if(this.timer)clearInterval(this.timer);}
 private async write(r:AuthenticatedRequest,action:string,fn:(c:PoolClient)=>Promise<WriteActionResult<any>>){const c=await this.pool.connect();try{return await executeWriteAction(c,{tenantId:r.auth.tenantId,actorUserId:r.auth.userId,action,aggregateType:'invoice',eventType:action,write:fn});}finally{c.release();}}
 @Get('invoices/:id') @RequirePermission('invoice.read') @TenantPermissionOnly()
 async read(@Req() r:AuthenticatedRequest,@Param('id') id:string){if(!validId(id))throw new BadRequestException('Choose an invoice');const invoice=(await this.pool.query('SELECT contract_id FROM commercial_terms_revisions WHERE tenant_id=$1 AND id=(SELECT commercial_terms_revision_id FROM invoices WHERE tenant_id=$1 AND id=$2 AND deleted_at IS NULL)',[r.auth.tenantId,id])).rows[0];return {enabled:process.env.PRIME_DELIVERY_ENABLED==='true',destinations:invoice?(await this.pool.query('SELECT id,name,recipient,enabled,approved_at FROM prime_delivery_destinations d WHERE tenant_id=$1 AND contract_id=$2 AND NOT EXISTS(SELECT 1 FROM prime_delivery_destination_revocations v WHERE v.destination_id=d.id) ORDER BY approved_at DESC',[r.auth.tenantId,invoice.contract_id])).rows:[],jobs:(await this.pool.query('SELECT id,package_id,status,event_type,attempts,receipt,last_error,created_at FROM prime_delivery_jobs WHERE tenant_id=$1 AND invoice_id=$2 ORDER BY created_at DESC',[r.auth.tenantId,id])).rows};}
 @Post('contracts/:id/destinations') @RequirePermission('contract.update') @TenantPermissionOnly()
 async destination(@Req() r:AuthenticatedRequest,@Param('id') id:string,@Body() b:Record<string,unknown>){if(!validId(id)||b.verified!==true)throw new BadRequestException('Verify the prime-approved destination');for(const key of ['name','endpoint','credential_env','recipient','source_reference'])if(typeof b[key]!=='string'||!b[key].trim()||b[key].length>2000)throw new BadRequestException('Complete destination and approval details');if(!/^PRIME_DELIVERY_TOKEN_[A-Z0-9_]+$/.test(String(b.credential_env)))throw new BadRequestException('Use an approved server credential reference');try{approvedDeliveryEndpoint(String(b.endpoint));}catch{throw new BadRequestException('Destination host must first be approved by the server operator');}
 return this.write(r,'prime_delivery.destination_approved',async c=>{const contract=(await c.query("SELECT id FROM contracts WHERE tenant_id=$1 AND id=$2 AND status='active' AND deleted_at IS NULL",[r.auth.tenantId,id])).rows[0];if(!contract)throw new BadRequestException('Active contract not found');const row=(await c.query('INSERT INTO prime_delivery_destinations(tenant_id,contract_id,name,endpoint,credential_env,recipient,source_reference,enabled,approved_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,name',[r.auth.tenantId,id,b.name,b.endpoint,b.credential_env,b.recipient,b.source_reference,b.enabled===true,r.auth.userId])).rows[0];return {entityType:'prime_delivery_destination',entityId:row.id,afterState:row};});}
 @Post('invoices/:id/queue') @RequirePermission('invoice.mark_sent') @TenantPermissionOnly()
 async queue(@Req() r:AuthenticatedRequest,@Param('id') id:string,@Body() b:Record<string,unknown>){if(![id,b.package_id,b.destination_id,b.client_mutation_id].every(validId))throw new BadRequestException('Choose a package and approved destination');return this.write(r,'prime_delivery.queued',async c=>{
  const facts=await invoicePackageFacts(c,r.auth.tenantId,id);
  const prior=(await c.query('SELECT * FROM prime_delivery_jobs WHERE tenant_id=$1 AND requested_by=$2 AND client_mutation_id=$3',[r.auth.tenantId,r.auth.userId,b.client_mutation_id])).rows[0];if(prior){if(prior.invoice_id!==id||prior.package_id!==b.package_id||prior.destination_id!==b.destination_id)throw new BadRequestException('Request identifier belongs to another delivery');return {entityType:'prime_delivery_job',entityId:prior.id,afterState:{id:prior.id,status:prior.status},skipEventAudit:true};}
  const destination=(await c.query('SELECT * FROM prime_delivery_destinations d WHERE tenant_id=$1 AND id=$2 AND contract_id=$3 AND enabled AND NOT EXISTS(SELECT 1 FROM prime_delivery_destination_revocations v WHERE v.destination_id=d.id)',[r.auth.tenantId,b.destination_id,facts.terms.contract_id])).rows[0];
  const packet=(await c.query('SELECT * FROM invoice_packages WHERE tenant_id=$1 AND id=$2 AND invoice_id=$3',[r.auth.tenantId,b.package_id,id])).rows[0];if(!destination||!packet||packet.source_fingerprint!==facts.source_fingerprint||packageHash(packet.archive_bytes)!==packet.archive_checksum)throw new BadRequestException('A current complete package and approved contract destination are required');
  const last=(await c.query('SELECT event_type FROM invoice_delivery_events WHERE tenant_id=$1 AND invoice_id=$2 ORDER BY event_sequence DESC LIMIT 1',[r.auth.tenantId,id])).rows[0];if(last&&last.event_type!=='rejected')throw new BadRequestException('This invoice is already delivered or accepted');
  if((await c.query("SELECT 1 FROM prime_delivery_jobs WHERE tenant_id=$1 AND invoice_id=$2 AND status IN ('queued','processing','review')",[r.auth.tenantId,id])).rows.length)throw new BadRequestException('Resolve the existing delivery before queuing another');
  const row=(await c.query('INSERT INTO prime_delivery_jobs(tenant_id,invoice_id,package_id,destination_id,requested_by,client_mutation_id,event_type) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,status',[r.auth.tenantId,id,b.package_id,b.destination_id,r.auth.userId,b.client_mutation_id,last?'resubmitted':'delivered'])).rows[0];return {entityType:'prime_delivery_job',entityId:row.id,afterState:row};
 });}
 @Post('jobs/:id/cancel') @RequirePermission('invoice.mark_sent') @TenantPermissionOnly()
 async cancel(@Req() r:AuthenticatedRequest,@Param('id') id:string,@Body() b:Record<string,unknown>){if(!validId(id)||typeof b.reason!=='string'||!b.reason.trim()||b.reason.length>2000)throw new BadRequestException('Explain why this delivery should be cancelled');return this.write(r,'prime_delivery.cancelled',async c=>{const row=(await c.query("UPDATE prime_delivery_jobs SET status='cancelled',last_error=$3,updated_at=now() WHERE tenant_id=$1 AND id=$2 AND status IN ('queued','failed') RETURNING id,status",[r.auth.tenantId,id,b.reason])).rows[0];if(!row)throw new BadRequestException('Only unsent queued or failed deliveries can be cancelled; uncertain deliveries require receipt review');return {entityType:'prime_delivery_job',entityId:row.id,afterState:row};});}
 @Post('destinations/:id/revoke') @RequirePermission('contract.update') @TenantPermissionOnly()
 async revoke(@Req() r:AuthenticatedRequest,@Param('id') id:string,@Body() b:Record<string,unknown>){if(!validId(id)||typeof b.reason!=='string'||!b.reason.trim()||b.reason.length>2000)throw new BadRequestException('Provide a revocation reason');return this.write(r,'prime_delivery.destination_revoked',async c=>{const d=(await c.query('SELECT id FROM prime_delivery_destinations WHERE tenant_id=$1 AND id=$2',[r.auth.tenantId,id])).rows[0];if(!d)throw new BadRequestException('Destination not found');await c.query('INSERT INTO prime_delivery_destination_revocations(tenant_id,destination_id,reason,revoked_by) VALUES($1,$2,$3,$4) ON CONFLICT(destination_id) DO NOTHING',[r.auth.tenantId,id,b.reason,r.auth.userId]);return {entityType:'prime_delivery_destination',entityId:id,afterState:{id,revoked:true,reason:b.reason}};});}
 @Post('jobs/:id/resolve') @RequirePermission('invoice.mark_sent') @TenantPermissionOnly()
 async resolve(@Req() r:AuthenticatedRequest,@Param('id') id:string,@Body() b:Record<string,unknown>){if(!validId(id)||b.verified!==true||!['not_delivered','delivery_recorded'].includes(String(b.resolution))||typeof b.proof_reference!=='string'||!b.proof_reference.trim()||b.proof_reference.length>2000)throw new BadRequestException('Verify the destination outcome and provide its proof reference');return this.write(r,'prime_delivery.review_resolved',async c=>{const job=(await c.query("SELECT * FROM prime_delivery_jobs WHERE tenant_id=$1 AND id=$2 AND status='review' FOR UPDATE",[r.auth.tenantId,id])).rows[0];if(!job)throw new BadRequestException('Choose an uncertain delivery');
  if(b.resolution==='delivery_recorded'){const event=(await c.query("SELECT id FROM invoice_delivery_events WHERE tenant_id=$1 AND invoice_id=$2 AND package_id=$3 AND event_type IN ('delivered','resubmitted') AND recorded_at>=$4 LIMIT 1",[r.auth.tenantId,job.invoice_id,job.package_id,job.created_at])).rows[0];if(!event)throw new BadRequestException('Record the verified delivery event for this package first');}
  const status=b.resolution==='delivery_recorded'?'delivered':'cancelled';await c.query('UPDATE prime_delivery_jobs SET status=$3,last_error=$4,updated_at=now() WHERE tenant_id=$1 AND id=$2',[r.auth.tenantId,id,status,'Reviewed: '+b.proof_reference]);return {entityType:'prime_delivery_job',entityId:id,afterState:{id,status,resolution:b.resolution,proof_reference:b.proof_reference}};
 });}
 async processNext(){if(this.busy||process.env.PRIME_DELIVERY_ENABLED!=='true')return;this.busy=true;let client:PoolClient|undefined,job:any;try{
  client=await this.pool.connect();await client.query("UPDATE prime_delivery_jobs SET status='review',last_error='Delivery interrupted; verify the destination receipt before resending',updated_at=now() WHERE status='processing' AND started_at<now()-interval '5 minutes'");
  await client.query('BEGIN');job=(await client.query("SELECT * FROM prime_delivery_jobs WHERE status='queued' AND next_attempt_at<=now() ORDER BY created_at LIMIT 1 FOR UPDATE SKIP LOCKED")).rows[0];if(!job){await client.query('COMMIT');return;}
  await client.query("UPDATE prime_delivery_jobs SET status='processing',attempts=attempts+1,started_at=now(),updated_at=now() WHERE id=$1",[job.id]);await client.query('COMMIT');client.release();client=undefined;
  let transmitted=false;try{
   const c=await this.pool.connect();let packet,destination;try{await c.query('BEGIN');
    const allowed=(await c.query(`SELECT 1 FROM users u JOIN tenant_users tu ON tu.user_id=u.id JOIN tenants t ON t.id=tu.tenant_id JOIN user_roles ur ON ur.tenant_user_id=tu.id AND ur.tenant_id=tu.tenant_id JOIN roles r ON r.id=ur.role_id AND r.tenant_id=tu.tenant_id JOIN role_permissions rp ON rp.role_id=r.id AND rp.tenant_id=r.tenant_id JOIN permissions p ON p.id=rp.permission_id WHERE u.id=$1 AND tu.tenant_id=$2 AND u.status='active' AND tu.status='active' AND t.status='active' AND u.deleted_at IS NULL AND tu.deleted_at IS NULL AND t.deleted_at IS NULL AND r.deleted_at IS NULL AND ur.scope_type='tenant' AND p.key='invoice.mark_sent' LIMIT 1`,[job.requested_by,job.tenant_id])).rows[0];if(!allowed)throw Error('Requester no longer has permission to deliver invoices');
    const facts=await invoicePackageFacts(c,job.tenant_id,job.invoice_id);packet=(await c.query('SELECT * FROM invoice_packages WHERE tenant_id=$1 AND id=$2',[job.tenant_id,job.package_id])).rows[0];destination=(await c.query('SELECT * FROM prime_delivery_destinations d WHERE tenant_id=$1 AND id=$2 AND enabled AND contract_id=$3 AND NOT EXISTS(SELECT 1 FROM prime_delivery_destination_revocations v WHERE v.destination_id=d.id)',[job.tenant_id,job.destination_id,facts.terms.contract_id])).rows[0];if(!destination||packet?.source_fingerprint!==facts.source_fingerprint||packageHash(packet.archive_bytes)!==packet.archive_checksum)throw Error('Package or approved destination changed');
    const last=(await c.query('SELECT event_type FROM invoice_delivery_events WHERE tenant_id=$1 AND invoice_id=$2 ORDER BY event_sequence DESC LIMIT 1',[job.tenant_id,job.invoice_id])).rows[0];if((job.event_type==='delivered'&&last)||(job.event_type==='resubmitted'&&last?.event_type!=='rejected'))throw Error('Invoice delivery state changed');await c.query('COMMIT');
   }catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}
   transmitted=true;const receipt=await this.transmit(destination,{id:job.id,checksum:packet.archive_checksum,bytes:packet.archive_bytes});validateDeliveryReceipt(receipt,packet.archive_checksum);
   await this.pool.query('UPDATE prime_delivery_jobs SET receipt=$2::jsonb,updated_at=now() WHERE id=$1',[job.id,JSON.stringify(receipt)]);
   await new InvoicePackagesController(this.pool).delivery({auth:{tenantId:job.tenant_id,userId:job.requested_by}} as AuthenticatedRequest,job.invoice_id,{package_id:job.package_id,event_type:job.event_type,occurred_at:receipt.received_at,recipient:destination.recipient,proof_reference:receipt.receipt_id,notes:'Verified automated package delivery receipt; customer acceptance remains separate.',verified:true,client_mutation_id:job.id});
   await this.finish(job,'delivered',null,receipt);
  }catch(e){const retryable=(e as {retryable?:boolean}).retryable===true;await this.finish(job,retryable&&job.attempts<4?'queued':transmitted?'review':'failed',retryable?'Provider rate limit; scheduled retry':transmitted?'Delivery not confirmed or local facts changed. Review the provider receipt before resending.':(e as Error).message);}
 }finally{if(client){await client.query('ROLLBACK');client.release();}this.busy=false;}}
 private async finish(job:any,status:string,error:string|null,receipt?:DeliveryReceipt){const c=await this.pool.connect();try{await c.query('BEGIN');await c.query('INSERT INTO prime_delivery_attempts(tenant_id,job_id,attempt,outcome,receipt) VALUES($1,$2,$3,$4,$5::jsonb) ON CONFLICT(job_id,attempt) DO NOTHING',[job.tenant_id,job.id,job.attempts+1,status,receipt?JSON.stringify(receipt):null]);await c.query("UPDATE prime_delivery_jobs SET status=$2,last_error=$3,next_attempt_at=now()+interval '1 minute',updated_at=now() WHERE id=$1",[job.id,status,error]);await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 protected transmit=transmitPrimePackage;
}
