"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useTenantCapability,PermissionLink} from '../access-control';
import {syncosFetch} from '../intelligence/api';
type Member={id:string;user_id:string;email:string;display_name:string;status:string};
type Grant={id:string;role_id:string;name:string;system_key:string;scope_type:string;organization_name:string|null};
type Role={id:string;name:string;system_key:string;permissions:string[]};
export default function AccessAdministration(){const canUsers=useTenantCapability('admin.manage_users'),canRoles=useTenantCapability('admin.manage_roles'),gate=useRef(false);const [members,setMembers]=useState<Member[]>([]),[next,setNext]=useState<string|null>(null),[query,setQuery]=useState(''),[selected,setSelected]=useState<{member:Member;grants:Grant[]}|null>(null),[roles,setRoles]=useState<Role[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(search='',after=''){const r=await syncosFetch<{items:Member[];next:string|null}>(`access-administration/members?search=${encodeURIComponent(search)}&after=${after}`);setMembers(r.items);setNext(r.next);}
 useEffect(()=>{if(canUsers)void load().catch(e=>setError(e.message));if(canRoles)void syncosFetch<{roles:Role[]}>('access-administration/roles').then(r=>setRoles(r.roles)).catch(e=>setError(e.message));},[canUsers,canRoles]);
 async function perform(fn:()=>Promise<void>){if(gate.current)return;gate.current=true;setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Access change failed.');}finally{setBusy(false);gate.current=false;}}
 async function choose(id:string){setSelected(await syncosFetch(`access-administration/members/${id}`));}
 function change(event:FormEvent<HTMLFormElement>,kind:'status'|'roles'){event.preventDefault();if(!selected)return;const body=Object.fromEntries(new FormData(event.currentTarget)),id=selected.member.id;void perform(async()=>{await syncosFetch(`access-administration/members/${id}/${kind}`,{method:'POST',body});await choose(id);await load(query);setMessage('Reviewed access change saved. The member must sign in again.');});}
 if(!canUsers)return null;
 return <main className="completion-workspace" style={{maxWidth:1000,margin:'auto',padding:24}}><h1>Workspace access</h1><p>Review existing members and approved role bundles. These controls change this workspace’s access; onboarding remains responsible for new users, crew assignments and partner relationships.</p><p><PermissionLink href="/identity-settings">Organization sign-in settings</PermissionLink></p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<form onSubmit={e=>{e.preventDefault();void perform(()=>load(query));}}><label>Find member<input value={query} onChange={e=>setQuery(e.target.value)} maxLength={100}/></label><button disabled={busy} style={{minHeight:44}}>Search members</button></form><ul>{members.map(m=><li key={m.id}><button disabled={busy} style={{minHeight:44}} onClick={()=>void perform(()=>choose(m.id))}>{m.display_name} · {m.email}</button> · {m.status}</li>)}</ul>{next&&<button disabled={busy} style={{minHeight:44}} onClick={()=>void perform(()=>load(query,next))}>Next members</button>}<button disabled={busy} style={{minHeight:44}} onClick={()=>void perform(()=>load(query))}>Back to first page</button>
 {selected&&<section className="workspace-panel" key={selected.member.id}><h2>{selected.member.display_name}</h2><p>{selected.member.email} · {selected.member.status}</p><form onSubmit={e=>change(e,'status')}><fieldset disabled={busy}><legend>Workspace membership</legend><label>Status<select name="status" defaultValue={selected.member.status==='disabled'?'disabled':'active'}><option value="active">Active</option><option value="disabled">Disabled</option></select></label><label>Reviewed reason<textarea name="reason" required minLength={5} maxLength={2000}/></label><button style={{minHeight:44}}>Save membership status</button></fieldset></form><h3>Current grants</h3><ul>{selected.grants.map(g=><li key={g.id}>{g.name} · {g.scope_type}{g.organization_name?' · '+g.organization_name:''}</li>)}</ul>
 {canRoles&&<form onSubmit={e=>change(e,'roles')}><fieldset disabled={busy}><legend>Approved internal role bundle</legend><label>Role<select required name="role_id" defaultValue=""><option value="">Choose role</option>{roles.filter(r=>!['partner_admin','partner_foreman','sync_foreman'].includes(r.system_key)).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Change<select name="operation"><option value="grant">Grant workspace role</option><option value="revoke">Revoke workspace role</option></select></label><label>Reviewed reason<textarea name="reason" required minLength={5} maxLength={2000}/></label><p>You cannot change your own access or grant powers beyond your own. At least one active workspace administrator must remain. Field and partner grants stay in workforce onboarding.</p><button style={{minHeight:44}}>Save role change</button></fieldset></form>}
 </section>}
 </main>;
}
