import {test,expect} from '@playwright/test';
async function setup(page:any,edit=true){await page.addInitScript(()=>localStorage.setItem('syncos.apiToken','synthetic-onboarding-token'));const permissions=['account_onboarding.read',...(edit?['account_onboarding.update']:[])];await page.route('**/api/syncos/auth/me', (r:any)=>r.fulfill({json:{user_id:'synthetic',tenant_id:'synthetic',roles:['system_admin'],permissions,tenant_permissions:permissions}}));}
test('onboarding edit requires confirmation, preserves failures and sends the reviewed revision',async({page})=>{
 await page.setViewportSize({width:390,height:844});await setup(page);let writes:any[]=[];let profile={id:'synthetic',organization_name:'Synthetic prime',lane:'prime',onboarding_stage:'identified',revision:'2026-10-06 12:00:00.000001+00',updated_at:'2026-10-06T12:00:00Z',required_documents:['Executed agreement'],missing_documents:['Executed agreement']};
 await page.route('**/api/syncos/account-onboarding/synthetic',r=>{if(r.request().method()==='PATCH'){writes.push(r.request().postDataJSON());if(writes.length===1)return r.fulfill({status:503,json:{message:'Temporary service failure'}});profile={...profile,...writes[1],revision:'new-revision',updated_at:'2026-10-06T12:01:00Z'};}return r.fulfill({json:profile});});
 await page.goto('/intelligence/account-onboarding/synthetic');await page.getByRole('combobox',{name:'Onboarding stage',exact:true}).selectOption('initial_outreach');await page.getByLabel('Next action',{exact:true}).fill('Call prime');await page.getByRole('button',{name:'Review changes'}).click();expect(writes).toHaveLength(0);await page.getByRole('button',{name:'Keep editing'}).click();await expect(page.getByLabel('Next action',{exact:true})).toHaveValue('Call prime');await page.getByRole('button',{name:'Review changes'}).click();await page.getByRole('button',{name:'Confirm tracking update'}).click();await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Temporary service failure');await page.getByRole('button',{name:'Confirm tracking update'}).click();await expect(page.getByRole('status').filter({hasText:'Onboarding tracking updated'})).toBeVisible();expect(writes[0]).toEqual(writes[1]);expect(writes[0].expected_revision).toBe('2026-10-06 12:00:00.000001+00');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('onboarding reader sees the profile without editing controls',async({page})=>{await setup(page,false);await page.route('**/api/syncos/account-onboarding/synthetic',r=>r.fulfill({json:{organization_name:'Synthetic prime',lane:'prime',onboarding_stage:'identified'}}));await page.goto('/intelligence/account-onboarding/synthetic');await expect(page.getByText('Read-only onboarding review.',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Review changes'})).toHaveCount(0);});
test('starting onboarding saves the chosen organization and lane only after review',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('syncos.apiToken','synthetic-onboarding-token'));const permissions=['account_onboarding.read','account_onboarding.create','account_onboarding.update','organization.read'];await page.route('**/api/syncos/auth/me',r=>r.fulfill({json:{user_id:'synthetic',tenant_id:'synthetic',roles:['system_admin'],permissions,tenant_permissions:permissions}}));await page.route('**/api/syncos/organizations/synthetic-org',r=>r.fulfill({json:{id:'synthetic-org',name:'Synthetic contractor'}}));const writes:any[]=[];await page.route('**/api/syncos/account-onboarding',r=>{writes.push(r.request().postDataJSON());return r.fulfill({status:201,json:{id:'saved-profile'}});});await page.route('**/api/syncos/account-onboarding/saved-profile',r=>r.fulfill({json:{id:'saved-profile',organization_name:'Synthetic contractor',lane:'contractor',onboarding_stage:'identified'}}));await page.goto('/intelligence/account-onboarding/new?organization_id=synthetic-org');await page.getByRole('combobox',{name:'Account lane',exact:true}).selectOption('contractor');await page.getByRole('button',{name:'Review changes'}).click();expect(writes).toHaveLength(0);await page.getByRole('button',{name:'Confirm tracking update'}).click();await expect(page).toHaveURL(/account-onboarding\/saved-profile$/);expect(writes).toHaveLength(1);expect(writes[0]).toMatchObject({organization_id:'synthetic-org',lane:'contractor',onboarding_stage:'identified'});
});
