import {test,expect} from '@playwright/test';
async function setup(page:any,manage=true){await page.addInitScript(()=>localStorage.setItem('syncos.apiToken','synthetic'));const permissions=['account_onboarding.read',...(manage?['account_onboarding.update']:[])];await page.route('**/api/syncos/auth/me',(r:any)=>r.fulfill({json:{user_id:'synthetic',tenant_id:'synthetic',roles:['system_admin'],permissions,tenant_permissions:permissions}}));await page.route('**/api/syncos/account-onboarding/profile',(r:any)=>r.fulfill({json:{id:'profile',organization_name:'Synthetic account',lane:'prime',onboarding_stage:'identified'}}));await page.route('**/api/syncos/account-programs/profiles/profile',(r:any)=>r.fulfill({json:[{id:'program',name:'Fiber program'}]}));}
const detail={program:{id:'program',name:'Fiber program'},originals:[{id:'original',file_name:'governing.pdf',size_bytes:200}],policies:[],reviews:[],requirements:[],active_policy_id:null,ready:false,boundary:'Document readiness only.'};
test('policy form preserves input on failure and requires source confirmation',async({page})=>{await setup(page);await page.setViewportSize({width:390,height:844});await page.route('**/api/syncos/account-programs/program',r=>r.fulfill({json:detail}));let writes:any[]=[];await page.route('**/api/syncos/account-programs/program/policies',r=>{writes.push(r.request().postDataJSON());return r.fulfill({status:409,json:{message:'Policy changed. Reload and review.'}});});await page.goto('/intelligence/account-onboarding/profile');await page.getByRole('combobox',{name:'Review program',exact:true}).selectOption('program');await page.getByText('Record a governing policy revision',{exact:true}).click();await page.getByRole('combobox',{name:'Governing original',exact:true}).selectOption('original');await page.getByLabel('Effective from',{exact:true}).fill('2026-01-01');await page.getByLabel('Required documents, one per line').fill('Insurance\nSafety training');await page.getByLabel('Policy approval reason').fill('Reviewed executed program requirements');await page.getByRole('button',{name:'Record policy revision',exact:true}).click();expect(writes).toHaveLength(0);await page.getByLabel('I checked these requirements', {exact:false}).check();await page.getByRole('button',{name:'Record policy revision',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Policy changed'})).toContainText('Policy changed');await expect(page.getByRole('alert').filter({hasText:'Policy changed'})).toBeFocused();await expect(page.getByLabel('Required documents, one per line')).toHaveValue('Insurance\nSafety training');expect(writes[0].requirements).toHaveLength(2);expect(writes[0].confirmed).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('read-only program review hides all mutation controls',async({page})=>{await setup(page,false);await page.route('**/api/syncos/account-programs/program',r=>r.fulfill({json:detail}));await page.goto('/intelligence/account-onboarding/profile');await page.getByRole('combobox',{name:'Review program',exact:true}).selectOption('program');await expect(page.getByRole('button',{name:'Download governing.pdf'})).toBeVisible();await expect(page.getByRole('button',{name:'Add program'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Preserve original'})).toHaveCount(0);await expect(page.getByText('Record a governing policy revision',{exact:true})).toHaveCount(0);});

test('stalled access checks fail closed and offer a safe retry',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('syncos.apiToken','synthetic'));
 let stalled=true;await page.route('**/api/syncos/auth/me',async r=>{if(stalled)return;const permissions=['account_onboarding.read'];await r.fulfill({json:{user_id:'synthetic',tenant_id:'synthetic',roles:[],permissions,tenant_permissions:permissions}});});
 await page.route('**/api/syncos/account-onboarding/profile',r=>r.fulfill({json:{id:'profile',organization_name:'Synthetic account',lane:'prime',onboarding_stage:'identified'}}));await page.route('**/api/syncos/account-programs/profiles/profile',r=>r.fulfill({json:[]}));
 await page.goto('/intelligence/account-onboarding/profile');await expect(page.getByRole('button',{name:'Add program'})).toHaveCount(0);await expect(page.getByRole('alert').filter({hasText:'Access verification timed out'})).toBeVisible({timeout:20000});
 stalled=false;await page.getByRole('button',{name:'Retry access check'}).click();await expect(page.getByRole('heading',{name:'Synthetic account'})).toBeVisible();await expect(page.getByRole('button',{name:'Add program'})).toHaveCount(0);
});

test('onboarding board includes accounts beyond its first page',async({page})=>{
 await setup(page,false);const rows=Array.from({length:201},(_,i)=>({id:`account-${i}`,name:`Synthetic account ${String(i).padStart(3,'0')}`,type:'customer',status:'discovered'}));const offsets:number[]=[];
 await page.route('**/api/syncos/**',r=>{const url=new URL(r.request().url()),path=url.pathname.split('/api/syncos/')[1];if(path==='auth/me')return r.fallback();if(path==='organizations'){const offset=Number(url.searchParams.get('offset')??0);offsets.push(offset);return r.fulfill({json:rows.slice(offset,offset+200)});}return r.fulfill({json:[]});});
 await page.goto('/intelligence/account-onboarding');await expect(page.getByText('Synthetic account 200',{exact:true})).toBeVisible();await expect(page.getByText('Synthetic account 200',{exact:true})).toHaveCount(1);expect([...new Set(offsets)].sort((a,b)=>a-b)).toEqual([0,200]);
});
