"use client";
import {useRef,useState} from 'react';
import {useCapability} from '../access-control';
import {syncosFetch} from '../intelligence/api';
type Row=Record<string,unknown>;
export function ProductionExports({reports=[],artifacts=[],mode='internal'}:{reports?:Row[];artifacts?:Row[];mode?:'internal'|'partner'|'foreman'}) {
 const generate=useCapability(mode==='partner'?'partner_production_export.generate':'production_export.generate')&&mode!=='foreman';
 const closeout=useCapability('production_closeout.generate')&&mode==='internal';
 const read=useCapability(mode==='partner'?'partner_production_export.read':mode==='foreman'?'partner_production_export.read_own':'production_export.read');
 const [report,setReport]=useState('');const [kind,setKind]=useState(generate?'daily_production_pdf':'production_closeout_package');const [created,setCreated]=useState<Row[]>([]);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const lock=useRef(false);
 const prefix=mode==='internal'?'syncfield':`syncfield/${mode}`;
 async function run(operation:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');try{await operation();}catch(e){setError(e instanceof Error?e.message:'Export failed. Please retry.');}finally{lock.current=false;setBusy(false);}}
 function create(){void run(async()=>{if(!report)throw new Error('Choose a submitted daily report.');const result=await syncosFetch<Row>(kind==='production_closeout_package'?'syncfield/production-closeout':`${prefix}/production-exports`,{method:'POST',body:{daily_report_id:report,artifact_type:kind,generation_mode:kind==='production_closeout_package'?'final_accepted_closeout':'customer_qc_status'}});setCreated(previous=>[result,...previous.filter(row=>row.id!==result.id)]);setMessage('Export generated. Download it below.');});}
 function download(row:Row){void run(async()=>{const file=await syncosFetch<{content_base64:string;mime_type:string;file_name:string}>(`${prefix}/production-exports/${encodeURIComponent(String(row.id))}/bytes`);const bytes=Uint8Array.from(atob(file.content_base64),char=>char.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:file.mime_type}));const a=document.createElement('a');a.href=url;a.download=file.file_name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Download ready.');});}
 const rows=[...created,...artifacts.filter(row=>!created.some(item=>item.id===row.id))];
 if(!generate&&!closeout&&!read)return null;
 return <section className="workspace-panel"><h2>Production exports and closeout</h2><p>Exports preserve the reported and customer-accepted quantities. A closeout package records the current status; it does not approve work or create financial records.</p>{error&&<p role="alert" className="error-banner">{error}</p>}{message&&<p role="status">{message}</p>}{(generate||closeout)&&<form className="stacked-form" onSubmit={e=>{e.preventDefault();create();}}><label className="form-field">Submitted daily report<select required disabled={busy} value={report} onChange={e=>setReport(e.target.value)}><option value="">Choose a report</option>{reports.map(row=><option key={String(row.id)} value={String(row.id)}>{String(row.work_order_number??row.project_name??'Report')} · {String(row.work_date??'')} · {String(row.crew_name??'')}</option>)}</select></label><label className="form-field">Export format<select disabled={busy} value={kind} onChange={e=>setKind(e.target.value)}>{generate&&<><option value="daily_production_pdf">Daily production PDF</option><option value="annotated_map_pdf">Annotated map PDF</option><option value="production_csv">Production CSV</option></>}{closeout&&<option value="production_closeout_package">Closeout status package</option>}</select></label><button className="operator-link" disabled={busy||!report||(!generate&&kind!=='production_closeout_package')}>{busy?'Working…':'Generate export'}</button></form>}{read&&<div className="record-list">{rows.map(row=><div className="record-list-row" key={String(row.id)}><span>{String(row.artifact_type??'Export').replaceAll('_',' ')} · {String(row.status??'ready')}{row.stale?' · Source has changed':''}</span><button className="operator-link" disabled={busy||row.status!=='ready'} onClick={()=>download(row)}>Download</button></div>)}{!rows.length&&<p>No exports generated yet.</p>}</div>}</section>;
}
