"use client";
import {CompanyDiscrepancies} from './discrepancies';
import {useEffect,useState,useRef} from 'react';
import {syncosFetch} from '../../intelligence/api';
import {useCapability,useVerifiedIdentity} from '../../access-control';
type Row=Record<string,any>;
export default function CompanyFieldOversight(){
 const identity=useVerifiedIdentity(),allowed=useCapability('partner_daily_production.read_org'),canDelegate=useCapability('partner_form.delegate'),canReport=useCapability('partner_inventory.report');const generation=useRef(0);
 const [data,setData]=useState<Row|null>(null),[assignment,setAssignment]=useState(''),[search,setSearch]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[destination,setDestination]=useState(''),[message,setMessage]=useState('');
 async function load(extra:Record<string,string>={},selected=assignment){const revision=++generation.current;setBusy(true);setError('');try{const q=new URLSearchParams({q:search,...(selected?{assignment_id:selected}:{}),...extra});const result=await syncosFetch<Row>('syncfield/partner/field-overview?'+q);if(revision===generation.current)setData(previous=>({...result,assignments:extra.before?[...new Map([...(previous?.assignments??[]),...result.assignments].map(a=>[a.id,a])).values()]:result.assignments}));}catch(e){if(revision===generation.current){setError((e as Error).message);setData(null);}}finally{if(revision===generation.current)setBusy(false);}}
 useEffect(()=>{if(identity&&allowed)void load();},[identity,allowed]);
 async function delegate(version:string){setBusy(true);setError('');try{await syncosFetch('syncfield/partner/delegate-form',{method:'POST',body:{source_assignment_id:assignment,assignment_id:destination,version_id:version}});setMessage('Form assigned. Each crew must provide its own answers; safety and approval responsibilities are unchanged.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!identity)return <main><p>Verifying access…</p></main>;if(!allowed)return <main><h1>Access unavailable</h1></main>;
 return <main className="completion-workspace" style={{maxWidth:960,margin:'auto',padding:20}}><a href="/partner">Back to company workspace</a><h1>Company field oversight</h1><p>Review your company’s assignment forms and crew material custody. Missing responses do not establish a safety or production approval.</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<form onSubmit={e=>{e.preventDefault();void load({},'');setAssignment('');}}><label>Search assignments<input value={search} maxLength={200} onChange={e=>setSearch(e.target.value)}/></label><button disabled={busy}>Search</button></form><label>Work assignment<select disabled={busy} value={assignment} onChange={e=>{setAssignment(e.target.value);void load({},e.target.value);}}><option value="">Choose assignment</option>{data?.assignments?.map((a:Row)=><option key={a.id} value={a.id}>{a.project_name} · {a.work_order_number} · {a.crew_name}{a.current?'':' · historical'}</option>)}</select></label>{data?.next&&<button disabled={busy} onClick={()=>void load({before:data.next})}>More assignments</button>}<button disabled={busy} onClick={()=>void load()}>Latest / refresh</button>
 {data?.assignment&&<><h2>Assigned forms and response coverage</h2>{data.forms.map((f:Row)=><section key={f.id}><h3>{f.schema.name} · version {f.version}</h3><p>{f.active?'Assigned':'Inactive'} · {f.submission_count} submitted responses{f.active&&!f.submission_count?' · awaiting a response':''}</p>{canDelegate&&f.active&&data.assignment.current&&<button disabled={busy||!destination} onClick={()=>void delegate(f.id)}>Assign this form to selected crew assignment</button>}</section>)}{canDelegate&&<label>Destination assignment for delegation<select disabled={busy} value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Choose your company’s assignment</option>{data.assignments.filter((a:Row)=>a.current&&a.assignment_status==='active').map((a:Row)=><option key={a.id} value={a.id}>{a.work_order_number} · {a.crew_name}</option>)}</select></label>}<h2>Submitted answers</h2>{data.records.map((r:Row)=><details key={r.id}><summary>{r.schema_snapshot.name} · {new Date(r.created_at).toLocaleString()}</summary>{Object.entries(r.answers).map(([key,value])=><p key={key}>{r.schema_snapshot.fields.find((f:Row)=>f.key===key)?.label??key}: {String(value)}</p>)}</details>)}{data.records_next&&<button disabled={busy} onClick={()=>void load({records_before:data.records_next})}>Older answers</button>}<h2>Crew material custody</h2>{data.balances.map((b:Row)=><p key={b.location_id+':'+b.lot_id}>{b.label} · {b.serial_number} · {b.location_label}: {b.balance} {b.unit}</p>)}<h2>Material movement history</h2>{data.movements.map((m:Row)=><details key={m.id}><summary>{m.label} · {m.kind} · {m.quantity} {m.unit}</summary><p>{m.reference}: {m.reason}</p><p>Work order reference: {m.work_order_id??'Custody movement'} · {new Date(m.created_at).toLocaleString()}</p></details>)}{data.movements_next&&<button disabled={busy} onClick={()=>void load({movements_before:data.movements_next})}>Older movements</button>}<CompanyDiscrepancies key={assignment} assignment={assignment} balances={data.balances} rows={data.discrepancies??[]} next={data.discrepancies_next} canReport={canReport} reload={()=>load()} older={cursor=>void load({discrepancies_before:cursor})}/></>}
 </main>;
}
