"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useTenantCapability} from '../../access-control';
import {syncosFetch,readToken,type SyncRecord} from '../api';
export function ProgramPolicies({profileId}:{profileId:string}){
 const errorBox=useRef<HTMLParagraphElement>(null),selectedRef=useRef(''),writeLock=useRef(false);
 const manage=useTenantCapability('account_onboarding.update');
 const [programs,setPrograms]=useState<SyncRecord[]>([]),[selected,setSelected]=useState(''),[data,setData]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function load(id=selected){const rows=await syncosFetch<SyncRecord[]>(`account-programs/profiles/${profileId}`);setPrograms(rows);if(id){const next=await syncosFetch(`account-programs/${id}`);if(selectedRef.current===id)setData(next);}}
 useEffect(()=>{if(error)errorBox.current?.focus();},[error]);
 useEffect(()=>{void load().catch(e=>setError(e.message));},[profileId]);
 useEffect(()=>{setData(null);if(selected)void load(selected).catch(e=>setError(e.message));},[selected]);
 async function action(work:()=>Promise<unknown>,message:string){if(writeLock.current)return;writeLock.current=true;setBusy(true);setError('');setNotice('');try{await work();await load();setNotice(message);}catch(e){setError(e instanceof Error?e.message:'Could not save. Your entries are preserved.');}finally{writeLock.current=false;setBusy(false);}}
 function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,name=new FormData(form).get('name');void action(async()=>{await syncosFetch(`account-programs/profiles/${profileId}`,{method:'POST',body:{name}});form.reset();},'Program created. Add the governing original and policy requirements.');}
 function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,file=new FormData(form).get('original') as File;void action(async()=>{if(!file?.size||file.size>10485760)throw new Error('Choose an original up to 10 MiB.');const encoded=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Could not read file. Choose it again.'));reader.readAsDataURL(file);});await syncosFetch(`account-programs/${selected}/originals`,{method:'POST',body:{file_name:file.name,content_base64:encoded}});form.reset();},'Original preserved. Uploading does not approve its contents.');}
 function policy(e:FormEvent<HTMLFormElement>){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));void action(()=>syncosFetch(`account-programs/${selected}/policies`,{method:'POST',body:{...values,confirmed:values.confirmed==='on',expected_revision:data.policies[0]?.revision??0,requirements:String(values.requirements).split('\n').map(s=>s.trim()).filter(Boolean).map((label,i)=>({key:`document-${i+1}`,label}))}}),'Policy revision recorded. Evidence must be reviewed against this revision.');}
 function review(e:FormEvent<HTMLFormElement>,requirement:any){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));void action(()=>syncosFetch(`account-programs/${selected}/reviews`,{method:'POST',body:{...values,confirmed:values.confirmed==='on',policy_id:data.active_policy_id,requirement_key:requirement.key,expected_review_id:requirement.review?.id??null}}),'Document review recorded in history.');}
 async function download(file:any){try{const response=await fetch(`/api/syncos/account-programs/${selected}/originals/${file.id}`,{headers:{authorization:`Bearer ${readToken()}`},cache:'no-store'});if(!response.ok)throw new Error('Could not retrieve the original. Check your access and try again.');const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=file.file_name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}}
 const originals=()=>data.originals.map((f:any)=><option key={f.id} value={f.id}>{f.file_name}</option>);
 return <section aria-labelledby="account-program-heading"><h2 id="account-program-heading">Program document requirements</h2><p>Preserve the governing original, record its requirements, then review each submitted original. Document readiness does not approve contracts, authorize work or release money. Dates use the UTC calendar.</p>{error&&<p ref={errorBox} tabIndex={-1} role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {manage&&<form onSubmit={create}><fieldset disabled={busy}><legend>Add an account program</legend><label>Program name<input name="name" required maxLength={160}/></label><button>Add program</button></fieldset></form>}
 <label>Review program<select value={selected} onChange={e=>{selectedRef.current=e.target.value;setSelected(e.target.value);}} disabled={busy}><option value="">Choose a program</option>{programs.map(p=><option key={String(p.id)} value={String(p.id)}>{String(p.name)}</option>)}</select></label>
 {data&&<><h3>{data.program.name}</h3><p role="status">{data.ready?'Document requirements satisfied':'Document requirements not satisfied'} — {data.boundary}</p>
 <h4>Preserved originals</h4>{data.originals.length?<ul>{data.originals.map((f:any)=><li key={f.id}><button onClick={()=>void download(f)}>Download {f.file_name}</button> ({f.size_bytes} bytes)</li>)}</ul>:<p>No originals uploaded.</p>}
 {manage&&<form onSubmit={upload}><fieldset disabled={busy}><legend>Add an original</legend><p>PDF, JPEG, PNG or WebP, up to 10 MiB. Identical retries reuse the original.</p><label>Original file<input type="file" name="original" required accept=".pdf,.jpg,.jpeg,.png,.webp"/></label><button>Preserve original</button></fieldset></form>}
 {manage&&<details><summary>Record a governing policy revision</summary><p>A new revision retains earlier policies and requires a fresh evidence review. Confirm the dates and requirements against the governing original.</p><form onSubmit={policy}><fieldset disabled={busy}><label>Governing original<select name="source_original_id" required defaultValue=""><option value="">Choose original</option>{originals()}</select></label><label>Effective from<input type="date" name="effective_from" required/></label><label>Effective until<input type="date" name="effective_until"/></label><label>Required documents, one per line<textarea name="requirements" required maxLength={24000}/></label><label>Policy approval reason<textarea name="reason" required maxLength={2000}/></label><label><input type="checkbox" name="confirmed" required/>I checked these requirements and dates against the governing original.</label><button>Record policy revision</button></fieldset></form></details>}
 {!data.active_policy_id&&<p>No current governing policy. Readiness remains unverified.</p>}
 {data.requirements.map((q:any)=><article key={data.active_policy_id+q.key}><h4>{q.label}: {q.state}</h4>{q.review&&<p>Last decision: {q.review.decision}. {q.review.reason}</p>}{manage&&<form onSubmit={e=>review(e,q)}><fieldset disabled={busy}><legend>Review {q.label}</legend><label>Evidence original<select name="original_id" required defaultValue=""><option value="">Choose original</option>{originals()}</select></label><label>Decision<select name="decision" defaultValue="submitted"><option value="submitted">Submitted, awaiting review</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></label><label>Document expires on<input type="date" name="expires_on"/></label><label>Review reason<textarea name="reason" required maxLength={2000}/></label><label><input type="checkbox" name="confirmed"/>I verified the original is readable and satisfies this requirement (required for approval).</label><button>Record document review</button></fieldset></form>}</article>)}
 <details><summary>Policy and review history</summary>{data.policies.map((p:any)=><div key={p.id}><h4>Revision {p.revision}</h4><p>{p.reason}</p><ul>{p.requirements.map((q:any)=><li key={q.key}>{q.label}</li>)}</ul></div>)}{data.reviews.map((r:any)=><p key={r.id}>{r.reviewed_at}: {r.requirement_key} — {r.decision}. {r.reason}</p>)}</details>
 </>}
 </section>;
}
