"use client";
import {useEffect,useState,type FormEvent} from 'react';
import {syncosFetch} from '../intelligence/api';
import {HistoryControls} from '../history-controls';
import {Panel} from '../dashboard-components';
type Channel={id:string;slug:string;label:string;privacy_notice:string;enabled:boolean;owner_user_id:string;escalation_user_id:string;follow_up_hours:number};
type Notification={id:string;subject:string;recipient_name:string;kind:string;status:string;attempts:number;last_error:string|null};
export function IntakeControls({owners}:{owners:{id:string;label:string}[]}){
 const [channels,setChannels]=useState<Channel[]>([]),[notifications,setNotifications]=useState<Notification[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Channel|null>(null),[query,setQuery]=useState(''),[more,setMore]=useState(false);
 async function load(){const [c,n]=await Promise.all([syncosFetch<Channel[]>('customer-intake-channels'),syncosFetch<Notification[]>('customer-inquiry-notifications')]);setChannels(c);setNotifications(n);setMore(n.length===200);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function history(q:string,older=false){if(busy)return;setBusy(true);setError('');try{const params=new URLSearchParams({q});if(older&&notifications.length)params.set('before',notifications[notifications.length-1].id);const rows=await syncosFetch<Notification[]>(`customer-inquiry-notifications?${params}`);setNotifications(old=>older?[...old,...rows]:rows);setMore(rows.length===200);setQuery(q);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const b=Object.fromEntries(new FormData(e.currentTarget));try{await syncosFetch('customer-intake-channels',{method:'POST',body:{...b,enabled:b.enabled==='on',follow_up_hours:Number(b.follow_up_hours)}});setMessage('Channel configuration saved.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><Panel title="Public request channels">{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<p>Enabling a channel makes its request form public. Choose authorized owners and review the privacy notice before sharing the link.</p>{channels.map(c=><p key={c.id}><button onClick={()=>setSelected(c)} disabled={busy}>Edit {c.label}</button> · {c.enabled?'Enabled':'Disabled'} · <a href={`/request-service/${c.slug}`}>Open request form</a></p>)}<button disabled={busy} onClick={()=>setSelected(null)}>New channel</button><form key={selected?.id??'new'} onSubmit={save}><fieldset disabled={busy}><label>Channel address<input name="slug" required pattern="[a-z0-9][a-z0-9-]{7,79}" maxLength={80} defaultValue={selected?.slug} readOnly={!!selected}/></label><p>8–80 lowercase letters, numbers or hyphens. This address is public.</p><label>Customer-facing title<input name="label" required maxLength={200} defaultValue={selected?.label}/></label><label>Privacy and handling notice<textarea name="privacy_notice" required maxLength={4000} defaultValue={selected?.privacy_notice}/></label>{[['owner_user_id','Follow-up owner'],['escalation_user_id','Overdue escalation owner']].map(([name,label])=><label key={name}>{label}<select name={name} required defaultValue={selected?.[name as 'owner_user_id'|'escalation_user_id']??''}><option value="">Choose an authorized owner</option>{owners.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>)}<label>Follow-up deadline (elapsed hours)<input name="follow_up_hours" type="number" min={1} max={720} required defaultValue={selected?.follow_up_hours??24}/></label><label><input type="checkbox" name="enabled" defaultChecked={selected?.enabled??false}/> Enable public submissions</label><button>{busy?'Saving…':'Save channel'}</button></fieldset></form></Panel><Panel title="Inquiry notification delivery"><HistoryControls label="notifications" busy={busy} more={more} onSearch={q=>void history(q)} onMore={()=>void history(query,true)}/><p>Queued notices remain pending until delivery is configured. Sent means the provider accepted the message; it does not prove the recipient read it. Email retries may repeat a message after an uncertain provider response.</p><button disabled={busy} onClick={()=>void load().catch(e=>setError(e.message))}>Refresh delivery status</button>{notifications.map(n=><div key={n.id}><p>{n.subject} · {n.recipient_name} · {n.kind} · {n.status} · {n.attempts} attempt(s)</p>{n.last_error&&<p>{n.last_error}</p>}{n.status==='failed'&&<button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await syncosFetch(`customer-inquiry-notifications/${n.id}/retry`,{method:'POST',body:{}});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Retry failed notification</button>}</div>)}</Panel></>;
}
