"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {CommandShell,Panel} from '../dashboard-components';
import {useCapability} from '../access-control';
import {syncosFetch,readToken} from '../intelligence/api';
type Choice={id:string;label:string};
type Inquiry={id:string;customer_name:string;email:string;subject:string;details:string;status:string;owner_user_id:string|null;opportunity_id:string|null;project_id:string|null;follow_up_note:string;revision:number;possible_duplicates:number};
type Attachment={id:string;file_name:string;size_bytes:number};
function Choose({name,label,rows,value}:{name:string;label:string;rows:Choice[];value?:string|null}){return <label>{label}<select name={name} defaultValue={value??''}><option value="">Not selected</option>{rows.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></label>;}
export default function CustomerInquiries(){
 const manage=useCapability('customer_inquiry.manage');
 const [data,setData]=useState<{inquiries:Inquiry[];owners:Choice[];opportunities:Choice[];projects:Choice[]}>({inquiries:[],owners:[],opportunities:[],projects:[]});
 const [files,setFiles]=useState<Record<string,Attachment[]>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const key=useRef(''),gate=useRef(false),errorRef=useRef<HTMLDivElement>(null);
 async function load(){setData(await syncosFetch('customer-inquiries'));}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);useEffect(()=>{if(error)errorRef.current?.focus();},[error]);
 async function action(fn:()=>Promise<unknown>,message:string){if(gate.current)return;gate.current=true;setBusy(true);setError('');setMessage('');try{await fn();setMessage(message);await load();}catch(e){setError((e as Error).message+' Your entries are preserved.');}finally{gate.current=false;setBusy(false);}}
 function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=Object.fromEntries(new FormData(form));if(!key.current)key.current=crypto.randomUUID();void action(async()=>{await syncosFetch('customer-inquiries',{method:'POST',body:{...f,authorized:f.authorized==='on',request_key:key.current}});key.current='';form.reset();},'Inquiry recorded. Assign an owner and review possible duplicates.');}
 async function loadFiles(id:string){setFiles(old=>({...old,[id]:[]}));const rows=await syncosFetch<Attachment[]>(`customer-inquiries/${id}/files`);setFiles(old=>({...old,[id]:rows}));}
 async function download(file:Attachment){await action(async()=>{const r=await fetch(`/api/syncos/customer-inquiries/files/${file.id}/download`,{headers:{authorization:`Bearer ${readToken()}`},cache:'no-store'});if(!r.ok)throw new Error('Attachment could not be downloaded.');const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file.file_name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'Attachment downloaded.');}
 return <div className="completion-workspace"><CommandShell title="Customer service inquiries" purpose="Record authorized customer requests, assign follow-up and link reviewed work. An inquiry never authorizes field work or commercial terms.">
 {error&&<div role="alert" ref={errorRef} tabIndex={-1}>{error}<button disabled={busy} onClick={()=>void action(load,'Queue refreshed.')}>Refresh queue</button></div>}{message&&<p role="status">{message}</p>}
 {manage&&<Panel title="Record a customer request"><form onSubmit={create} onChange={()=>{key.current='';}}><fieldset disabled={busy}><label>Customer name<input name="customer_name" required maxLength={1000}/></label><label>Contact email<input name="email" type="email" required maxLength={254}/></label><label>Subject<input name="subject" required maxLength={240}/></label><label>Request details<textarea name="details" required maxLength={10000}/></label><label>Source and permission to process<input name="source_reference" required maxLength={1000}/></label><label><input name="authorized" type="checkbox" required/> This request is authorized for processing by Sync.</label><button>{busy?'Saving…':'Record inquiry'}</button></fieldset></form></Panel>}
 <Panel title="Follow-up queue"><p>Most recent 200 inquiries. Possible duplicate matches use contact email and subject; review them before creating downstream work.</p>{data.inquiries.map(i=><details key={i.id}><summary>{i.subject} · {i.customer_name} · {i.status.replaceAll('_',' ')}{i.possible_duplicates?` · ${i.possible_duplicates} possible duplicate(s)`:''}</summary><p>{i.email}</p><p style={{whiteSpace:'pre-wrap'}}>{i.details}</p><p>Latest follow-up: {i.follow_up_note||'Not recorded'}</p>
 {manage&&<form key={i.revision} onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));void action(()=>syncosFetch(`customer-inquiries/${i.id}/review`,{method:'POST',body:{...f,revision:i.revision}}),'Follow-up saved. No message was sent to the customer.');}}><fieldset disabled={busy}><Choose name="owner_user_id" label="Follow-up owner" rows={data.owners} value={i.owner_user_id}/><label>Status<select name="status" defaultValue={i.status}>{['new','assigned','awaiting_customer','qualified','closed'].map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label><Choose name="opportunity_id" label="Reviewed opportunity" rows={data.opportunities} value={i.opportunity_id}/><Choose name="project_id" label="Reviewed project" rows={data.projects} value={i.project_id}/><label>Follow-up, acknowledgment evidence or closure note<textarea name="follow_up_note" required maxLength={4000} defaultValue={i.follow_up_note}/></label><button>Save follow-up</button></fieldset></form>}
 <button disabled={busy} onClick={()=>void action(()=>loadFiles(i.id),'Attachments loaded.')}>View attachments</button>{files[i.id]?.map(f=><p key={f.id}><button disabled={busy} onClick={()=>void download(f)}>{f.file_name} ({Math.ceil(f.size_bytes/1024)} KB)</button></p>)}
 {manage&&<form onSubmit={e=>{e.preventDefault();const form=e.currentTarget,file=new FormData(form).get('file') as File;void action(async()=>{if(!file?.size||file.size>5242880)throw new Error('Choose an original file up to 5 MiB.');const encoded=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('The file could not be read.'));reader.readAsDataURL(file);});await syncosFetch(`customer-inquiries/${i.id}/files`,{method:'POST',body:{file_name:file.name,content_base64:encoded}});form.reset();await loadFiles(i.id);},'Original attachment saved. Identical file retries are not duplicated.');}}><fieldset disabled={busy}><label>Original attachment<input name="file" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" required/></label><p>PDF, JPEG, PNG or WebP; up to 5 MiB each and ten files per inquiry.</p><button>Attach original</button></fieldset></form>}
 </details>)}</Panel></CommandShell></div>;
}
