"use client";
import {useEffect,useState,type FormEvent} from 'react';
import {Capability,useCapability} from '../access-control';
import {readToken,syncosFetch} from '../intelligence/api';
import {PrimeDelivery} from "./prime-delivery";
import {FinanceAction} from './financial-workflow';
type State={invoice:{id:string;invoice_number:string;due_date:string|null};terms:{contract_id:string;payment_days:number;payment_trigger:string}|null;policy:{required_documents:string[]}|null;packages:Array<{id:string;revision_number:number;archive_checksum:string}>;events:Array<{id:string;event_type:string;occurred_at:string;proof_reference:string}>;documents:Array<{id:string;document_kind:string;file_name:string}>};
export function InvoicePackages({initialInvoiceId=''}:{initialInvoiceId?:string}={}){
 const canRead=useCapability('invoice.read');const [invoices,setInvoices]=useState<Array<{id:string;label:string}>>([]),[id,setId]=useState(initialInvoiceId),[state,setState]=useState<State|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
 const refresh=()=>setRevision(v=>v+1);
 useEffect(()=>{if(!canRead)return;let alive=true;syncosFetch<{invoices:typeof invoices}>('invoice-packages/choices').then(v=>{if(alive)setInvoices(v.invoices);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[canRead,revision]);
 useEffect(()=>{setState(null);if(!id)return;let alive=true;setLoading(true);syncosFetch<State>(`invoice-packages/invoices/${id}`).then(v=>{if(alive){setState(v);setError('');}}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[id,revision]);
 async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setError('');const form=event.currentTarget;try{const data=new FormData(form),file=data.get('file') as File;if(file.size>20*1024*1024)throw new Error('Choose a PDF no larger than 20 MiB.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));await syncosFetch(`invoice-packages/invoices/${id}/documents`,{method:'POST',body:{document_kind:data.get('document_kind'),file_name:file.name,content_base64:btoa(binary),verified:data.get('verified')==='on'}});form.reset();refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function download(packet:string){setBusy(true);setError('');try{const res=await fetch(`/api/syncos/invoice-packages/${packet}/download`,{headers:{authorization:`Bearer ${readToken()}`}});if(!res.ok)throw new Error('Package download failed. Refresh and try again.');const url=URL.createObjectURL(await res.blob()),a=document.createElement('a');a.href=url;a.download=`invoice-package-${packet}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!canRead)return null;
 const last=state?.events.at(-1)?.event_type;const next=last==='rejected'?'resubmitted':'delivered';
 const eventFields=<><label>Package<select name="package_id" required defaultValue=""><option value="">Select the package sent to the customer</option>{state?.packages.map(p=><option value={p.id} key={p.id}>Revision {p.revision_number}</option>)}</select></label><label>Actual event time, including UTC offset<input name="occurred_at" placeholder="2026-09-30T14:30:00-04:00" required/></label><label>Customer recipient<input name="recipient" required maxLength={2000}/></label><label>Receipt or customer-response reference<input name="proof_reference" required maxLength={2000}/></label><label>Event notes<textarea name="notes" required maxLength={2000}/></label><label><input name="verified" type="checkbox" required/> I verified this event against the customer receipt or response.</label></>;
 return <section className="workspace-panel"><h2>Invoice packages and customer responses</h2><p>Prepare the prime’s required documents, download the package, and record actual delivery and customer responses. Manual delivery records do not send a package. Automatic sending has separate approved destinations and status controls below.</p><label>Invoice<select aria-label="Invoice package selection" value={id} disabled={busy} onChange={e=>setId(e.target.value)} style={{minHeight:44}}><option value="">Choose an invoice</option>{invoices.map(i=><option value={i.id} key={i.id}>{i.label}</option>)}</select></label><button type="button" disabled={busy||loading} onClick={refresh}>Refresh package history</button>{loading&&<p role="status">Loading invoice package history…</p>}{error&&<p role="alert">{error}</p>}
 {state&&<div key={id}><p>Payment due: {state.invoice.due_date?String(state.invoice.due_date).slice(0,10):'Awaiting the approved contract trigger'}</p>
 {state.terms?<FinanceAction permission="contract.update" title="Review prime package requirements" prefix="invoice-packages" endpoint={`contracts/${state.terms.contract_id}/requirements`} submitLabel="Approve package requirements" onSaved={refresh} transform={f=>({...f,required_documents:f.required_documents.split('\n').map(s=>s.trim()).filter(Boolean),verified:f.verified==='on'})}><label>Additional required documents, one per line<textarea name="required_documents" defaultValue={state.policy?.required_documents.join('\n')??''}/></label><p>The invoice, accepted-work record and selected original evidence are always included. Leave this list empty only if the prime requires no additional documents.</p><label>Prime requirements source<input name="source_reference" required maxLength={2000}/></label><label><input name="verified" type="checkbox" required/> I checked these requirements against the prime’s instructions.</label></FinanceAction>:<p>Reconcile this invoice with approved agreement pricing before preparing its package.</p>}
 {!!state.policy?.required_documents.length&&<Capability permission="invoice.update"><details className="workspace-panel"><summary>Attach reviewed billing document</summary><form onSubmit={upload}><fieldset disabled={busy} style={{border:0}}><label>Required document type<select name="document_kind" required defaultValue=""><option value="">Select requirement</option>{state.policy?.required_documents.map(d=><option key={d}>{d}</option>)}</select></label><label>Original PDF (up to 20 MiB)<input name="file" type="file" accept="application/pdf" required/></label><label><input name="verified" type="checkbox" required/> I opened this original and verified it is readable and complete.</label><button style={{minHeight:44}} disabled={busy}>{busy?'Uploading…':'Attach reviewed document'}</button></fieldset></form></details></Capability>}
 <ul>{state.documents.map(d=><li key={d.id}>{d.document_kind}: {d.file_name}</li>)}</ul>
 {state.terms&&state.policy&&<FinanceAction permission="invoice.update" title="Prepare complete invoice package" prefix="invoice-packages" endpoint={`invoices/${id}/prepare`} submitLabel="Prepare package" onSaved={refresh}><p>SyncOS verifies current accepted work, approved pricing, required documents and original-file checksums. Preparation does not record delivery.</p></FinanceAction>}
 <ul>{state.packages.map(p=><li key={p.id}>Package revision {p.revision_number} <button type="button" disabled={busy} onClick={()=>download(p.id)}>Download revision {p.revision_number}</button></li>)}</ul><p>Earlier revisions remain available for audit. Delivery is allowed only for a complete package matching current invoice facts.</p>
 {state.packages.length>0&&(!last||last==='rejected')&&<FinanceAction permission="invoice.mark_sent" title={last?'Record resubmission':'Record customer delivery'} prefix="invoice-packages" endpoint={`invoices/${id}/delivery`} submitLabel={last?'Record resubmission':'Record delivery'} onSaved={refresh} transform={f=>({...f,event_type:next,verified:f.verified==='on'})}>{eventFields}</FinanceAction>}
 {['delivered','resubmitted'].includes(last??'')&&<><FinanceAction permission="invoice.mark_sent" title="Record customer rejection" prefix="invoice-packages" endpoint={`invoices/${id}/delivery`} submitLabel="Record rejection" onSaved={refresh} transform={f=>({...f,event_type:'rejected',verified:f.verified==='on'})}>{eventFields}</FinanceAction><FinanceAction permission="invoice.approve" title="Record customer invoice acceptance" prefix="invoice-packages" endpoint={`invoices/${id}/acceptance`} submitLabel="Record invoice acceptance" onSaved={refresh} transform={f=>({...f,verified:f.verified==='on'})}>{eventFields}</FinanceAction></>}
 {state.terms&&<PrimeDelivery invoiceId={id} contractId={state.terms.contract_id} packages={state.packages} onSaved={refresh}/>}
 <h3>Delivery and acceptance history</h3>{state.events.length?<ol>{state.events.map(e=><li key={e.id}>{e.event_type} · {new Date(e.occurred_at).toLocaleString()} · {e.proof_reference}</li>)}</ol>:<p>No customer delivery has been recorded.</p>}</div>}
 </section>;
}
