"use client";
import {useEffect,useState} from 'react';
import {FinanceAction} from './financial-workflow';
import {syncosFetch} from '../intelligence/api';
type State={enabled:boolean;destinations:{id:string;name:string;recipient:string;enabled:boolean}[];jobs:{id:string;status:string;attempts:number;receipt:{receipt_id:string}|null;last_error:string|null}[]};
export function PrimeDelivery({invoiceId,contractId,packages,onSaved}:{invoiceId:string;contractId:string;packages:{id:string;revision_number:number}[];onSaved:()=>void}){const [state,setState]=useState<State|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0);const refresh=()=>{setRevision(v=>v+1);onSaved();};useEffect(()=>{let alive=true;syncosFetch<State>(`prime-delivery/invoices/${invoiceId}`).then(r=>{if(alive){setState(r);setError('');}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[invoiceId,revision]);
 return <section className="workspace-panel"><h3>Automatic package delivery</h3><p>{state?.enabled?'Approved queued packages are sent by the delivery service.':'Automatic sending is disabled. You can prepare approved destinations and queue packages; no delivery starts until the server operator enables it.'} A delivery receipt never records customer acceptance.</p>{error&&<p role="alert">{error}</p>}<button onClick={()=>setRevision(v=>v+1)} style={{minHeight:44}}>Refresh delivery status</button>
 <FinanceAction permission="contract.update" title="Approve delivery destination" prefix="prime-delivery" endpoint={`contracts/${contractId}/destinations`} submitLabel="Save approved destination" onSaved={refresh} transform={f=>({...f,verified:f.verified==='on',enabled:f.enabled==='on'})}><label>Destination name<input name="name" required maxLength={2000}/></label><label>Prime-approved HTTPS endpoint<input name="endpoint" type="url" required maxLength={2000}/></label><label>Server credential reference<input name="credential_env" required pattern="PRIME_DELIVERY_TOKEN_[A-Z0-9_]+" placeholder="PRIME_DELIVERY_TOKEN_PRIME"/></label><label>Recipient<input name="recipient" required maxLength={2000}/></label><label>Approval source reference<input name="source_reference" required maxLength={2000}/></label><label><input name="enabled" type="checkbox"/> Allow this approved destination to receive packages</label><label><input name="verified" type="checkbox" required/> I verified the prime’s destination and receipt contract.</label><p>Enter the credential reference supplied by the server operator, never a password or token. Only approved hosts are allowed.</p></FinanceAction>
 {state?.destinations.filter(d=>d.enabled).length&&packages.length?<FinanceAction permission="invoice.mark_sent" title="Queue complete package" prefix="prime-delivery" endpoint={`invoices/${invoiceId}/queue`} submitLabel="Queue package delivery" onSaved={refresh}><label>Package<select name="package_id" required defaultValue=""><option value="">Choose current package</option>{packages.map(p=><option key={p.id} value={p.id}>Revision {p.revision_number}</option>)}</select></label><label>Approved destination<select name="destination_id" required defaultValue=""><option value="">Choose destination</option>{state.destinations.filter(d=>d.enabled).map(d=><option key={d.id} value={d.id}>{d.name} · {d.recipient}</option>)}</select></label><p>The service rechecks completeness and your permission before sending. Only one unresolved delivery is allowed per invoice.</p></FinanceAction>:null}
 {state?.destinations.map(d=><FinanceAction key={d.id} permission="contract.update" title={`Revoke destination: ${d.name}`} prefix="prime-delivery" endpoint={`destinations/${d.id}/revoke`} submitLabel="Revoke destination" onSaved={refresh}><label>Reason<textarea name="reason" required maxLength={2000}/></label><p>Queued deliveries will fail their destination check. Already transmitted packages cannot be recalled.</p></FinanceAction>)}
 <h4>Delivery attempts</h4>{state?.jobs.length?<ul>{state.jobs.map(j=><li key={j.id}><p>{j.status} · {j.attempts} attempts{j.receipt?' · Receipt '+j.receipt.receipt_id:''}</p>{j.last_error&&<p>{j.last_error}</p>}{['queued','failed'].includes(j.status)&&<FinanceAction permission="invoice.mark_sent" title="Cancel unsent delivery" prefix="prime-delivery" endpoint={`jobs/${j.id}/cancel`} submitLabel="Cancel delivery" onSaved={refresh}><label>Reason<textarea name="reason" required maxLength={2000}/></label></FinanceAction>}{j.status==='review'&&<FinanceAction permission="invoice.mark_sent" title="Resolve uncertain delivery" prefix="prime-delivery" endpoint={`jobs/${j.id}/resolve`} submitLabel="Save reviewed outcome" onSaved={refresh} transform={f=>({...f,verified:f.verified==='on'})}><label>Verified result<select name="resolution" required><option value="not_delivered">Prime confirms package was not delivered</option><option value="delivery_recorded">Verified delivery already recorded in package history</option></select></label><label>Prime receipt or confirmation reference<input name="proof_reference" required maxLength={2000}/></label><label><input name="verified" type="checkbox" required/> I checked the actual destination outcome before allowing further action.</label></FinanceAction>}</li>)}</ul>:<p>No automated deliveries queued.</p>}
 </section>;
}
