"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { CommandShell } from "../dashboard-components";
import { PermissionLink, useCapability } from "../access-control";
import { syncosFetch, type SyncRecord } from "../intelligence/api";

type Detail = { project_handoff: SyncRecord; checklist_items: SyncRecord[]; risks: SyncRecord[]; warnings: SyncRecord[]; blockers: SyncRecord[]; required_override_fields: string[]; recommended_next_action?: string };
type Options = { sources: SyncRecord[]; staff: SyncRecord[] };
type Input = { name: string; label: string; required?: boolean; options?: Array<[string,string]>; type?: string; value?: unknown };
function Form({ title, fields, submit }: { title: string; fields: Input[]; submit: (body: SyncRecord) => Promise<void> }) {
 const lock=useRef(false); const [busy,setBusy]=useState(false); const [error,setError]=useState("");const [saved,setSaved]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError("");setSaved(false);try{const values=new FormData(e.currentTarget);const body:SyncRecord={};for(const field of fields){const value=values.get(field.name);if(field.type==='checkbox')body[field.name]=Boolean(value);else if(typeof value==='string'&&value.trim())body[field.name]=value.trim();}await submit(body);setSaved(true);}catch(reason){setError(reason instanceof Error?reason.message:'Save failed. Entries retained.');}finally{lock.current=false;setBusy(false);}}
 return <details className="workspace-panel"><summary style={{minHeight:44,cursor:'pointer'}}>{title}</summary><form onSubmit={save} aria-label={title}><fieldset disabled={busy||saved} style={{border:0,display:'grid',gap:12,gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,240px),1fr))'}}>{fields.map(field=><label key={field.name} style={{display:'grid',gap:6}}>{field.label}{field.required?' *':''}{field.options?<select name={field.name} defaultValue={String(field.value??'')} required={field.required} style={{minHeight:44}}><option value="">Choose…</option>{field.options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:<input name={field.name} required={field.required} type={field.type??'text'} defaultValue={field.type==='checkbox'?undefined:String(field.value??'')} defaultChecked={field.type==='checkbox'?Boolean(field.value):undefined} style={{minHeight:44,minWidth:0}}/>}</label>)}</fieldset>{error&&<p role="alert">{error}</p>}{saved&&<p role="status">Saved. The current readiness and approval gates still apply.</p>}<button type="submit" disabled={busy||saved}>{busy?'Saving…':title}</button>{saved&&<button type="button" onClick={()=>setSaved(false)}>Enter another update</button>}</form></details>;
}
const text=(name:string,label:string,required=false):Input=>({name,label,required});
export default function ProjectHandoffsPage(){
 const canRead=useCapability('project_handoff.read');const canCreate=useCapability('project_handoff.create');const canUpdate=useCapability('project_handoff.update');const canRecalculate=useCapability('project_handoff.recalculate');const canSubmit=useCapability('project_handoff.submit_review');const canApprove=useCapability('project_handoff.approve');const canReject=useCapability('project_handoff.reject');const canCreateProject=useCapability('project_handoff.create_project');const canProject=useCapability('project.create');const canChecklist=useCapability('project_handoff_checklist.complete');const canRisk=useCapability('project_handoff_risk.create');const canResolve=useCapability('project_handoff_risk.resolve');
 const [rows,setRows]=useState<SyncRecord[]>([]);const [options,setOptions]=useState<Options>({sources:[],staff:[]});const [detail,setDetail]=useState<Detail|null>(null);const [selected,setSelected]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(true);const openSequence=useRef(0);
 async function load(){const [list,choices]=await Promise.all([syncosFetch<SyncRecord[]>('project-handoffs'),syncosFetch<Options>('project-handoffs/options')]);setRows(list);setOptions(choices);}
 useEffect(()=>{if(!canRead)return;setLoading(true);void load().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[canRead]);
 async function open(id:string){const sequence=++openSequence.current;setSelected(id);setDetail(null);setError('');if(!id)return;try{const value=await syncosFetch<Detail>(`project-handoffs/${id}/detail`);if(sequence===openSequence.current)setDetail(value);}catch(e){if(sequence===openSequence.current)setError(e instanceof Error?e.message:'Could not load handoff');}}
 async function mutate(path:string,body:SyncRecord,method:'POST'|'PATCH'='POST'){const sequence=openSequence.current;await syncosFetch(path,{method,body});await load();if(selected){const value=await syncosFetch<Detail>(`project-handoffs/${selected}/detail`);if(sequence===openSequence.current)setDetail(value);}}
 const owners=options.staff.map(row=>[String(row.id),String(row.display_name)] as [string,string]);
 const handoff=detail?.project_handoff;const active=Boolean(handoff&&!['project_created','archived'].includes(String(handoff.status)));
 const fields:Input[]=[{name:'operations_owner_user_id',label:'Operations owner',options:owners,required:true},{name:'project_manager_user_id',label:'Project manager',options:owners,required:true},{name:'field_supervisor_user_id',label:'Field supervisor',options:owners},text('scope_summary','Scope summary',true),text('location_summary','Location summary',true),{name:'expected_start_date',label:'Expected start date',type:'date',required:true},{name:'expected_end_date',label:'Expected end date',type:'date'},text('handoff_notes','Handoff notes')];
 return <CommandShell title="Project Handoffs" purpose="Move approved coverage into an explicitly approved planning project."><section className="workspace-panel"><h2>Coverage to project</h2><p>Complete readiness checks, obtain approval, then create the planning project. This does not create work orders, authorize field work, or create financial records.</p>{error&&<p role="alert">{error}</p>}{loading&&canRead&&<p role="status">Loading handoffs…</p>}
 {canCreate&&<Form title="Create project handoff" fields={[{name:'coverage_plan_id',label:'Approved coverage plan',required:true,options:options.sources.map(row=>[String(row.id),`${row.opportunity_name} · ${row.customer_name??'Customer'} · ${row.territory_name??'Territory'}`])},...fields]} submit={async body=>{const source=options.sources.find(row=>row.id===body.coverage_plan_id);if(!source)throw new Error('Choose an approved coverage plan.');const created=await syncosFetch<Detail>('project-handoffs',{method:'POST',body:{...body,opportunity_id:source.opportunity_id}});await load();await open(String(created.project_handoff.id));}}/>}
 <label>Handoff to review<select value={selected} onChange={e=>void open(e.target.value)} style={{minHeight:44,maxWidth:'100%'}}><option value="">Choose a handoff…</option>{rows.map(row=><option key={String(row.id)} value={String(row.id)}>{String(row.opportunity_name)} — {String(row.status).replaceAll('_',' ')}</option>)}</select></label>
 {detail&&handoff&&<section key={selected}><h3>Readiness: {String(handoff.handoff_readiness_band??handoff.status).replaceAll('_',' ')}</h3><p>{detail.recommended_next_action}</p>{handoff.project_id?<PermissionLink href={`/projects/${handoff.project_id}`}>Open created planning project</PermissionLink>:null}
 <ul>{detail.blockers.map((row,i)=><li key={`blocker-${i}`}>Blocked: {String(row.message)}</li>)}{detail.warnings.map((row,i)=><li key={`warning-${i}`}>Warning: {String(row.message)}</li>)}</ul>
 {active&&canUpdate&&<Form key={`edit-${selected}`} title="Save handoff details" fields={fields.map(field=>({...field,value:handoff[field.name]}))} submit={body=>mutate(`project-handoffs/${selected}`,body,'PATCH')}/>}
 <h3>Readiness checklist</h3>{detail.checklist_items.map(item=><div key={String(item.id)} className="workspace-panel"><p>{String(item.label)} — {String(item.status).replaceAll('_',' ')}{item.hard_stop?' · Required gate':''}</p>{active&&canChecklist&&!['complete','not_applicable','overridden','archived'].includes(String(item.status))&&<Form title={`Confirm: ${item.label}`} fields={[{name:'confirmed',label:'I have verified this requirement and its supporting records',type:'checkbox',required:true}]} submit={async()=>mutate(`project-handoff-checklist-items/${item.id}/complete`,{})}/>}</div>)}
 <h3>Risks</h3>{detail.risks.map(risk=><div className="workspace-panel" key={String(risk.id)}><p>{String(risk.message)} — {String(risk.status)}</p>{active&&canResolve&&!['resolved','archived','overridden'].includes(String(risk.status))&&<Form title={`Resolve: ${risk.message}`} fields={[text('resolution_note','Resolution evidence and explanation',true)]} submit={body=>mutate(`project-handoff-risks/${risk.id}/resolve`,body)}/>}</div>)}
 {active&&canRisk&&<Form title="Add handoff risk" fields={[{name:'risk_type',label:'Risk type',required:true,options:['coverage_gap','capacity_gap','compliance_gap','safety_gap','contract_gap','customer_requirement_gap','financial_gap','margin_gap','documentation_gap','schedule_gap','ownership_gap','scope_gap','location_gap','po_ntp_gap','billing_gap','ap_contact_gap','hard_stop_constraint','executive_hold','other'].map(v=>[v,v.replaceAll('_',' ')])},{name:'severity',label:'Severity',required:true,options:['low','medium','high','critical'].map(v=>[v,v])},text('message','Risk description',true),text('recommended_action','Recommended action'),{name:'hard_stop',label:'Block project creation until resolved',type:'checkbox'}]} submit={body=>mutate(`project-handoffs/${selected}/risks`,body)}/>}
 {active&&canRecalculate&&<Form title="Recalculate readiness" fields={[]} submit={body=>mutate(`project-handoffs/${selected}/recalculate`,body)}/>}
 {active&&canSubmit&&handoff.status!=='approved'&&<Form title="Submit readiness review" fields={[text('review_note','Review note',true)]} submit={body=>mutate(`project-handoffs/${selected}/submit-readiness-review`,body)}/>}
 {active&&canApprove&&handoff.status!=='approved'&&detail.blockers.length===0&&<Form title="Approve handoff" fields={[text('approval_note','Approval note',true),...detail.required_override_fields.map(name=>text(name,`Reason accepting warning: ${name.replaceAll('_',' ')}`,true))]} submit={body=>mutate(`project-handoffs/${selected}/approve`,{approval_note:body.approval_note,override_reasons:Object.fromEntries(detail.required_override_fields.map(name=>[name,body[name]]))})}/>}
 {active&&canReject&&<Form title="Reject handoff" fields={[{name:'rejection_reason',label:'Rejection reason',required:true,options:['coverage_not_ready','compliance_blocked','capacity_blocked','scope_incomplete','customer_requirement_missing','financial_risk','duplicate','other'].map(v=>[v,v.replaceAll('_',' ')])},text('rejection_note','Rejection explanation',true)]} submit={body=>mutate(`project-handoffs/${selected}/reject`,body)}/>}
 {handoff.status==='approved'&&!handoff.project_id&&canCreateProject&&canProject&&detail.blockers.length===0&&<Form title="Create planning project" fields={[text('creation_note','Project creation note',true),{name:'confirmed',label:'Create this planning project; field work still needs separate authorization',type:'checkbox',required:true}]} submit={body=>mutate(`project-handoffs/${selected}/create-project`,{creation_note:body.creation_note})}/>}
 </section>}</section></CommandShell>;
}
